"""Trading signals schemas for the REST API.

This module defines response schemas for trading signal data returned
by signal-related endpoints.
"""

from datetime import datetime

from snapper.api.schemas.base import StrictApiSchema
from snapper.interface.websocket.schemas import TradeSide


class TradingSignal(StrictApiSchema):
    """Trading signal response schema.

    Represents a trading signal generated by a strategy.

    Attributes:
        id: Unique signal identifier.
        instrument: Trading instrument symbol.
        exchange: Exchange name (empty string if not specified).
        timestamp: When the signal was generated.
        side: Trade direction (buy/sell).
        strength: Signal strength (0.0-1.0).
        reason: Human-readable reason for the signal.
        strategy_name: Name of the strategy that generated the signal.
        price: Target price for the trade (optional).
    """

    id: int
    instrument: str
    exchange: str = ""
    timestamp: datetime
    side: TradeSide
    strength: float
    reason: str
    strategy_name: str | None
    price: float | None
