"""Trading engine service module.

This module provides the core trading execution logic through TradingEngineService.
Each engine instance manages a single instrument, handling position entry/exit,
stop-loss logic, fee calculation, and order publication to ZMQ.
"""

import datetime as dt
import time
from collections import OrderedDict
from collections.abc import Callable
from dataclasses import dataclass
from decimal import Decimal
from typing import TypedDict
from uuid import uuid7

import zmq
from loguru import logger

from snapper.application.engine.config import EngineConfigModel
from snapper.application.portfolio.models import PortfolioTracker
from snapper.application.risk.models import RiskConfigModel
from snapper.application.risk.models import RiskEvaluator
from snapper.application.trade.caps_enforcer import TradingCapsEnforcer
from snapper.application.trade.outbox import OutboxDispatcher
from snapper.application.trade.submission import TradeCommandSubmission
from snapper.core.partitioning import ShardOwnership
from snapper.core.types import ExchangeEnum
from snapper.core.types import ExecutionModeEnum
from snapper.core.types import FillStatusEnum
from snapper.core.types import OrderCommandEnum
from snapper.core.types import OrderExchange
from snapper.core.types import OrderTypeEnum
from snapper.core.types import TradeCommandStatusEnum
from snapper.core.types import TradeSideEnum
from snapper.core.wallet_short import compute_wallet_short
from snapper.data.repository import SQLAlchemyRepository
from snapper.data.repository_types import TradeCommandInsertRow
from snapper.interface.websocket.schemas import ExecutionMode
from snapper.interface.websocket.schemas import TradeSide
from snapper.messaging.infrastructure.publisher import MessagePublisher
from snapper.messaging.schemas.data import ExecutionData
from snapper.messaging.schemas.data import OrderRequestData
from snapper.messaging.topics.builders import order_command_topic


@dataclass(frozen=True)
class _OrderDispatch:
    """Result of a durable order dispatch.

    Carries both ids the coordinator needs for a paired-execution leg:
    ``client_order_id`` (the venue-facing id, also the engine's in-flight
    key) and ``command_public_id`` (the durable ``TradeCommand`` row id the
    paired-execution leg binds to, so the outbox arming gate can match the
    leg to its command). The two are distinct: the command's ``public_id`` is
    generated by the DB insert, not the venue-facing ``client_order_id``.
    """

    client_order_id: str
    command_public_id: str


class InstrumentSpec(TypedDict, total=False):
    """Per-instrument lookup row carrying lot/tick sizing plus identity.

    All fields optional via ``total=False`` so existing
    ``instrument_specs`` constructions that only stamp
    ``tick_size`` and ``lot_size`` keep typechecking. The
    ``public_id`` key is populated by
    :meth:`TraderCoordinator._resolve_instrument_specs` whenever
    the upstream lookup succeeds; it is the UUID7 identity used
    by the AI-attribution gate to evaluate per-instrument quantity
    and notional caps.
    """

    public_id: str
    tick_size: float
    lot_size: float


class InstrumentSpecMissingError(RuntimeError):
    """Raised when an AI-attributed strategy emit lacks a resolved ``public_id``.

    The strategy hot-path's AI gate
    (:meth:`TradingCapsEnforcer.guard_with_ai_review_attribution`)
    requires a real ``instrument_public_id`` on the submission so the
    notional and per-instrument quantity caps can evaluate. When the
    spec lookup returns no ``public_id`` for an AI-attributed emit the
    engine raises this loud, operator-actionable error before invoking
    the guard. Non-AI strategy emits remain tolerant of a missing
    ``public_id``.
    """


def compute_shard_key(
    *,
    instrument: str,
    exchange: OrderExchange,
    mode: ExecutionMode,
    wallet_public_id: str,
    strategy_tag: str | None,
) -> str:
    """Build the canonical ``shard_key`` for a trading engine.

    This is the single source of truth for shard-key construction, shared
    by the engine, the executor, and the REST and MCP manual-order paths.
    The formula MUST be byte-identical across every call site, because
    ownership checks (``TraderCoordinator._on_signal`` /
    ``_recover_engine_state``) compute the key BEFORE the engine is
    constructed and compare hashes against
    :class:`snapper.core.partitioning.ShardOwnership`. Drift between call
    sites would split ownership across instances.

    Structure: base ``{exchange}.{instrument}.{mode}``; a wallet segment
    ``.w{short}`` is appended when ``wallet_public_id`` is set (``short``
    is the last 12 lowercase hex characters of the wallet id with dashes
    stripped); a ``.{strategy_tag}`` segment is appended for paper mode
    only, when non-empty.

    Args:
        instrument: The traded symbol (e.g., ``"BTC-USD"``).
        exchange: Order-capable exchange identifier.
        mode: Execution mode — ``"live"`` or ``"paper"``.
        wallet_public_id: Wallet id owning the engine's position.
            Empty string to omit the wallet segment.
        strategy_tag: Strategy discriminator for paper sharding.
            Ignored for ``live`` mode. ``None`` / empty omits the tag.

    Returns:
        The canonical shard key string.
    """
    base = f"{exchange}.{instrument}.{mode}"
    if wallet_public_id:
        wallet_short = compute_wallet_short(wallet_public_id)
        base = f"{base}.w{wallet_short}"
    if mode == ExecutionModeEnum.PAPER and strategy_tag:
        return f"{base}.{strategy_tag}"
    return base


class TradingEngineService:
    """Trading engine for executing trades on a single instrument.

    Manages the complete trading lifecycle for one symbol including:
    - Position tracking (entry price, quantity)
    - Risk-based position sizing
    - Stop-loss execution
    - Order publishing to ZMQ execution topic
    - Mark-to-market equity calculation

    Each TraderCoordinator creates one TradingEngineService per active symbol.
    The engine consumes strategy signals and translates them into concrete
    order requests.

    Attributes:
        instrument: Symbol being traded (e.g., "BTC-USD").
        execution_socket: ZMQ publisher for sending order requests.
        exchange: Target exchange for order execution.
        cfg: Engine configuration (initial cash, fees).
        portfolio: Tracks cash and positions.
        risk: Risk evaluator for position sizing.
        position_qty: Current position size.
        peak_equity: Highest equity reached (for drawdown calculation).
        entry_price: Price at which current position was opened.
        instrument_specs: Lot size and tick size specifications.
    """

    IN_FLIGHT_TIMEOUT: float = 60.0

    instrument: str
    execution_socket: MessagePublisher
    exchange: OrderExchange
    cfg: EngineConfigModel
    portfolio: PortfolioTracker
    risk: RiskEvaluator
    position_qty: float
    peak_equity: float
    entry_price: float | None
    instrument_specs: dict[str, InstrumentSpec]
    order_in_flight: bool
    seen_exec_ids: OrderedDict[str, None]

    def __init__(
        self,
        instrument: str,
        execution_socket: MessagePublisher,
        risk: RiskEvaluator | None = None,
        cfg: EngineConfigModel | None = None,
        *,
        instrument_specs: dict[str, InstrumentSpec] | None = None,
        exchange: OrderExchange = ExchangeEnum.PAPER,
        repository: SQLAlchemyRepository | None = None,
        outbox: OutboxDispatcher | None = None,
        strategy_tag: str | None = None,
        wallet_public_id: str = "",
        operator_public_id: str = "",
        ownership: ShardOwnership | None = None,
        caps_enforcer: TradingCapsEnforcer | None = None,
    ) -> None:
        """Initialize trading engine for a specific instrument.

        Args:
            instrument: Symbol to trade (e.g., "BTC-USD").
            execution_socket: Message publisher for order requests.
            risk: Risk evaluator instance. Defaults to standard RiskEvaluator.
            cfg: Engine configuration. Defaults to EngineConfigModel defaults.
            instrument_specs: Dict mapping symbol to lot_size/tick_size specs.
            exchange: Target exchange. Defaults to "paper" for simulation.
            repository: Optional DB repository for writing TradeCommand.
            outbox: Optional outbox dispatcher to notify after DB write.
            strategy_tag: Strategy discriminator for paper mode sharding.
                Paper engines with different tags get isolated shard_keys.
                Ignored for live mode (one consolidated position per instrument).
            wallet_public_id: Wallet that owns positions and credentials for
                this engine instance. The ``""`` default exists for test
                fixtures; the trade-command wallet columns are NOT NULL,
                and production call sites always pass a real wallet id.
            operator_public_id: Trading-identity operator that initiated the
                strategy this engine serves. Stored on the engine for audit
                propagation onto every TradeCommand and OrderRequestData
                this engine emits.
            ownership: partitioning — the coordinator's
                :class:`ShardOwnership` view, forwarded to
                :meth:`Repository.insert_trade_command` as a
                defense-in-depth guard against operational misconfig
                ``None`` bypasses the guard (test fixtures,
                CLI tools, and single-instance deployments).
            caps_enforcer: enforcer — when present
                ``_send_order`` wraps the insert with
                :meth:`TradingCapsEnforcer.guard_service_principal`
                so cap enforcement logic is exercised even on the
                strategy hot path (bypass is explicit at the call
                site). ``None`` preserves the
                direct-insert path (test fixtures that construct
                the engine without DI).
        """
        self.instrument = instrument
        self.execution_socket = execution_socket
        self.exchange = exchange
        self.cfg = cfg or EngineConfigModel()
        self.portfolio = PortfolioTracker(cash=self.cfg.initial_cash)
        self.risk = risk or RiskEvaluator(RiskConfigModel())
        self.position_qty = 0.0
        self.peak_equity = self.cfg.initial_cash
        self.entry_price: float | None = None
        self.instrument_specs = instrument_specs or {}
        self.order_in_flight = False
        self._pending_client_order_id: str | None = None
        self.pending_coid_listener: Callable[[str | None, str | None], None] | None = None
        self._in_flight_since: float | None = None
        self._pending_unknown = False
        self.seen_exec_ids: OrderedDict[str, None] = OrderedDict()
        self._repository = repository
        self._outbox = outbox
        self._strategy_tag = strategy_tag
        self.wallet_public_id = wallet_public_id
        self.operator_public_id = operator_public_id
        self._ownership = ownership
        self._caps_enforcer = caps_enforcer
        self._shard_key = compute_shard_key(
            instrument=instrument,
            exchange=exchange,
            mode=self.mode,
            wallet_public_id=wallet_public_id,
            strategy_tag=strategy_tag,
        )

    @property
    def pending_client_order_id(self) -> str | None:
        """Return the client_order_id of the currently in-flight submission.

        Returns:
            The in-flight client_order_id, or ``None`` when no submission
            is awaiting a fill (and also when the engine was built via
            ``__new__`` without running ``__init__``).
        """
        return getattr(self, "_pending_client_order_id", None)

    @pending_client_order_id.setter
    def pending_client_order_id(self, value: str | None) -> None:
        """Set the in-flight client_order_id and notify any registered listener.

        ``TraderCoordinator`` registers a listener on each engine after
        construction so the per-frame fill dispatch can resolve
        coid -> engine via an O(1) index instead of scanning every
        engine. The listener is invoked only on actual change (set,
        clear, replace) to keep the index consistent without redundant
        callbacks during ``order_in_flight`` recovery paths.

        Tolerates engines constructed via ``__new__`` without running
        ``__init__`` (unit-test fixtures): a missing backing slot or
        missing listener attribute is treated as "no previous value"
        / "no listener" rather than raising.

        Args:
            value: The new in-flight client_order_id, or ``None`` to
                clear the pending submission.
        """
        previous = getattr(self, "_pending_client_order_id", None)
        if previous == value:
            return
        self._pending_client_order_id = value
        listener = getattr(self, "pending_coid_listener", None)
        if listener is not None:
            listener(previous, value)

    def _build_strategy_insert_row(
        self,
        *,
        order_public_id: str,
        reason: str,
        side: str,
        size: float,
        leverage: int | None,
        reduce_only: bool,
        now: dt.datetime,
        session_id: str,
        sequence_id: int,
        grouped_correlation_id: str | None = None,
        reference_price: float | None = None,
    ) -> TradeCommandInsertRow:
        """Return the TradeCommand insert row for a strategy submit.

        Factored out of ``_send_order`` so the same row is used whether
        the insert is wrapped by
        :meth:`TradingCapsEnforcer.guard_service_principal` (production)
        or issued directly (test fixtures without a caps enforcer).

        When ``grouped_correlation_id`` is set (a paired-execution leg), it
        becomes the command's ``correlation_id`` so the command joins its
        paired-execution group and is held by the outbox arming gate until
        the group arms; otherwise ``correlation_id`` defaults to the order's
        own public id (the existing per-order behaviour).

        ``reference_price`` is the paper-venue fill reference: the paper
        simulator fills a market order at ``order.price``, so paper
        engines pass the validated signal price here and it rides the
        existing ``price`` column onto the dispatch payload. Live-venue
        market commands MUST keep it ``None`` — a real exchange must
        never receive a market order carrying a price.
        """
        return {
            "command_type": OrderCommandEnum.SUBMIT,
            "shard_key": self._shard_key,
            "exchange": self.exchange,
            "instrument": self.instrument,
            "mode": self.mode,
            "strategy_id": reason,
            "client_order_id": order_public_id,
            "venue_client_id": order_public_id,
            "side": side,
            "order_type": "market",
            "quantity": size,
            "price": reference_price,
            "leverage": leverage,
            "reduce_only": reduce_only,
            "status": TradeCommandStatusEnum.CREATED,
            "created_at": now,
            "correlation_id": (
                grouped_correlation_id if grouped_correlation_id is not None else order_public_id
            ),
            "session_id": session_id,
            "sequence_id": sequence_id,
            "timestamp": now,
            "wallet_public_id": self.wallet_public_id or "",
            "operator_public_id": self.operator_public_id or None,
            "source_surface": "strategy",
        }

    def _check_in_flight_timeout(self) -> None:
        """Clear in-flight guard if timeout has elapsed.

        Called before processing new signals. If the configured timeout
        has passed since the order was sent, logs a warning and clears
        the guard so new signals can be processed.

        EXCEPTION: when the pending order's submit outcome
        is UNKNOWN (``_pending_unknown``), the guard is NEVER cleared on
        timeout — the order may be live on the venue, and clearing
        would let a replacement order through, doubling exposure. The
        guard holds until venue verification resolves the order to
        accepted (flag clears, normal lifecycle resumes) or rejected
        (``clear_pending_intent`` releases the guard).
        """
        if not self.order_in_flight or self._in_flight_since is None:
            return
        elapsed = time.monotonic() - self._in_flight_since
        if elapsed > self.IN_FLIGHT_TIMEOUT:
            if self._pending_unknown:
                logger.error(
                    f"Order {self.pending_client_order_id} in-flight timeout "
                    f"after {elapsed:.1f}s for {self.instrument} but submit state "
                    f"is UNKNOWN — holding guard (no re-emission until venue "
                    f"verification resolves)"
                )
                return
            logger.warning(
                f"Order {self.pending_client_order_id} in-flight timeout "
                f"after {elapsed:.1f}s for {self.instrument}, clearing guard"
            )
            self.order_in_flight = False
            self.pending_client_order_id = None
            self._in_flight_since = None

    def mark_pending_unknown(self, client_order_id: str) -> bool:
        """Flag the current pending order as having an UNKNOWN submit outcome.

        Only acts when the given client_order_id matches the current
        pending order (mirrors ``clear_pending_intent`` matching) so a
        stale event cannot freeze the guard for a newer order.

        Args:
            client_order_id: Order ID from the unknown event.

        Returns:
            True if the flag was set, False if ID did not match.
        """
        if client_order_id != self.pending_client_order_id:
            return False
        self._pending_unknown = True
        return True

    def clear_pending_unknown(self, client_order_id: str) -> bool:
        """Resolve a previously UNKNOWN submit back to a known state.

        Called when a late ACCEPTED event arrives for the order: the
        in-flight guard stays held (the order is live, awaiting fills)
        but the timeout safety valve behaves normally again.

        Args:
            client_order_id: Order ID from the resolving event.

        Returns:
            True only when the order matched AND was actually flagged
            UNKNOWN (so callers can log the resolution without firing
            on every ordinary acceptance).
        """
        if client_order_id != self.pending_client_order_id:
            return False
        if not self._pending_unknown:
            return False
        self._pending_unknown = False
        return True

    def apply_fill(self, fill: ExecutionData) -> bool:
        """Apply a confirmed execution fill to engine state.

        Uses delta fields (last_size/last_price) for booking. Duplicate
        fills are detected by exec_id/trade_id and silently dropped.
        Clears order_in_flight only when the fill matches the current
        pending order and status is 'filled' (complete).

        Args:
            fill: Execution event with delta fill data.

        Returns:
            True if fill was applied, False if duplicate.
        """
        guard_key = (
            fill.trade_id or f"fallback-{fill.client_order_id}-{fill.last_size}-{fill.last_price}"
        )
        if guard_key in self.seen_exec_ids:
            logger.info(f"Duplicate execution {guard_key} ignored for {self.instrument}")
            return False
        self.seen_exec_ids[guard_key] = None
        if len(self.seen_exec_ids) > 10_000:
            self.seen_exec_ids.popitem(last=False)
        self.portfolio.update_fill(
            self.instrument, fill.side, fill.last_size, fill.last_price, fill.fee
        )
        old_qty = self.position_qty
        if fill.side == TradeSideEnum.BUY:
            self.position_qty += fill.last_size
        else:
            self.position_qty -= fill.last_size
        if abs(self.position_qty) < 1e-12:
            self.position_qty = 0.0
            self.entry_price = None
        elif old_qty <= 0 < self.position_qty or old_qty >= 0 > self.position_qty:
            self.entry_price = fill.last_price
        elif self.entry_price is not None and abs(self.position_qty) > abs(old_qty):
            old_abs = abs(old_qty)
            new_abs = abs(self.position_qty)
            self.entry_price = (
                old_abs * self.entry_price + fill.last_size * fill.last_price
            ) / new_abs
        if (
            fill.client_order_id == self.pending_client_order_id
            and fill.status == FillStatusEnum.FILLED
        ):
            self.order_in_flight = False
            self.pending_client_order_id = None
            self._in_flight_since = None
            self._pending_unknown = False
        return True

    def clear_pending_intent(self, client_order_id: str) -> bool:
        """Clear in-flight state for a rejected or cancelled order.

        Only clears if the given client_order_id matches the current
        pending order, preventing stale events from clearing newer orders.

        Args:
            client_order_id: Order ID from the reject/cancel event.

        Returns:
            True if intent was cleared, False if ID did not match.
        """
        if client_order_id != self.pending_client_order_id:
            return False
        self.order_in_flight = False
        self.pending_client_order_id = None
        self._in_flight_since = None
        self._pending_unknown = False
        return True

    def rearm_pending_intent(self, client_order_id: str) -> bool:
        """Re-arm the in-flight guard for a venue-live adopted order (#155).

        A released engine (it consumed a false REJECTED, or the lazy
        timeout valve cleared the guard) never learns the order is live
        again — the next signal would emit a NEW order while the adopted
        one still works the book. Called by the coordinator on an
        adoption-shaped ACCEPTED (``reason="adopted"``). Deliberately NOT
        the restart-only ``_mark_order_in_flight`` semantics: that helper
        overwrites ``pending_client_order_id`` unconditionally, which on
        a running engine would clobber a newer live intent.

        Dispositions:
            - in flight for a DIFFERENT order: no-op, returns False
              (clobber guard — the newer intent wins; the residual is
              the coordinator's WARN).
            - in flight for the SAME order: refresh ``_in_flight_since``
              (a live venue observation must not let a near-expired
              valve clear right after adoption), returns True.
            - released: arm with a FRESH timeout window — parity with
              restart recovery, NOT the never-released timeline; after
              the fresh window lapses with the order still live the
              valve clears again (accepted residual, see task #155).
              ``_pending_unknown`` resets: a venue-confirmed-live order
              is by definition no longer ambiguous.

        Args:
            client_order_id: The adopted order's client id.

        Returns:
            True when the guard was re-armed or refreshed.
        """
        if self.order_in_flight:
            if self.pending_client_order_id != client_order_id:
                return False
            self._in_flight_since = time.monotonic()
            return True
        self.order_in_flight = True
        self.pending_client_order_id = client_order_id
        self._in_flight_since = time.monotonic()
        self._pending_unknown = False
        return True

    @property
    def mode(self) -> ExecutionMode:
        """Get execution mode based on exchange type.

        Returns:
            "paper" for paper trading, "live" for real exchanges.
        """
        return (
            ExecutionModeEnum.PAPER
            if self.exchange == ExchangeEnum.PAPER
            else ExecutionModeEnum.LIVE
        )

    def _mark_to_market(self, last_close: float) -> float:
        """Calculate current equity and update peak equity.

        Computes total portfolio value as cash plus position value
        at current market price. Updates peak equity for drawdown tracking.

        Args:
            last_close: Current market price of the instrument.

        Returns:
            Current total equity value.
        """
        equity = self.portfolio.cash + self.position_qty * last_close
        self.peak_equity = max(self.peak_equity, equity)
        logger.debug({"equity": equity, "peak": self.peak_equity})
        return equity

    async def _maybe_stop(self, last_close: float, prev_close: float | None = None) -> bool:
        """Check and execute stop-loss if triggered.

        Monitors position against stop-loss threshold:
        - Long: triggers when price drops below entry by stop_pct
        - Short: triggers when price rises above entry by stop_pct
        - Fast move detection from previous close in both directions

        Args:
            last_close: Current market price.
            prev_close: Previous bar's close price for fast-move detection.

        Returns:
            True if stop-loss was triggered and position closed, False otherwise.
        """
        if abs(self.position_qty) < 1e-12:
            return False
        if self.order_in_flight:
            return False
        stop_ref = self.entry_price
        if stop_ref is None:
            pos = self.portfolio.positions.get(self.instrument)
            stop_ref = pos.average_price if pos and pos.quantity != 0 else None
        stop_pct = self.risk.stop_pct()
        if self.position_qty > 0:
            trigger_ref = stop_ref is not None and last_close <= stop_ref * (1 - stop_pct)
            trigger_fast = prev_close is not None and last_close <= prev_close * (1 - stop_pct)
            stop_side = TradeSideEnum.SELL
            stop_size = self.position_qty
        else:
            trigger_ref = stop_ref is not None and last_close >= stop_ref * (1 + stop_pct)
            trigger_fast = prev_close is not None and last_close >= prev_close * (1 + stop_pct)
            stop_side = TradeSideEnum.BUY
            stop_size = abs(self.position_qty)
        if trigger_ref or trigger_fast:
            dispatch = await self._send_order(
                side=stop_side,
                size=stop_size,
                price=last_close,
                reason="engine-stop",
            )
            self.order_in_flight = True
            self.pending_client_order_id = dispatch.client_order_id
            self._in_flight_since = time.monotonic()
            return True
        return False

    async def _insert_strategy_trade_command(
        self,
        submission: TradeCommandSubmission,
        insert_row: TradeCommandInsertRow,
        *,
        ai_review_public_id: str | None,
        ai_review_dispatch_version: int | None,
    ) -> str:
        """Route the strategy emit through the appropriate caps gate.

        Returns the inserted command's durable ``public_id`` (the value a
        paired-execution leg binds to via ``command_public_id``), discarded
        by non-grouped callers.

        Three-way selection:
            1. ``ai_review_public_id`` set → AI-attribution guard
               (resolves user from cited row, runs caps).
            2. caps_enforcer wired but no AI attribution →
               ``guard_service_principal`` (existing audit-bypass
               behaviour, byte-identical for non-AI strategy emits).
            3. No caps_enforcer (test fixture) → direct insert.

        Args:
            submission: The constructed
                :class:`TradeCommandSubmission` (already carries
                attribution kwargs when present).
            insert_row: The pre-built
                :class:`TradeCommandInsertRow` for the SQL insert.
            ai_review_public_id: Optional citation from the
                ``SignalData`` envelope, threaded down through
                :meth:`execute_desired_units` → :meth:`_send_order`.
            ai_review_dispatch_version: Companion to the citation
                (transport-only).
        """
        repository = self._repository
        if repository is None:
            raise RuntimeError("TradingEngineService repository not initialized")
        if self._caps_enforcer is not None and ai_review_public_id is not None:
            async with self._caps_enforcer.guard_with_ai_review_attribution(
                submission,
                ai_review_public_id=ai_review_public_id,
                ai_review_dispatch_version=ai_review_dispatch_version,
            ):
                _, command_public_id = await repository.insert_trade_command(
                    insert_row, ownership=self._ownership
                )
            return command_public_id
        if self._caps_enforcer is not None:
            async with self._caps_enforcer.guard_service_principal(submission):
                _, command_public_id = await repository.insert_trade_command(
                    insert_row, ownership=self._ownership
                )
            return command_public_id
        _, command_public_id = await repository.insert_trade_command(
            insert_row, ownership=self._ownership
        )
        return command_public_id

    async def _send_order(
        self,
        side: TradeSide,
        size: float,
        price: float,
        reason: str,
        signaled_at: float | None = None,
        leverage: int | None = None,
        reduce_only: bool = False,
        *,
        ai_review_public_id: str | None = None,
        ai_review_dispatch_version: int | None = None,
        grouped_correlation_id: str | None = None,
    ) -> _OrderDispatch:
        """Publish order request via the durable-outbox path.

        Writes a durable ``TradeCommand`` row to DB and notifies the
        ``OutboxDispatcher`` — the dispatcher owns the ZMQ publish.
        The dual-write in-process fallback remains for unit tests that
        construct the engine without an outbox (MagicMock repos, no
        SQL backing); production always wires the outbox via
        ``TraderCoordinator._setup_trade_services``.

        Args:
            side: Order side ("buy" or "sell").
            size: Order quantity.
            price: Reference price. On paper-venue engines it is
                forwarded as the market order's fill reference (the
                paper simulator fills at ``order.price``; previously it
                was discarded and paper fills booked at 0.0). Live-venue
                market commands never carry it.
            reason: Order reason tag (e.g., "engine-buy", "engine-stop").
            signaled_at: Unix timestamp when signal was generated.
            leverage: Margin leverage (None for spot).
            reduce_only: True when closing a position.
            ai_review_public_id: Optional citation forwarded from
                :class:`SignalData` so the strategy hot-path can route
                through the attribution-aware caps gate. ``None`` keeps
                the existing service-principal bypass.
            ai_review_dispatch_version: Companion to
                ``ai_review_public_id`` — transport-only;
                the strategy citation validator does not compare it.
            grouped_correlation_id: When set (a paired-execution leg),
                stamped as the command's correlation_id so it joins its
                group and is held by the outbox arming gate until armed.

        Returns:
            An :class:`_OrderDispatch` carrying the venue ``client_order_id``
            and the durable ``command_public_id`` (for binding a
            paired-execution leg).

        Raises:
            InstrumentSpecMissingError: When ``ai_review_public_id`` is
                set but ``instrument_specs[self.instrument]`` lacks the
                ``public_id`` key. AI-attributed emits require a
                resolved ``instrument_public_id`` so the caps evaluator
                can run quantity / notional checks; failing closed
                makes the spec-loader gap loud and operator-actionable.
        """
        signaled_at_dt = None
        if signaled_at is not None:
            signaled_at_dt = dt.datetime.fromtimestamp(signaled_at, tz=dt.UTC)
        reference_price = price if self.exchange == ExchangeEnum.PAPER else None
        topic = order_command_topic(self.exchange, self.instrument, OrderCommandEnum.SUBMIT)
        order_public_id = str(uuid7())
        now = dt.datetime.now(dt.UTC)
        session_id = self.execution_socket.tracker.session_id
        sequence_id = self.execution_socket.tracker.next_sequence(topic)

        spec = self.instrument_specs.get(self.instrument, InstrumentSpec())
        instrument_public_id = spec.get("public_id")
        if ai_review_public_id is not None and instrument_public_id is None:
            raise InstrumentSpecMissingError(
                f"AI-attributed strategy emit for {self.instrument!r} "
                "requires instrument_specs[...]['public_id'] to be "
                "populated by the spec loader; aborting before caps "
                "guard so the failure is loud + operator-actionable."
            )

        command_public_id = order_public_id
        if self._repository is not None:
            strategy_submission = TradeCommandSubmission(
                user_public_id=None,
                operator_public_id=self.operator_public_id or None,
                wallet_public_id=self.wallet_public_id or None,
                instrument_public_id=instrument_public_id,
                command_type=OrderCommandEnum.SUBMIT,
                side=side,
                order_type="market",
                quantity=Decimal(str(size)),
                price=None,
                source_surface="strategy",
                idempotency_key=None,
                ai_review_public_id=ai_review_public_id,
                ai_review_dispatch_version=ai_review_dispatch_version,
            )
            insert_row = self._build_strategy_insert_row(
                order_public_id=order_public_id,
                reason=reason,
                side=side,
                size=size,
                leverage=leverage,
                reduce_only=reduce_only,
                now=now,
                session_id=session_id,
                sequence_id=sequence_id,
                grouped_correlation_id=grouped_correlation_id,
                reference_price=reference_price,
            )
            command_public_id = await self._insert_strategy_trade_command(
                strategy_submission,
                insert_row,
                ai_review_public_id=ai_review_public_id,
                ai_review_dispatch_version=ai_review_dispatch_version,
            )

        if self._outbox is not None:
            self._outbox.notify()
            logger.debug(f"Durable command written, outbox notified: {order_public_id}")
        else:
            order = OrderRequestData(
                public_id=order_public_id,
                timestamp=now,
                session_id=session_id,
                sequence_id=sequence_id,
                strategy_id=reason,
                instrument=self.instrument,
                mode=self.mode,
                side=side,
                order_type=OrderTypeEnum.MARKET,
                quantity=size,
                price=reference_price,
                client_order_id=order_public_id,
                exchange=self.exchange,
                strategy_tag=self._strategy_tag,
                signaled_at=signaled_at_dt,
                leverage=leverage,
                reduce_only=reduce_only,
                wallet_public_id=self.wallet_public_id,
                operator_public_id=self.operator_public_id or None,
            )
            await self.execution_socket.send(topic, order, flags=zmq.NOBLOCK)
            if self._repository is not None:
                await self._repository.update_trade_command_status(
                    public_id=order_public_id,
                    new_status=TradeCommandStatusEnum.DIRECT_DISPATCHED,
                    bus_time=now,
                    session_id=session_id,
                    sequence_id=sequence_id,
                    dispatched_at=now,
                    attempt_count=1,
                )
            logger.debug(f"Published order command (direct): {order_public_id}")
        return _OrderDispatch(client_order_id=order_public_id, command_public_id=command_public_id)

    def _cap_opening_size(
        self, opening_qty: float, current_price: float, closing_proceeds: float = 0.0
    ) -> float:
        """Apply leverage, cash, and lot-size constraints to the opening portion.

        For flip transitions, closing_proceeds estimates the cash freed by
        closing the existing position so the opening cap reflects post-close state.

        Args:
            opening_qty: Unsigned quantity for the new direction.
            current_price: Current market price.
            closing_proceeds: Estimated cash from closing the existing position.

        Returns:
            Capped and rounded opening quantity (unsigned).
        """
        fee_rate = self.cfg.fee_bps / 10000.0
        reserve = max(0.01, self.portfolio.cash * 1e-3)
        cash_avail = max(self.portfolio.cash + closing_proceeds - reserve, 0.0)
        exposure = self.portfolio.notional_exposure(self.instrument, current_price)
        effective_cash = cash_avail / (1.0 + fee_rate)
        post_close_exposure = max(exposure - closing_proceeds, 0.0)
        opening_qty = self.risk.cap_size_by_leverage(
            post_close_exposure, effective_cash, current_price, opening_qty
        )
        max_size_by_cash = effective_cash / current_price if current_price > 0 else 0.0
        opening_qty = max(min(opening_qty, max_size_by_cash), 0.0)
        specs = self.instrument_specs.get(self.instrument, {})
        lot = float(specs.get("lot_size", 0.0))
        tick = float(specs.get("tick_size", 0.0))
        return self.risk.round_size(opening_qty, lot, current_price, tick)

    def _classify_delta(self, desired_units: float, abs_delta: float) -> tuple[float, float]:
        """Split position delta into closing and opening portions.

        For flip transitions the closing portion is unconstrained, while
        the opening portion will be subject to cash and leverage caps.

        Args:
            desired_units: Target position size.
            abs_delta: Absolute size of the position change.

        Returns:
            Tuple of (closing_qty, opening_qty), both unsigned.
        """
        crosses_zero = (self.position_qty > 0 and desired_units < 0) or (
            self.position_qty < 0 and desired_units > 0
        )
        is_opening = (self.position_qty <= 0 and desired_units > 0) or (
            self.position_qty >= 0 and desired_units < 0
        )
        if crosses_zero:
            closing = abs(self.position_qty)
            return closing, abs_delta - closing
        if is_opening:
            return 0.0, abs_delta
        is_reducing = abs(desired_units) < abs(self.position_qty)
        if is_reducing:
            return abs_delta, 0.0
        return 0.0, abs_delta

    async def execute_desired_units(
        self,
        desired_units: float,
        current_price: float,
        signaled_at: float | None = None,
        *,
        ai_review_public_id: str | None = None,
        ai_review_dispatch_version: int | None = None,
        grouped_correlation_id: str | None = None,
    ) -> str | None:
        """Execute position change based on desired position size.

        Main entry point for strategy signal execution. Compares desired position
        with current position and sends appropriate buy/sell orders. Supports
        long, short, and flip transitions.

        For flips (long→short or short→long), the delta is split into a closing
        portion (uncapped) and an opening portion (subject to cash/leverage caps).

        Portfolio and position state are NOT updated here; they change only
        when confirmed fills arrive via apply_fill().

        Args:
            desired_units: Target position size (positive=long, negative=short, 0=flat).
            current_price: Current market price for sizing calculations.
            signaled_at: Unix timestamp when signal was generated.
            ai_review_public_id: Optional citation forwarded from
                :class:`SignalData` so the strategy hot-path can route through
                :meth:`TradingCapsEnforcer.guard_with_ai_review_attribution`.
                ``None`` preserves the existing
                ``guard_service_principal()`` audit-bypass behavior.
            ai_review_dispatch_version: Companion to
                ``ai_review_public_id``; transport-only — the
                strategy citation validator does not compare it.
            grouped_correlation_id: When set (a paired-execution leg),
                stamped as the command's correlation_id so the command
                joins its paired-execution group and is held by the outbox
                arming gate until the group arms.

        Returns:
            The durable command ``public_id`` when an order was dispatched
            (for the coordinator to bind a paired-execution leg), else
            ``None`` (an order already in flight, or no order needed).
        """
        self._check_in_flight_timeout()
        if self.order_in_flight:
            logger.warning(
                f"Order {self.pending_client_order_id} still in flight for "
                f"{self.instrument}, dropping signal"
            )
            return None
        delta = desired_units - self.position_qty
        if abs(delta) < 1e-12:
            return None
        equity = self._mark_to_market(current_price)
        side = TradeSideEnum.BUY if delta > 0 else TradeSideEnum.SELL
        closing_qty, opening_qty = self._classify_delta(desired_units, abs(delta))
        if opening_qty > 0:
            if not self.risk.can_open_new_trade(equity, self.peak_equity):
                opening_qty = 0.0
            else:
                proceeds = closing_qty * current_price if closing_qty > 0 else 0.0
                opening_qty = self._cap_opening_size(opening_qty, current_price, proceeds)
        total_order = closing_qty + opening_qty
        specs = self.instrument_specs.get(self.instrument, {})
        lot = float(specs.get("lot_size", 0.0))
        total_order = self.risk.round_down_to_step(total_order, lot)
        if total_order <= 0:
            return None
        reason = "engine-buy" if side == TradeSideEnum.BUY else "engine-sell"
        is_pure_close = closing_qty > 0 and opening_qty <= 0
        dispatch = await self._send_order(
            side=side,
            size=total_order,
            price=current_price,
            reason=reason,
            signaled_at=signaled_at,
            leverage=self.cfg.leverage,
            reduce_only=is_pure_close,
            ai_review_public_id=ai_review_public_id,
            ai_review_dispatch_version=ai_review_dispatch_version,
            grouped_correlation_id=grouped_correlation_id,
        )
        self.order_in_flight = True
        self.pending_client_order_id = dispatch.client_order_id
        self._in_flight_since = time.monotonic()
        return dispatch.command_public_id
