"""AiReviewService — SOLE owner of the ``ai_reviews`` state machine.

Responsibilities (Plan A v1.4 + Plan D v1.1):

- Q9 — atomic state-machine transitions (pending -> resolved/timeout/superseded)
  with the writable-CTE counter primitive that keeps
  ``ai_delegates.active_reviews_count`` consistent under concurrent
  decisions.
- Q10 — admission control: pick a live delegate that has an open
  scope grant + at most one in-flight review.
- Q14 — emit success/error envelopes for the ``submit_ai_review_decision``
  MCP tool + the matching REST endpoint.
- Q17 — own the layered offline-detection: Layer 1 fast path triggered by
  ``WebSocketAuthManager`` ``bus.delegate_offline`` events; Layer 2 DB
  scanner that catches stragglers when no socket close was observed.
- Q18 — protocol-level dedup via ``dispatch_version`` so the bridge can
  ignore replays generated by the offline-scanner re-fanout.

This module exposes only the **skeleton** — singleton lifecycle, the
in-memory ``asyncio.Future`` registry that backs the strategy-side
``await ai_review`` primitive, and the bus-publisher injection seam.
The heavy state-machine methods land in subsequent commits per the
Plan D §3 layout (``create_review`` / ``submit_decision`` / reaper /
offline scanner).

The futures registry is the load-bearing in-process channel between the
WS-listener path (which receives ``bus.ai_review_decision`` and resolves
the future) and the strategy path (which awaits creation of the review).
Both sides MUST share the same singleton; otherwise the strategy would
hang on a future the listener can't see. Tests reset the singleton via
:meth:`clear_instance` between cases to avoid cross-test future leakage.
"""

import asyncio
from dataclasses import dataclass
from datetime import UTC
from datetime import datetime
from uuid import uuid7

from loguru import logger

from snapper.auth.scope_grant_service import ScopeGrantService
from snapper.core.json_types import JsonValue
from snapper.core.types import AiReviewDecisionEnum
from snapper.core.types import AiReviewEventTypeEnum
from snapper.core.types import AiReviewResolutionModeEnum
from snapper.core.types import AiReviewStatusEnum
from snapper.data.repository import Repository
from snapper.data.repository_types import AiReviewRow
from snapper.messaging.infrastructure.publisher import MessagePublisher

ERROR_REVIEW_NOT_FOUND = "review_not_found"
"""Plan A Q14 envelope error code — caller passed an unknown review_id."""

ERROR_NOT_AUTHORIZED = "not_authorized"
"""Plan A Q14 — caller's delegate has no scope grant for the review's wallet+instrument."""

ERROR_PEER_RESOLVED = "review_already_resolved_by_peer"
"""Plan A Q14 — terminal status reached by another decision (or reaper) before us."""

ERROR_REVIEW_EXPIRED = "review_id_expired"
"""Plan A Q14 — Q9 step 3.5 inline timeout: deadline elapsed before the decision arrived."""

ERROR_DECISION_ALREADY_RECORDED = "decision_already_recorded"
"""Plan A Q14 — idempotent retry: same delegate, same decision, already-resolved row.

Returned with ``error_code`` set so the client surfaces the duplicate as success
(success=True per the Plan A Q14 envelope), while still flagging the no-op for
audit and metrics dashboards.
"""


@dataclass(slots=True)
class AiReviewDecisionResult:
    """Envelope returned by :meth:`AiReviewService.submit_decision`.

    Plan A Q14 contract — ``error_code`` is the load-bearing discriminator:

    - ``None`` -> first valid decision; the row transitioned and the
      decision was recorded for the first time.
    - :data:`ERROR_DECISION_ALREADY_RECORDED` -> idempotent retry; the
      caller is the responding delegate and the decision matches what we
      already have. Treated as success at the MCP layer.
    - Any other code -> hard error; the MCP layer flips ``success=False``.

    ``status`` and ``resolution_mode`` reflect the row's current state
    AFTER any transition this call performed (or simply observed). For
    ``ERROR_REVIEW_NOT_FOUND`` they are ``None`` since there is no row to
    report on.
    """

    error_code: str | None
    message: str
    status: AiReviewStatusEnum | None
    resolution_mode: AiReviewResolutionModeEnum | None
    dispatch_version: int | None
    details: dict[str, JsonValue]


_TERMINAL_STATUSES = frozenset(
    {
        AiReviewStatusEnum.RESOLVED_APPROVED.value,
        AiReviewStatusEnum.RESOLVED_REJECTED.value,
        AiReviewStatusEnum.TIMEOUT.value,
        AiReviewStatusEnum.SUPERSEDED.value,
    }
)
"""Plan A Q9 — terminal statuses that block further transitions."""


class NoLiveDelegateError(Exception):
    """No eligible AI delegate is live within the heartbeat window.

    Raised by :meth:`AiReviewService.create_review` when admission control finds
    no eligible AI delegate for the requested scope (operator + wallet +
    instrument). The strategy turns this into a Plan A Q11 ``no_live_delegate``
    outcome and decides whether to abort, retry, or fall through to the human
    path according to its own policy.
    """


class DelegateBusyError(Exception):
    """Every eligible delegate already has an in-flight review.

    Raised by :meth:`AiReviewService.create_review` when every eligible delegate
    has ``active_reviews_count > 0``. Plan A Q10 caps each delegate at one
    in-flight review; busy-everywhere is a transient signal the strategy can
    retry against, distinct from :class:`NoLiveDelegateError` (which means
    there is nobody to wait for).
    """


class AiReviewService:
    """Singleton owner of the ``ai_reviews`` state machine + future registry."""

    _instance: AiReviewService | None = None
    _initialized: bool = False

    def __new__(cls) -> AiReviewService:
        """Create or return the singleton instance."""
        if cls._instance is None:
            instance = super().__new__(cls)
            cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        """Initialise publisher slot + futures registry on first construction."""
        if self._initialized:
            return
        self._initialized = True
        self._msg_publisher: MessagePublisher | None = None
        self._futures: dict[str, asyncio.Future[object]] = {}

    def set_msg_publisher(self, publisher: MessagePublisher | None) -> None:
        """Inject the bus publisher used for ``bus.ai_review_*`` topics.

        The FastAPI lifespan calls this once the shared ZMQ PUB socket is
        available; tests pass a fake publisher (or ``None`` to clear). Decoupling
        socket ownership from the singleton keeps the service trivially testable
        without ZMQ.

        Args:
            publisher: Configured ``MessagePublisher`` or ``None`` to clear.
        """
        self._msg_publisher = publisher

    @property
    def msg_publisher(self) -> MessagePublisher | None:
        """Expose the injected publisher for tests + diagnostics.

        Read-only by design — production code paths route through
        :meth:`submit_decision` / reaper helpers that publish under their own
        post-commit invariants.

        Returns:
            The currently injected ``MessagePublisher`` or ``None``.
        """
        return self._msg_publisher

    def register_future(self, review_public_id: str, fut: asyncio.Future[object]) -> None:
        """Register a future that the strategy is awaiting on.

        Called by ``StrategyContext.create_ai_review`` BEFORE
        :meth:`create_review` publishes ``bus.ai_review_request``, so the
        listener side never sees a decision it can't deliver. Re-registering
        the same id replaces the previous handle: the most recent waiter wins,
        which matches the Plan D §8 retry-on-restart contract where a
        reconnecting strategy is the only legitimate re-registrant.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            fut: ``asyncio.Future`` the strategy is awaiting.
        """
        self._futures[review_public_id] = fut

    def unregister_future(self, review_public_id: str) -> None:
        """Drop a future from the registry.

        Idempotent — the await-loop calls this in its ``finally`` after either
        normal resolution or timeout, and the reaper / supersede paths call it
        again as a safety net.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row to forget.
        """
        self._futures.pop(review_public_id, None)

    def get_future(self, review_public_id: str) -> asyncio.Future[object] | None:
        """Look up a future without removing it.

        Returns ``None`` when the review id is unknown — typical in
        bus-listener code paths where decisions for already-resolved or
        cross-instance reviews land on this backend; the listener treats
        ``None`` as a no-op.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.

        Returns:
            The registered future or ``None`` if the id is unknown.
        """
        return self._futures.get(review_public_id)

    async def submit_decision(
        self,
        *,
        review_public_id: str,
        caller_user_public_id: str,
        decision: AiReviewDecisionEnum,
        rationale: str | None,
        repo: Repository,
        scope_grant_service: ScopeGrantService,
        now: datetime | None = None,
    ) -> AiReviewDecisionResult:
        """Submit an AI delegate's decision; Plan D §3.2 nine-step transaction.

        Resolves the caller's ``ai_delegates`` row, confirms the review
        exists and is within the caller's scope grant, branches on
        terminal-state shortcuts (idempotent retry vs peer-won),
        runs the Q9 step 3.5 inline timeout when the deadline has
        already elapsed, then performs the atomic CAS resolve + audit
        event append + Q10 counter decrement.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            caller_user_public_id: ``users.public_id`` of the AI delegate
                user submitting the decision; resolved to
                ``ai_delegates.public_id`` via the operational side-table.
            decision: ``APPROVE`` or ``REJECT``.
            rationale: Optional free-text (≤4096 chars; caller validates
                before reaching this method).
            repo: Repository handle. Passed in so the MCP tool keeps the
                caller's transactional context.
            scope_grant_service: Scope-check service. Passed in so the
                MCP tool's ``Depends`` wiring is the source of truth.
            now: Optional override for the transaction wall-clock; tests
                inject a fixed value so the late-decision shortcut and
                resolved_at columns are deterministic.

        Returns:
            :class:`AiReviewDecisionResult` envelope.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        delegate_row = await repo.get_ai_delegate_by_user_public_id(caller_user_public_id)
        if delegate_row is None:
            return AiReviewDecisionResult(
                error_code=ERROR_NOT_AUTHORIZED,
                message="Caller is not registered as an AI delegate.",
                status=None,
                resolution_mode=None,
                dispatch_version=None,
                details={"caller_user_public_id": caller_user_public_id},
            )
        delegate_public_id = delegate_row["public_id"]

        review = await repo.get_ai_review(review_public_id)
        if review is None:
            return AiReviewDecisionResult(
                error_code=ERROR_REVIEW_NOT_FOUND,
                message="No review with that id.",
                status=None,
                resolution_mode=None,
                dispatch_version=None,
                details={"review_public_id": review_public_id},
            )

        scope_ok = await scope_grant_service.has_grant_for_delegate(
            delegate_public_id=delegate_public_id,
            wallet_public_id=review["wallet_public_id"],
            instrument_public_id=review["instrument_public_id"],
            as_of=wall_clock,
        )
        if not scope_ok:
            return AiReviewDecisionResult(
                error_code=ERROR_NOT_AUTHORIZED,
                message="Delegate has no scope grant for this review.",
                status=AiReviewStatusEnum(review["status"]),
                resolution_mode=(
                    AiReviewResolutionModeEnum(review["resolution_mode"])
                    if review["resolution_mode"] is not None
                    else None
                ),
                dispatch_version=int(review["dispatch_version"]),
                details={
                    "wallet_public_id": review["wallet_public_id"],
                    "instrument_public_id": review["instrument_public_id"],
                },
            )

        if review["status"] in _TERMINAL_STATUSES:
            return self._terminal_state_envelope(
                review=review,
                delegate_public_id=delegate_public_id,
                decision=decision,
            )

        if review["deadline"] <= wall_clock:
            timeout_result = await repo.atomic_timeout_ai_review(
                review_public_id=review_public_id,
                now=wall_clock,
            )
            if timeout_result is not None:
                await repo.insert_ai_review_event(
                    {
                        "public_id": str(uuid7()),
                        "review_public_id": review_public_id,
                        "event_type": AiReviewEventTypeEnum.TIMEOUT_MARKED.value,
                        "actor_delegate_public_id": None,
                        "previous_status": timeout_result["previous_status"],
                        "new_status": AiReviewStatusEnum.TIMEOUT.value,
                        "payload": {"trigger": "submit_decision_late"},
                        "occurred_at": wall_clock,
                    }
                )
                await repo.decrement_delegate_active_count_for_review(
                    review_public_id=review_public_id,
                    selected_delegate_public_id=timeout_result["selected_delegate_public_id"],
                    now=wall_clock,
                )
            return AiReviewDecisionResult(
                error_code=ERROR_REVIEW_EXPIRED,
                message="Deadline elapsed before the decision arrived.",
                status=AiReviewStatusEnum.TIMEOUT,
                resolution_mode=AiReviewResolutionModeEnum.TIMEOUT_NO_RESPONSE,
                dispatch_version=int(review["dispatch_version"]),
                details={"deadline": review["deadline"].isoformat()},
            )

        new_status = (
            AiReviewStatusEnum.RESOLVED_APPROVED
            if decision == AiReviewDecisionEnum.APPROVE
            else AiReviewStatusEnum.RESOLVED_REJECTED
        )
        resolution_mode = self._resolution_mode_for(
            previous_status=review["status"],
            selected_delegate_public_id=review["selected_delegate_public_id"],
            responding_delegate_public_id=delegate_public_id,
        )
        atomic = await repo.atomic_resolve_ai_review(
            review_public_id=review_public_id,
            decision=decision.value,
            responding_delegate_public_id=delegate_public_id,
            rationale=rationale,
            resolution_mode=resolution_mode.value,
            new_status=new_status.value,
            now=wall_clock,
        )
        if atomic is None:
            fresh = await repo.get_ai_review(review_public_id)
            return self._terminal_state_envelope(
                review=fresh if fresh is not None else review,
                delegate_public_id=delegate_public_id,
                decision=decision,
            )

        await repo.insert_ai_review_event(
            {
                "public_id": str(uuid7()),
                "review_public_id": review_public_id,
                "event_type": AiReviewEventTypeEnum.DECISION_RECORDED.value,
                "actor_delegate_public_id": delegate_public_id,
                "previous_status": atomic["previous_status"],
                "new_status": new_status.value,
                "payload": {
                    "decision": decision.value,
                    "rationale": rationale,
                },
                "occurred_at": wall_clock,
            }
        )
        await repo.decrement_delegate_active_count_for_review(
            review_public_id=review_public_id,
            selected_delegate_public_id=atomic["selected_delegate_public_id"],
            now=wall_clock,
        )
        logger.info(
            "ai_review decision recorded",
            review_public_id=review_public_id,
            decision=decision.value,
            resolution_mode=resolution_mode.value,
        )
        return AiReviewDecisionResult(
            error_code=None,
            message="Decision recorded.",
            status=new_status,
            resolution_mode=resolution_mode,
            dispatch_version=int(atomic["dispatch_version"]),
            details={"previous_status": atomic["previous_status"]},
        )

    def _terminal_state_envelope(
        self,
        *,
        review: AiReviewRow,
        delegate_public_id: str,
        decision: AiReviewDecisionEnum,
    ) -> AiReviewDecisionResult:
        """Build the envelope returned when the row is already terminal.

        Disambiguates idempotent-retry (same delegate, same decision)
        from peer-resolved, so the caller can tell the difference between
        "your previous request landed" and "someone else got there first".
        """
        status_enum = AiReviewStatusEnum(review["status"])
        resolution_mode_value = review["resolution_mode"]
        resolution_mode = (
            AiReviewResolutionModeEnum(resolution_mode_value)
            if resolution_mode_value is not None
            else None
        )
        dispatch_version = int(review["dispatch_version"])
        recorded_decision = review["decision"]
        responding = review["responding_delegate_public_id"]
        same_caller = responding == delegate_public_id
        same_decision = recorded_decision is not None and recorded_decision == decision.value
        if same_caller and same_decision:
            return AiReviewDecisionResult(
                error_code=ERROR_DECISION_ALREADY_RECORDED,
                message="Decision already recorded; idempotent retry.",
                status=status_enum,
                resolution_mode=resolution_mode,
                dispatch_version=dispatch_version,
                details={"decision": decision.value},
            )
        return AiReviewDecisionResult(
            error_code=ERROR_PEER_RESOLVED,
            message="Review already resolved by another decision or the reaper.",
            status=status_enum,
            resolution_mode=resolution_mode,
            dispatch_version=dispatch_version,
            details={
                "responding_delegate_public_id": responding,
                "recorded_decision": recorded_decision,
            },
        )

    @staticmethod
    def _resolution_mode_for(
        *,
        previous_status: str,
        selected_delegate_public_id: str,
        responding_delegate_public_id: str,
    ) -> AiReviewResolutionModeEnum:
        """Plan A Q4 — pick the resolution_mode the row's transition implies.

        - ``pending`` + selected==responding -> PICK_ONE_PRIMARY (most common).
        - ``fanout_dispatched`` + selected==responding -> SECONDARY_AFTER_FANOUT
          (selected delegate came back online after fanout fired).
        - ``fanout_dispatched`` + selected!=responding -> FANOUT_FIRST_RESPONDER
          (different eligible delegate won the fanout race).
        """
        if previous_status == AiReviewStatusEnum.PENDING.value:
            return AiReviewResolutionModeEnum.PICK_ONE_PRIMARY
        if responding_delegate_public_id == selected_delegate_public_id:
            return AiReviewResolutionModeEnum.SECONDARY_AFTER_FANOUT
        return AiReviewResolutionModeEnum.FANOUT_FIRST_RESPONDER

    @classmethod
    def get_instance(cls) -> AiReviewService:
        """Return the singleton, creating it on first call.

        Returns:
            The process-wide ``AiReviewService`` singleton.
        """
        if cls._instance is None:
            cls._instance = AiReviewService()
        return cls._instance

    @classmethod
    def clear_instance(cls) -> None:
        """Reset the singleton — test-only seam."""
        cls._instance = None
        cls._initialized = False


def get_ai_review_service() -> AiReviewService:
    """Module-level accessor mirroring :func:`get_scope_grant_service`.

    Imported by FastAPI ``Depends`` wiring + by the MCP tool registration so
    the same singleton is observed across both transports.

    Returns:
        The process-wide ``AiReviewService`` singleton.
    """
    return AiReviewService.get_instance()
