"""AiReviewService — SOLE owner of the ``ai_reviews`` state machine.

Responsibilities (Plan A v1.4 + Plan D v1.1):

- Q9 — atomic state-machine transitions (pending -> resolved/timeout/superseded)
  with the writable-CTE counter primitive that keeps
  ``ai_delegates.active_reviews_count`` consistent under concurrent
  decisions.
- Q10 — admission control: pick a live delegate that has an open
  scope grant + at most one in-flight review.
- Q14 — emit success/error envelopes for the ``submit_ai_review_decision``
  MCP tool + the matching REST endpoint.
- Q17 — own the layered offline-detection: Layer 1 fast path triggered by
  ``WebSocketAuthManager`` ``bus.delegate_offline`` events; Layer 2 DB
  scanner that catches stragglers when no socket close was observed.
- Q18 — protocol-level dedup via ``dispatch_version`` so the bridge can
  ignore replays generated by the offline-scanner re-fanout.

This module exposes only the **skeleton** — singleton lifecycle, the
in-memory ``asyncio.Future`` registry that backs the strategy-side
``await ai_review`` primitive, and the bus-publisher injection seam.
The heavy state-machine methods land in subsequent commits per the
Plan D §3 layout (``create_review`` / ``submit_decision`` / reaper /
offline scanner).

The futures registry is the load-bearing in-process channel between the
WS-listener path (which receives ``bus.ai_review_decision`` and resolves
the future) and the strategy path (which awaits creation of the review).
Both sides MUST share the same singleton; otherwise the strategy would
hang on a future the listener can't see. Tests reset the singleton via
:meth:`clear_instance` between cases to avoid cross-test future leakage.
"""

import asyncio

from snapper.messaging.infrastructure.publisher import MessagePublisher


class NoLiveDelegateError(Exception):
    """No eligible AI delegate is live within the heartbeat window.

    Raised by :meth:`AiReviewService.create_review` when admission control finds
    no eligible AI delegate for the requested scope (operator + wallet +
    instrument). The strategy turns this into a Plan A Q11 ``no_live_delegate``
    outcome and decides whether to abort, retry, or fall through to the human
    path according to its own policy.
    """


class DelegateBusyError(Exception):
    """Every eligible delegate already has an in-flight review.

    Raised by :meth:`AiReviewService.create_review` when every eligible delegate
    has ``active_reviews_count > 0``. Plan A Q10 caps each delegate at one
    in-flight review; busy-everywhere is a transient signal the strategy can
    retry against, distinct from :class:`NoLiveDelegateError` (which means
    there is nobody to wait for).
    """


class AiReviewService:
    """Singleton owner of the ``ai_reviews`` state machine + future registry."""

    _instance: AiReviewService | None = None
    _initialized: bool = False

    def __new__(cls) -> AiReviewService:
        """Create or return the singleton instance."""
        if cls._instance is None:
            instance = super().__new__(cls)
            cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        """Initialise publisher slot + futures registry on first construction."""
        if self._initialized:
            return
        self._initialized = True
        self._msg_publisher: MessagePublisher | None = None
        self._futures: dict[str, asyncio.Future[object]] = {}

    def set_msg_publisher(self, publisher: MessagePublisher | None) -> None:
        """Inject the bus publisher used for ``bus.ai_review_*`` topics.

        The FastAPI lifespan calls this once the shared ZMQ PUB socket is
        available; tests pass a fake publisher (or ``None`` to clear). Decoupling
        socket ownership from the singleton keeps the service trivially testable
        without ZMQ.

        Args:
            publisher: Configured ``MessagePublisher`` or ``None`` to clear.
        """
        self._msg_publisher = publisher

    @property
    def msg_publisher(self) -> MessagePublisher | None:
        """Expose the injected publisher for tests + diagnostics.

        Read-only by design — production code paths route through
        :meth:`submit_decision` / reaper helpers that publish under their own
        post-commit invariants.

        Returns:
            The currently injected ``MessagePublisher`` or ``None``.
        """
        return self._msg_publisher

    def register_future(self, review_public_id: str, fut: asyncio.Future[object]) -> None:
        """Register a future that the strategy is awaiting on.

        Called by ``StrategyContext.create_ai_review`` BEFORE
        :meth:`create_review` publishes ``bus.ai_review_request``, so the
        listener side never sees a decision it can't deliver. Re-registering
        the same id replaces the previous handle: the most recent waiter wins,
        which matches the Plan D §8 retry-on-restart contract where a
        reconnecting strategy is the only legitimate re-registrant.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            fut: ``asyncio.Future`` the strategy is awaiting.
        """
        self._futures[review_public_id] = fut

    def unregister_future(self, review_public_id: str) -> None:
        """Drop a future from the registry.

        Idempotent — the await-loop calls this in its ``finally`` after either
        normal resolution or timeout, and the reaper / supersede paths call it
        again as a safety net.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row to forget.
        """
        self._futures.pop(review_public_id, None)

    def get_future(self, review_public_id: str) -> asyncio.Future[object] | None:
        """Look up a future without removing it.

        Returns ``None`` when the review id is unknown — typical in
        bus-listener code paths where decisions for already-resolved or
        cross-instance reviews land on this backend; the listener treats
        ``None`` as a no-op.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.

        Returns:
            The registered future or ``None`` if the id is unknown.
        """
        return self._futures.get(review_public_id)

    @classmethod
    def get_instance(cls) -> AiReviewService:
        """Return the singleton, creating it on first call.

        Returns:
            The process-wide ``AiReviewService`` singleton.
        """
        if cls._instance is None:
            cls._instance = AiReviewService()
        return cls._instance

    @classmethod
    def clear_instance(cls) -> None:
        """Reset the singleton — test-only seam."""
        cls._instance = None
        cls._initialized = False


def get_ai_review_service() -> AiReviewService:
    """Module-level accessor mirroring :func:`get_scope_grant_service`.

    Imported by FastAPI ``Depends`` wiring + by the MCP tool registration so
    the same singleton is observed across both transports.

    Returns:
        The process-wide ``AiReviewService`` singleton.
    """
    return AiReviewService.get_instance()
