"""AiReviewService — SOLE owner of the ``ai_reviews`` state machine.

Responsibilities (Plan A v1.4 + Plan D v1.1):

- Q9 — atomic state-machine transitions (pending -> resolved/timeout/superseded)
  with the writable-CTE counter primitive that keeps
  ``ai_delegates.active_reviews_count`` consistent under concurrent
  decisions.
- Q10 — admission control: pick a live delegate that has an open
  scope grant + at most one in-flight review.
- Q14 — emit success/error envelopes for the ``submit_ai_review_decision``
  MCP tool + the matching REST endpoint.
- Q17 — own the layered offline-detection: Layer 1 fast path triggered by
  ``WebSocketAuthManager`` ``bus.delegate_offline`` events; Layer 2 DB
  scanner that catches stragglers when no socket close was observed.
- Q18 — protocol-level dedup via ``dispatch_version`` so the bridge can
  ignore replays generated by the offline-scanner re-fanout.

This module exposes only the **skeleton** — singleton lifecycle, the
in-memory ``asyncio.Future`` registry that backs the strategy-side
``await ai_review`` primitive, and the bus-publisher injection seam.
The heavy state-machine methods land in subsequent commits per the
Plan D §3 layout (``create_review`` / ``submit_decision`` / reaper /
offline scanner).

The futures registry is the load-bearing in-process channel between the
WS-listener path (which receives ``bus.ai_review_decision`` and resolves
the future) and the strategy path (which awaits creation of the review).
Both sides MUST share the same singleton; otherwise the strategy would
hang on a future the listener can't see. Tests reset the singleton via
:meth:`clear_instance` between cases to avoid cross-test future leakage.
"""

import asyncio
import contextlib
import hashlib
import json
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC
from datetime import datetime
from datetime import timedelta
from uuid import uuid7

import zmq
import zmq.asyncio
from loguru import logger

from snapper.auth.scope_grant_service import ScopeGrantService
from snapper.core.json_types import JsonObject
from snapper.core.json_types import JsonValue
from snapper.core.types import AiReviewDecisionEnum
from snapper.core.types import AiReviewEventTypeEnum
from snapper.core.types import AiReviewResolutionModeEnum
from snapper.core.types import AiReviewStatusEnum
from snapper.data.repository import Repository
from snapper.data.repository_types import AiReviewEventInsertRow
from snapper.data.repository_types import AiReviewInsertRow
from snapper.data.repository_types import AiReviewRow
from snapper.data.repository_types import PendingReviewSummary
from snapper.messaging.infrastructure.publisher import MessagePublisher
from snapper.messaging.infrastructure.validated_socket import HWM_AUDIT
from snapper.messaging.infrastructure.validated_socket import ValidatedSubscriber
from snapper.messaging.infrastructure.validated_socket import apply_hwm
from snapper.messaging.schemas.data import AiReviewCapsViolationFrameData
from snapper.messaging.schemas.data import CapsViolationAfterAiApproveData
from snapper.messaging.schemas.data import DelegateOfflineData

_BUS_DELEGATE_OFFLINE_TOPIC = "bus.delegate_offline"
"""Internal Q17 layer-1 fast-path topic published by
``WebSocketAuthManager._publish_delegate_offline`` (sole publisher).
Subscribed by :meth:`AiReviewService.handle_delegate_offline_bus_message`
which CAS-fans-out matching pending reviews."""

_BUS_CAPS_VIOLATION_TOPIC = "bus.caps_violation_after_ai_approve"
"""Internal Plan D §3.6 topic published by ``TradingCapsEnforcer``
(deferred publisher-side wiring chunk) when an AI-approved trade
later fails the caps gate. Subscribed by
:meth:`AiReviewService.handle_caps_violation_bus_message` which
re-fanouts to the external ``ai_reviews.{user}.{strategy}.caps_violation``
WS topic."""

_AI_REVIEW_LISTEN_RECV_BACKOFF_S = 0.1
"""Sleep between recv retries when the ZMQ subscriber raises a
non-cancellation error. Mirrors the admin listener's
``_ADMIN_LISTEN_RECV_BACKOFF_S`` so a transient broker hiccup never
bursts the listener loop into a busy retry tight-loop."""

DEFAULT_HEARTBEAT_WINDOW_SECONDS = 15
"""Plan A Q10 v1.3 + Q17 cross-plan lock — liveness threshold for admission control.

Plan C client-side heartbeat MUST send at ``heartbeat_interval ≤ window/2``
(default 7s) so a healthy delegate never appears offline mid-cycle.
"""

DEFAULT_FANOUT_AFTER_SECONDS = 30
"""Plan A Q4 v1.4 — when fanout fires if the selected delegate stays silent.

Cross-plan invariant: fanout_after MUST be > heartbeat_window so the offline
scanner has at least one window's worth of evidence the delegate is gone
before re-dispatch fires.
"""

MAX_SIGNAL_ENVELOPE_BYTES = 16 * 1024
"""Plan A v1.4 §3 + risk register — server-side cap on the canonical JSON size.

Plan A v1.4 line 516: ``Max signal_envelope payload: 16KB (matches §3
server-side limit). Bridge enforces defensively after JSON parse``. The
truncation guard belongs in :meth:`AiReviewService.create_review` per the
risk-register entry at plan line 1444. Oversize envelopes raise
:class:`SignalEnvelopeTooLargeError` BEFORE INSERT so the caller can
surface a structured failure rather than mutating the bitemporal store.
"""

ERROR_REVIEW_NOT_FOUND = "review_not_found"
"""Plan A Q14 envelope error code — caller passed an unknown review_id."""

ERROR_NOT_AUTHORIZED = "not_authorized"
"""Plan A Q14 — caller's delegate has no scope grant for the review's wallet+instrument."""

ERROR_PEER_RESOLVED = "review_already_resolved_by_peer"
"""Plan A Q14 — terminal status reached by another decision (or reaper) before us."""

ERROR_REVIEW_EXPIRED = "review_id_expired"
"""Plan A Q14 — Q9 step 3.5 inline timeout: deadline elapsed before the decision arrived."""

ERROR_DECISION_ALREADY_RECORDED = "decision_already_recorded"
"""Plan A Q14 — idempotent retry: same delegate, same decision, already-resolved row.

Returned with ``error_code`` set so the client surfaces the duplicate as success
(success=True per the Plan A Q14 envelope), while still flagging the no-op for
audit and metrics dashboards.
"""


@dataclass(slots=True)
class AiReviewDecisionResult:
    """Envelope returned by :meth:`AiReviewService.submit_decision`.

    Plan A Q14 contract — ``error_code`` is the load-bearing discriminator:

    - ``None`` -> first valid decision; the row transitioned and the
      decision was recorded for the first time.
    - :data:`ERROR_DECISION_ALREADY_RECORDED` -> idempotent retry; the
      caller is the responding delegate and the decision matches what we
      already have. Treated as success at the MCP layer.
    - Any other code -> hard error; the MCP layer flips ``success=False``.

    ``status`` and ``resolution_mode`` reflect the row's current state
    AFTER any transition this call performed (or simply observed). For
    ``ERROR_REVIEW_NOT_FOUND`` they are ``None`` since there is no row to
    report on.
    """

    error_code: str | None
    message: str
    status: AiReviewStatusEnum | None
    resolution_mode: AiReviewResolutionModeEnum | None
    dispatch_version: int | None
    details: dict[str, JsonValue]


_TERMINAL_STATUSES = frozenset(
    {
        AiReviewStatusEnum.RESOLVED_APPROVED.value,
        AiReviewStatusEnum.RESOLVED_REJECTED.value,
        AiReviewStatusEnum.TIMEOUT.value,
        AiReviewStatusEnum.SUPERSEDED.value,
    }
)
"""Plan A Q9 — terminal statuses that block further transitions."""


class NoLiveDelegateError(Exception):
    """No eligible AI delegate is live within the heartbeat window.

    Raised by :meth:`AiReviewService.create_review` when admission control finds
    no eligible AI delegate for the requested scope (operator + wallet +
    instrument). The strategy turns this into a Plan A Q11 ``no_live_delegate``
    outcome and decides whether to abort, retry, or fall through to the human
    path according to its own policy.
    """


class DelegateBusyError(Exception):
    """Every eligible delegate already has an in-flight review.

    Raised by :meth:`AiReviewService.create_review` when every eligible delegate
    has ``active_reviews_count > 0``. Plan A Q10 caps each delegate at one
    in-flight review; busy-everywhere is a transient signal the strategy can
    retry against, distinct from :class:`NoLiveDelegateError` (which means
    there is nobody to wait for).
    """


class SignalEnvelopeTooLargeError(Exception):
    """Caller-supplied ``signal_envelope`` exceeds the Plan A 16KB cap.

    Raised by :meth:`AiReviewService.create_review` BEFORE any DB write
    when the canonical-JSON serialisation of the envelope exceeds
    :data:`MAX_SIGNAL_ENVELOPE_BYTES`. Plan A v1.4 risk-register entry
    pins the truncation guard to the service layer (line 1444) so the
    bridge + strategy boundary inputs are double-defended without coupling
    storage code to caller-side trust.
    """


@dataclass(slots=True, frozen=True)
class AiReviewCreateRequest:
    """Strategy-side payload for :meth:`AiReviewService.create_review`.

    Bundles the scope identifiers (user/operator/wallet/instrument/strategy)
    with the data fields (signal envelope, instrument metadata, deadline,
    bus origin) so the service signature stays short. The strategy
    primitive (Plan D §8 ``StrategyContext.create_ai_review``) builds this
    request from the live ``SignalData`` envelope and the resolved scope
    of the strategy's run-time context.

    Attributes:
        user_public_id: Owner of the strategy issuing the CONSULT
            (Q9 step 1 v1.4 fix — DISTINCT from delegate users).
        operator_public_id: Operator scope under which the strategy
            is consulting; admission control filters delegates to this
            operator's members.
        wallet_public_id: Wallet the resulting trade would settle on;
            used by the scope-grant pre-check.
        instrument_public_id: Instrument the strategy is signalling on.
        strategy_public_id: Origin strategy public_id stored on the
            review row for operator-dashboard filtering.
        signal_envelope: Strategy-side signal payload persisted as JSON.
        instrument_metadata: Instrument snapshot persisted as JSON for
            the delegate's offline reasoning (``requires_ai_review``,
            liquidity hints, ...).
        deadline_seconds: How long the strategy will wait for a decision
            before falling through. Plan A Q4 typical range 5-30s.
        session_id: Strategy's bus session UUID at creation.
        sequence_id: Strategy's monotonic sequence at creation.
    """

    user_public_id: str
    operator_public_id: str
    wallet_public_id: str
    instrument_public_id: str
    strategy_public_id: str
    signal_envelope: JsonObject
    instrument_metadata: JsonObject
    deadline_seconds: int
    session_id: str
    sequence_id: int


@dataclass(slots=True, frozen=True)
class AiReviewAdmissionPolicy:
    """Liveness + fanout windows for admission control.

    Cross-plan invariant: ``fanout_after_seconds`` MUST exceed
    ``heartbeat_window_seconds`` so the offline scanner has at least one
    window's worth of evidence the delegate is gone before re-dispatch
    fires. The invariant is enforced at construction via
    :meth:`__post_init__`; oversights at call sites surface as
    ``ValueError`` rather than as silently misordered timeouts. Tests
    override these for fast-clock liveness scenarios while keeping the
    invariant; the defaults match the Plan A v1.4 cross-plan locks.
    """

    heartbeat_window_seconds: int = DEFAULT_HEARTBEAT_WINDOW_SECONDS
    fanout_after_seconds: int = DEFAULT_FANOUT_AFTER_SECONDS

    def __post_init__(self) -> None:
        """Enforce ``fanout_after_seconds > heartbeat_window_seconds`` (Q17 lock)."""
        if self.heartbeat_window_seconds <= 0:
            raise ValueError(
                f"heartbeat_window_seconds must be positive; "
                f"got {self.heartbeat_window_seconds}."
            )
        if self.fanout_after_seconds <= self.heartbeat_window_seconds:
            raise ValueError(
                f"fanout_after_seconds ({self.fanout_after_seconds}) must be "
                f"strictly greater than heartbeat_window_seconds "
                f"({self.heartbeat_window_seconds}) per Plan A Q17 cross-plan lock."
            )


_DEFAULT_AI_REVIEW_ADMISSION_POLICY = AiReviewAdmissionPolicy()


@dataclass(slots=True, frozen=True)
class AiReviewDecisionOutcome:
    """Terminal-state projection for the strategy-side await primitive.

    Returned by :func:`create_ai_review_and_await` (Plan D §8) once a
    CONSULT review has reached a terminal status. Strategies branch
    on :attr:`status`:

    - ``RESOLVED_APPROVED`` — proceed with the trade.
    - ``RESOLVED_REJECTED`` — VETO per Q12; abort, no trade.
    - ``TIMEOUT`` — deadline elapsed without a decision; strategy
      falls through to the original non-AI decision (Q3).
    - ``SUPERSEDED`` — strategy abandoned the review (e.g. signal
      expired before deadline).

    Attributes:
        review_public_id: UUID7 of the resolved ``ai_reviews`` row.
        status: Terminal :class:`AiReviewStatusEnum`.
        resolution_mode: How resolution happened (or ``None`` for
          mid-state reads, but at terminal state it is always set).
        decision: ``approve`` / ``reject`` for resolved rows; ``None``
          for timeout / superseded.
        rationale: Free-text rationale recorded by the deciding
          delegate; ``None`` for non-decision terminal states.
        dispatch_version: Plan A Q18 version counter at terminal
          time (used by bridges to dedup re-fanouts).
        responding_delegate_public_id: Delegate that submitted the
          decision; ``None`` for timeout / superseded.
    """

    review_public_id: str
    status: AiReviewStatusEnum
    resolution_mode: AiReviewResolutionModeEnum | None
    decision: AiReviewDecisionEnum | None
    rationale: str | None
    dispatch_version: int
    responding_delegate_public_id: str | None


@dataclass(slots=True)
class AiReviewCreated:
    """Result envelope for a successful :meth:`AiReviewService.create_review`.

    The strategy primitive (Plan D §8 ``StrategyContext.create_ai_review``)
    forwards ``review_public_id`` to its await loop and registers a future
    keyed on it. ``selected_delegate_public_id`` lets the caller log which
    delegate received the dispatch — useful for operator dashboards and for
    correlating the eventual ``ai_review_decision`` bus message back to the
    candidate that won admission.

    Attributes:
        review_public_id: UUID7 of the freshly inserted ``ai_reviews`` row.
        selected_delegate_public_id: ``ai_delegates.public_id`` whose
            ``active_reviews_count`` was incremented as part of the
            atomic claim.
    """

    review_public_id: str
    selected_delegate_public_id: str


def _serialize_signal_envelope_canonical(envelope: JsonObject) -> bytes:
    """Canonical JSON bytes for hashing + size enforcement.

    ``allow_nan=False`` rejects ``NaN`` / ``Infinity`` at this point: those
    values are not valid JSON and round-trip differently between SQLite's
    ``JSON`` text storage and PostgreSQL ``JSONB``, so a downstream
    consumer reconstructing the envelope from the column would see a
    different hash than the one stored on the audit-event payload.
    ``sort_keys=True`` + tight separators give a stable canonical form so
    two equivalent envelopes hash identically regardless of build order.
    """
    return json.dumps(
        envelope,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _signal_envelope_hash(envelope: JsonObject) -> str:
    """Canonical SHA-256 hex digest of the signal envelope.

    Stored in the ``ai_reviews.signal_snapshot_hash`` column AND on the
    ``ai_review_events.created`` payload so a consumer reconstructing the
    audit trail can confirm the envelope it sees matches the one the
    review was created from.
    """
    return hashlib.sha256(_serialize_signal_envelope_canonical(envelope)).hexdigest()


class AiReviewService:
    """Singleton owner of the ``ai_reviews`` state machine + future registry."""

    _instance: AiReviewService | None = None
    _initialized: bool = False

    def __new__(cls) -> AiReviewService:
        """Create or return the singleton instance."""
        if cls._instance is None:
            instance = super().__new__(cls)
            cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        """Initialise publisher slot + futures registry on first construction."""
        if self._initialized:
            return
        self._initialized = True
        self._msg_publisher: MessagePublisher | None = None
        self._futures: dict[str, asyncio.Future[object]] = {}
        self._repository_factory: Callable[[], Repository] | None = None
        self._bus_subscriber: ValidatedSubscriber | None = None
        self._bus_zmq_context: zmq.asyncio.Context | None = None
        self._bus_listen_task: asyncio.Task[None] | None = None
        self._bus_running: bool = False
        self._bus_listener_lock: asyncio.Lock = asyncio.Lock()

    def set_msg_publisher(self, publisher: MessagePublisher | None) -> None:
        """Inject the bus publisher used for ``bus.ai_review_*`` topics.

        The FastAPI lifespan calls this once the shared ZMQ PUB socket is
        available; tests pass a fake publisher (or ``None`` to clear). Decoupling
        socket ownership from the singleton keeps the service trivially testable
        without ZMQ.

        Args:
            publisher: Configured ``MessagePublisher`` or ``None`` to clear.
        """
        self._msg_publisher = publisher

    @property
    def msg_publisher(self) -> MessagePublisher | None:
        """Expose the injected publisher for tests + diagnostics.

        Read-only by design — production code paths route through
        :meth:`submit_decision` / reaper helpers that publish under their own
        post-commit invariants.

        Returns:
            The currently injected ``MessagePublisher`` or ``None``.
        """
        return self._msg_publisher

    def register_future(self, review_public_id: str, fut: asyncio.Future[object]) -> None:
        """Register a future that the strategy is awaiting on.

        Called by ``StrategyContext.create_ai_review`` BEFORE
        :meth:`create_review` publishes ``bus.ai_review_request``, so the
        listener side never sees a decision it can't deliver. Re-registering
        the same id replaces the previous handle: the most recent waiter wins,
        which matches the Plan D §8 retry-on-restart contract where a
        reconnecting strategy is the only legitimate re-registrant.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            fut: ``asyncio.Future`` the strategy is awaiting.
        """
        self._futures[review_public_id] = fut

    def unregister_future(self, review_public_id: str) -> None:
        """Drop a future from the registry.

        Idempotent — the await-loop calls this in its ``finally`` after either
        normal resolution or timeout, and the reaper / supersede paths call it
        again as a safety net.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row to forget.
        """
        self._futures.pop(review_public_id, None)

    def get_future(self, review_public_id: str) -> asyncio.Future[object] | None:
        """Look up a future without removing it.

        Returns ``None`` when the review id is unknown — typical in
        bus-listener code paths where decisions for already-resolved or
        cross-instance reviews land on this backend; the listener treats
        ``None`` as a no-op.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.

        Returns:
            The registered future or ``None`` if the id is unknown.
        """
        return self._futures.get(review_public_id)

    async def create_review(
        self,
        request: AiReviewCreateRequest,
        *,
        repo: Repository,
        now: datetime | None = None,
        policy: AiReviewAdmissionPolicy = _DEFAULT_AI_REVIEW_ADMISSION_POLICY,
    ) -> AiReviewCreated:
        """Plan A v1.4 Q10 admission control + Plan D §3.1 INSERT.

        Composes :meth:`Repository.list_eligible_delegates_for_ai_review`
        (operator + scope + liveness filter) with
        :meth:`Repository.claim_and_insert_ai_review` (atomic CAS claim
        on ``ai_delegates.active_reviews_count`` + INSERT of the review
        row + ``created`` audit event in one transaction). The
        ``signal_snapshot_hash`` is computed from ``request.signal_envelope``
        so the audit trail can verify the envelope a downstream consumer
        sees matches the one admission control resolved on.

        Bus publish of ``bus.ai_review_request`` is intentionally NOT
        performed here — the publisher slot exists on the singleton but
        the listener side lands in the next chunk (Plan D Phase 1
        item 2 ``supersede_review`` + reaper + scanner). Until the
        listener exists the publish would be a noisy no-op against the
        empty bus topology.

        Args:
            request: Strategy-side payload bundling scope identifiers
                + signal envelope + instrument metadata + deadline +
                bus origin (session_id / sequence_id).
            repo: Repository handle (single-transaction caller context).
            now: Optional override for the wall-clock; tests inject a
                fixed value so the deadline + audit timestamps are
                deterministic.
            policy: Liveness + fanout windows. Defaults to the Plan A
                v1.4 cross-plan locks (15s heartbeat / 30s fanout);
                tests override for fast-clock scenarios.

        Returns:
            :class:`AiReviewCreated` with the freshly inserted
            ``review_public_id`` and the
            ``selected_delegate_public_id`` admission control
            picked.

        Raises:
            NoLiveDelegateError: No eligible AI delegate is live within
                the heartbeat window for the operator + wallet +
                instrument scope.
            DelegateBusyError: Eligible delegates exist but every one
                already has an in-flight review (Q10 caps each at one).
            SignalEnvelopeTooLargeError: ``request.signal_envelope``
                serialises to more than :data:`MAX_SIGNAL_ENVELOPE_BYTES`
                of canonical JSON (Plan A v1.4 risk-register guard).
            ValueError: ``request.signal_envelope`` contains
                non-finite floats (``NaN`` / ``Infinity``) — not valid
                JSON, would corrupt audit-trail reconstruction.
        """
        canonical_envelope = _serialize_signal_envelope_canonical(request.signal_envelope)
        if len(canonical_envelope) > MAX_SIGNAL_ENVELOPE_BYTES:
            raise SignalEnvelopeTooLargeError(
                f"signal_envelope canonical size {len(canonical_envelope)} bytes "
                f"exceeds {MAX_SIGNAL_ENVELOPE_BYTES}-byte cap (Plan A v1.4)."
            )
        wall_clock = now if now is not None else datetime.now(UTC)
        candidates = await repo.list_eligible_delegates_for_ai_review(
            operator_public_id=request.operator_public_id,
            wallet_public_id=request.wallet_public_id,
            instrument_public_id=request.instrument_public_id,
            heartbeat_window_seconds=policy.heartbeat_window_seconds,
            as_of=wall_clock,
        )
        if not candidates:
            raise NoLiveDelegateError(
                f"No live AI delegate eligible for "
                f"operator={request.operator_public_id} "
                f"wallet={request.wallet_public_id} "
                f"instrument={request.instrument_public_id} "
                f"within {policy.heartbeat_window_seconds}s heartbeat window."
            )

        review_public_id = str(uuid7())
        event_public_id = str(uuid7())
        envelope_hash = hashlib.sha256(canonical_envelope).hexdigest()
        deadline = wall_clock + timedelta(seconds=request.deadline_seconds)
        fanout_after = wall_clock + timedelta(seconds=policy.fanout_after_seconds)
        candidate_ids = [candidate["public_id"] for candidate in candidates]

        review_data: AiReviewInsertRow = {
            "public_id": review_public_id,
            "session_id": request.session_id,
            "sequence_id": request.sequence_id,
            "user_public_id": request.user_public_id,
            "operator_public_id": request.operator_public_id,
            "wallet_public_id": request.wallet_public_id,
            "instrument_public_id": request.instrument_public_id,
            "strategy_public_id": request.strategy_public_id,
            "selected_delegate_public_id": candidate_ids[0],
            "status": AiReviewStatusEnum.PENDING.value,
            "signal_envelope": request.signal_envelope,
            "signal_snapshot_hash": envelope_hash,
            "instrument_metadata": request.instrument_metadata,
            "deadline": deadline,
            "fanout_after": fanout_after,
            "dispatch_version": 0,
            "created_at": wall_clock,
            "updated_at": wall_clock,
        }
        event_data: AiReviewEventInsertRow = {
            "public_id": event_public_id,
            "review_public_id": review_public_id,
            "event_type": AiReviewEventTypeEnum.CREATED.value,
            "actor_delegate_public_id": None,
            "previous_status": None,
            "new_status": AiReviewStatusEnum.PENDING.value,
            "payload": {
                "signal_snapshot_hash": envelope_hash,
                "dispatch_version": 0,
            },
            "occurred_at": wall_clock,
        }

        selected = await repo.claim_and_insert_ai_review(
            candidate_delegate_public_ids=candidate_ids,
            review_data=review_data,
            event_data=event_data,
            now=wall_clock,
        )
        if selected is None:
            raise DelegateBusyError(
                f"All {len(candidate_ids)} eligible delegate(s) busy for "
                f"operator={request.operator_public_id} "
                f"wallet={request.wallet_public_id} "
                f"instrument={request.instrument_public_id}."
            )
        logger.info(
            "ai_review created",
            review_public_id=review_public_id,
            selected_delegate_public_id=selected,
            candidate_count=len(candidate_ids),
        )
        return AiReviewCreated(
            review_public_id=review_public_id,
            selected_delegate_public_id=selected,
        )

    async def submit_decision(
        self,
        *,
        review_public_id: str,
        caller_user_public_id: str,
        decision: AiReviewDecisionEnum,
        rationale: str | None,
        repo: Repository,
        scope_grant_service: ScopeGrantService,
        now: datetime | None = None,
    ) -> AiReviewDecisionResult:
        """Submit an AI delegate's decision; Plan D §3.2 nine-step transaction.

        Resolves the caller's ``ai_delegates`` row, confirms the review
        exists and is within the caller's scope grant, branches on
        terminal-state shortcuts (idempotent retry vs peer-won),
        runs the Q9 step 3.5 inline timeout when the deadline has
        already elapsed, then performs the atomic CAS resolve + audit
        event append + Q10 counter decrement.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            caller_user_public_id: ``users.public_id`` of the AI delegate
                user submitting the decision; resolved to
                ``ai_delegates.public_id`` via the operational side-table.
            decision: ``APPROVE`` or ``REJECT``.
            rationale: Optional free-text (≤4096 chars; caller validates
                before reaching this method).
            repo: Repository handle. Passed in so the MCP tool keeps the
                caller's transactional context.
            scope_grant_service: Scope-check service. Passed in so the
                MCP tool's ``Depends`` wiring is the source of truth.
            now: Optional override for the transaction wall-clock; tests
                inject a fixed value so the late-decision shortcut and
                resolved_at columns are deterministic.

        Returns:
            :class:`AiReviewDecisionResult` envelope.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        delegate_row = await repo.get_ai_delegate_by_user_public_id(caller_user_public_id)
        if delegate_row is None:
            return AiReviewDecisionResult(
                error_code=ERROR_NOT_AUTHORIZED,
                message="Caller is not registered as an AI delegate.",
                status=None,
                resolution_mode=None,
                dispatch_version=None,
                details={"caller_user_public_id": caller_user_public_id},
            )
        delegate_public_id = delegate_row["public_id"]

        review = await repo.get_ai_review(review_public_id)
        if review is None:
            return AiReviewDecisionResult(
                error_code=ERROR_REVIEW_NOT_FOUND,
                message="No review with that id.",
                status=None,
                resolution_mode=None,
                dispatch_version=None,
                details={"review_public_id": review_public_id},
            )

        scope_ok = await scope_grant_service.has_grant_for_delegate(
            delegate_public_id=delegate_public_id,
            wallet_public_id=review["wallet_public_id"],
            instrument_public_id=review["instrument_public_id"],
            as_of=wall_clock,
        )
        if not scope_ok:
            return AiReviewDecisionResult(
                error_code=ERROR_NOT_AUTHORIZED,
                message="Delegate has no scope grant for this review.",
                status=AiReviewStatusEnum(review["status"]),
                resolution_mode=(
                    AiReviewResolutionModeEnum(review["resolution_mode"])
                    if review["resolution_mode"] is not None
                    else None
                ),
                dispatch_version=int(review["dispatch_version"]),
                details={
                    "wallet_public_id": review["wallet_public_id"],
                    "instrument_public_id": review["instrument_public_id"],
                },
            )

        if review["status"] in _TERMINAL_STATUSES:
            return self._terminal_state_envelope(
                review=review,
                delegate_public_id=delegate_public_id,
                decision=decision,
            )

        if review["deadline"] <= wall_clock:
            timeout_result = await repo.atomic_timeout_ai_review(
                review_public_id=review_public_id,
                now=wall_clock,
            )
            if timeout_result is not None:
                await repo.insert_ai_review_event(
                    {
                        "public_id": str(uuid7()),
                        "review_public_id": review_public_id,
                        "event_type": AiReviewEventTypeEnum.TIMEOUT_MARKED.value,
                        "actor_delegate_public_id": None,
                        "previous_status": timeout_result["previous_status"],
                        "new_status": AiReviewStatusEnum.TIMEOUT.value,
                        "payload": {"trigger": "submit_decision_late"},
                        "occurred_at": wall_clock,
                    }
                )
                await repo.decrement_delegate_active_count_for_review(
                    review_public_id=review_public_id,
                    selected_delegate_public_id=timeout_result["selected_delegate_public_id"],
                    now=wall_clock,
                )
            return AiReviewDecisionResult(
                error_code=ERROR_REVIEW_EXPIRED,
                message="Deadline elapsed before the decision arrived.",
                status=AiReviewStatusEnum.TIMEOUT,
                resolution_mode=AiReviewResolutionModeEnum.TIMEOUT_NO_RESPONSE,
                dispatch_version=int(review["dispatch_version"]),
                details={"deadline": review["deadline"].isoformat()},
            )

        new_status = (
            AiReviewStatusEnum.RESOLVED_APPROVED
            if decision == AiReviewDecisionEnum.APPROVE
            else AiReviewStatusEnum.RESOLVED_REJECTED
        )
        resolution_mode = self._resolution_mode_for(
            previous_status=review["status"],
            selected_delegate_public_id=review["selected_delegate_public_id"],
            responding_delegate_public_id=delegate_public_id,
        )
        atomic = await repo.atomic_resolve_ai_review(
            review_public_id=review_public_id,
            decision=decision.value,
            responding_delegate_public_id=delegate_public_id,
            rationale=rationale,
            resolution_mode=resolution_mode.value,
            new_status=new_status.value,
            now=wall_clock,
        )
        if atomic is None:
            fresh = await repo.get_ai_review(review_public_id)
            return self._terminal_state_envelope(
                review=fresh if fresh is not None else review,
                delegate_public_id=delegate_public_id,
                decision=decision,
            )

        await repo.insert_ai_review_event(
            {
                "public_id": str(uuid7()),
                "review_public_id": review_public_id,
                "event_type": AiReviewEventTypeEnum.DECISION_RECORDED.value,
                "actor_delegate_public_id": delegate_public_id,
                "previous_status": atomic["previous_status"],
                "new_status": new_status.value,
                "payload": {
                    "decision": decision.value,
                    "rationale": rationale,
                },
                "occurred_at": wall_clock,
            }
        )
        await repo.decrement_delegate_active_count_for_review(
            review_public_id=review_public_id,
            selected_delegate_public_id=atomic["selected_delegate_public_id"],
            now=wall_clock,
        )
        logger.info(
            "ai_review decision recorded",
            review_public_id=review_public_id,
            decision=decision.value,
            resolution_mode=resolution_mode.value,
        )
        return AiReviewDecisionResult(
            error_code=None,
            message="Decision recorded.",
            status=new_status,
            resolution_mode=resolution_mode,
            dispatch_version=int(atomic["dispatch_version"]),
            details={"previous_status": atomic["previous_status"]},
        )

    def _terminal_state_envelope(
        self,
        *,
        review: AiReviewRow,
        delegate_public_id: str,
        decision: AiReviewDecisionEnum,
    ) -> AiReviewDecisionResult:
        """Build the envelope returned when the row is already terminal.

        Disambiguates idempotent-retry (same delegate, same decision)
        from peer-resolved, so the caller can tell the difference between
        "your previous request landed" and "someone else got there first".
        """
        status_enum = AiReviewStatusEnum(review["status"])
        resolution_mode_value = review["resolution_mode"]
        resolution_mode = (
            AiReviewResolutionModeEnum(resolution_mode_value)
            if resolution_mode_value is not None
            else None
        )
        dispatch_version = int(review["dispatch_version"])
        recorded_decision = review["decision"]
        responding = review["responding_delegate_public_id"]
        same_caller = responding == delegate_public_id
        same_decision = recorded_decision is not None and recorded_decision == decision.value
        if same_caller and same_decision:
            return AiReviewDecisionResult(
                error_code=ERROR_DECISION_ALREADY_RECORDED,
                message="Decision already recorded; idempotent retry.",
                status=status_enum,
                resolution_mode=resolution_mode,
                dispatch_version=dispatch_version,
                details={"decision": decision.value},
            )
        return AiReviewDecisionResult(
            error_code=ERROR_PEER_RESOLVED,
            message="Review already resolved by another decision or the reaper.",
            status=status_enum,
            resolution_mode=resolution_mode,
            dispatch_version=dispatch_version,
            details={
                "responding_delegate_public_id": responding,
                "recorded_decision": recorded_decision,
            },
        )

    async def timeout_review(
        self,
        *,
        review_public_id: str,
        repo: Repository,
        now: datetime | None = None,
    ) -> bool:
        """Plan D §3 + §8 inline timeout: pending/fanout_dispatched -> timeout.

        Called by :func:`create_ai_review_and_await` (Plan D §8) when
        the strategy's deadline elapses with the row still
        non-terminal. Mirrors :meth:`supersede_review` shape — atomic
        CAS UPDATE + ``timeout_marked`` audit event + Q10 v1.2 counter
        decrement — with the resolution_mode set to
        ``timeout_no_response``.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row.
            repo: Repository handle.
            now: Optional wall-clock override for deterministic tests.

        Returns:
            ``True`` when this call won the CAS and the row
            transitioned; ``False`` when a peer (decision / reaper /
            supersede) had already transitioned the row.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        atomic = await repo.atomic_timeout_ai_review(
            review_public_id=review_public_id, now=wall_clock
        )
        if atomic is None:
            return False
        await repo.insert_ai_review_event(
            {
                "public_id": str(uuid7()),
                "review_public_id": review_public_id,
                "event_type": AiReviewEventTypeEnum.TIMEOUT_MARKED.value,
                "actor_delegate_public_id": None,
                "previous_status": atomic["previous_status"],
                "new_status": AiReviewStatusEnum.TIMEOUT.value,
                "payload": {"trigger": "strategy_await_loop"},
                "occurred_at": wall_clock,
            }
        )
        await repo.decrement_delegate_active_count_for_review(
            review_public_id=review_public_id,
            selected_delegate_public_id=atomic["selected_delegate_public_id"],
            now=wall_clock,
        )
        logger.info(
            "ai_review timeout (strategy await loop)",
            review_public_id=review_public_id,
        )
        return True

    async def supersede_review(
        self,
        *,
        review_public_id: str,
        reason: str,
        repo: Repository,
        now: datetime | None = None,
    ) -> bool:
        """Plan D §3 strategy-abandon path: pending/fanout_dispatched -> superseded.

        Atomically transitions the row to ``superseded`` /
        ``superseded_by_strategy``, appends a ``superseded`` audit
        event with the reason, and decrements the
        ``ai_delegates.active_reviews_count`` exactly once via the
        Q10 v1.2 ``counter_decremented_at`` CAS primitive shared with
        :meth:`submit_decision` and :meth:`_reaper_tick`.

        Args:
            review_public_id: UUID7 of the ``ai_reviews`` row to
                supersede.
            reason: Free-text rationale stored on the audit-event
                payload (no length cap enforced here — strategy code
                is internal).
            repo: Repository handle (single-transaction caller
                context).
            now: Optional override for the wall-clock; tests inject a
                fixed value so the resolved_at + audit timestamps are
                deterministic.

        Returns:
            ``True`` when this call won the CAS and the row
            transitioned to terminal; ``False`` when a peer (a
            decision, the reaper, or another supersede) had already
            transitioned the row.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        atomic = await repo.atomic_supersede_ai_review(
            review_public_id=review_public_id, now=wall_clock
        )
        if atomic is None:
            return False
        await repo.insert_ai_review_event(
            {
                "public_id": str(uuid7()),
                "review_public_id": review_public_id,
                "event_type": AiReviewEventTypeEnum.SUPERSEDED.value,
                "actor_delegate_public_id": None,
                "previous_status": atomic["previous_status"],
                "new_status": AiReviewStatusEnum.SUPERSEDED.value,
                "payload": {"reason": reason},
                "occurred_at": wall_clock,
            }
        )
        await repo.decrement_delegate_active_count_for_review(
            review_public_id=review_public_id,
            selected_delegate_public_id=atomic["selected_delegate_public_id"],
            now=wall_clock,
        )
        logger.info(
            "ai_review superseded",
            review_public_id=review_public_id,
            reason=reason,
        )
        return True

    async def _reaper_tick(self, *, repo: Repository, now: datetime | None = None) -> int:
        """Plan D §3.3 single-tick reaper iteration.

        Snapshots up to N expired pending/fanout_dispatched reviews,
        then per-row drives the existing
        :meth:`Repository.atomic_timeout_ai_review` CAS + audit-event
        + counter-decrement primitives shared with
        :meth:`submit_decision`. Returns the number of rows that won
        the per-row CAS this tick (rows that lost — because a peer
        decision or earlier reaper landed first — are silently
        skipped, matching the spec's "drop-the-lease" guarantee).

        Args:
            repo: Repository handle.
            now: Optional override for the wall-clock.

        Returns:
            Number of rows successfully transitioned to ``timeout`` by
            this tick.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        candidates = await repo.list_expired_pending_reviews(now=wall_clock)
        transitioned = 0
        for candidate in candidates:
            atomic = await repo.atomic_timeout_ai_review(
                review_public_id=candidate["public_id"], now=wall_clock
            )
            if atomic is None:
                continue
            await repo.insert_ai_review_event(
                {
                    "public_id": str(uuid7()),
                    "review_public_id": candidate["public_id"],
                    "event_type": AiReviewEventTypeEnum.TIMEOUT_MARKED.value,
                    "actor_delegate_public_id": None,
                    "previous_status": atomic["previous_status"],
                    "new_status": AiReviewStatusEnum.TIMEOUT.value,
                    "payload": {"trigger": "reaper_tick"},
                    "occurred_at": wall_clock,
                }
            )
            await repo.decrement_delegate_active_count_for_review(
                review_public_id=candidate["public_id"],
                selected_delegate_public_id=atomic["selected_delegate_public_id"],
                now=wall_clock,
            )
            transitioned += 1
        if transitioned > 0:
            logger.info("ai_review reaper tick", transitioned=transitioned)
        return transitioned

    async def _offline_scanner_tick(
        self,
        *,
        repo: Repository,
        now: datetime | None = None,
        heartbeat_window_seconds: int = DEFAULT_HEARTBEAT_WINDOW_SECONDS,
    ) -> int:
        """Plan D §3.4 single-tick Layer 2 offline scanner iteration.

        Snapshots up to N pending reviews whose ``fanout_after`` has
        elapsed AND whose selected delegate has gone silent past the
        heartbeat window, then drives the per-row atomic
        ``pending -> fanout_dispatched`` CAS + ``fanout_dispatched``
        audit event for each. Returns the number of fanouts dispatched
        this tick.

        Args:
            repo: Repository handle.
            now: Optional override for the wall-clock.
            heartbeat_window_seconds: Liveness window passed through
                to the eligibility query.

        Returns:
            Number of pending reviews whose CAS won this tick.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        candidates = await repo.list_offline_pending_reviews(
            now=wall_clock, heartbeat_window_seconds=heartbeat_window_seconds
        )
        return await self._dispatch_fanout_for_candidates(
            candidates=candidates,
            repo=repo,
            now=wall_clock,
            trigger="offline_scanner_tick",
        )

    async def _delegate_offline_tick(
        self,
        *,
        delegate_public_id: str,
        repo: Repository,
        now: datetime | None = None,
    ) -> int:
        """Plan D §3.5 fast-path equivalent of the §3.4 scanner.

        Scans only the pending rows whose
        ``selected_delegate_public_id`` matches the freshly-offline
        delegate, then drives the same atomic fanout-dispatch CAS as
        the Layer 2 scanner. Idempotent vs §3.4: a row that the
        scanner already transitioned is skipped because the CAS
        predicate is ``status='pending'``.

        Args:
            delegate_public_id: ``ai_delegates.public_id`` of the
                delegate whose ``bus.delegate_offline`` event triggered
                the call.
            repo: Repository handle.
            now: Optional override for the wall-clock. Callers from the
                bus subscriber pass ``msg.last_seen_at`` so the
                ``fanout_after`` gate matches the instant the delegate
                actually went offline; reviews whose ``fanout_after``
                is still in the future are deferred to the §3.4 Layer 2
                scanner per the :class:`DelegateOfflineData` schema
                contract.

        Returns:
            Number of pending reviews whose CAS won this fast-path
            invocation.
        """
        wall_clock = now if now is not None else datetime.now(UTC)
        candidates = await repo.list_pending_reviews_for_delegate(
            selected_delegate_public_id=delegate_public_id, now=wall_clock
        )
        return await self._dispatch_fanout_for_candidates(
            candidates=candidates,
            repo=repo,
            now=wall_clock,
            trigger="delegate_offline_bus",
        )

    async def _dispatch_fanout_for_candidates(
        self,
        *,
        candidates: list[PendingReviewSummary],
        repo: Repository,
        now: datetime,
        trigger: str,
    ) -> int:
        """Common per-candidate CAS + audit-event loop for §3.4 / §3.5.

        Both the Layer 2 scanner and the §3.5 fast-path share the same
        per-row dispatch shape: atomic CAS UPDATE pending ->
        fanout_dispatched (incrementing ``dispatch_version``), then
        append a ``fanout_dispatched`` audit-event row with the
        trigger source on the payload. Extracted into a helper so the
        two callers can't drift on the audit-event shape.
        """
        dispatched = 0
        for candidate in candidates:
            new_version = await repo.atomic_dispatch_fanout(
                review_public_id=candidate["public_id"], now=now
            )
            if new_version is None:
                continue
            await repo.insert_ai_review_event(
                {
                    "public_id": str(uuid7()),
                    "review_public_id": candidate["public_id"],
                    "event_type": AiReviewEventTypeEnum.FANOUT_DISPATCHED.value,
                    "actor_delegate_public_id": None,
                    "previous_status": AiReviewStatusEnum.PENDING.value,
                    "new_status": AiReviewStatusEnum.FANOUT_DISPATCHED.value,
                    "payload": {
                        "trigger": trigger,
                        "dispatch_version": new_version,
                    },
                    "occurred_at": now,
                }
            )
            dispatched += 1
        if dispatched > 0:
            logger.info("ai_review fanout dispatched", trigger=trigger, count=dispatched)
        return dispatched

    async def handle_caps_violation_bus_message(self, msg: CapsViolationAfterAiApproveData) -> bool:
        """Plan D §3.6 — re-fanout caps-violation events to the WS topic family.

        Subscribes to the internal ``bus.caps_violation_after_ai_approve``
        topic; for each event, translates the internal
        :class:`CapsViolationAfterAiApproveData`
        (``type="caps_violation_after_ai_approve"``) into the external
        :class:`AiReviewCapsViolationFrameData`
        (``type="ai_review.caps_violation"``, fixed by Plan A §4.2
        line 467 / Q16) and publishes it on the
        ``ai_reviews.{user_public_id}.{strategy_public_id}.caps_violation``
        topic so the bridge per-frame scope filter (Q15) routes the
        frame to the right delegate's UI dispatcher
        (Plan A §4.2 line 503).

        Best-effort: a missing publisher logs a warning instead of
        raising (mirrors :class:`ScopeGrantService` semantics — a
        singleton spun up before the FastAPI lifespan attached one
        still tolerates the call). A send failure degrades to a
        logged exception so a transient broker hiccup never crashes
        the subscriber loop. Provenance fields are stamped fresh from
        :attr:`MessagePublisher.tracker` so the per-topic gap detector
        on the bridge sees a monotonic sequence keyed to the external
        ``ai_reviews.{user}.{strategy}.caps_violation`` topic instead
        of the internal ``bus.caps_violation_after_ai_approve``
        sequence (which would be interleaved with other strategies'
        caps events under the same internal stream key, causing false
        gap telemetry on the per-strategy external stream).

        Args:
            msg: Decoded :class:`CapsViolationAfterAiApproveData`
                payload published by :class:`TradingCapsEnforcer`
                (publisher-side wiring lands in a follow-up chunk).

        Returns:
            ``True`` when the WS event was handed to the publisher,
            ``False`` when the publisher slot was empty OR the publish
            attempt raised.
        """
        if self._msg_publisher is None:
            logger.warning(
                "ai_reviews caps_violation NOT broadcast for review_public_id={}: "
                "AiReviewService publisher unavailable",
                msg.review_public_id,
            )
            return False
        topic = f"ai_reviews.{msg.user_public_id}.{msg.strategy_public_id}.caps_violation"
        tracker = self._msg_publisher.tracker
        external_frame = AiReviewCapsViolationFrameData(
            public_id=str(uuid7()),
            timestamp=datetime.now(UTC),
            session_id=tracker.session_id,
            sequence_id=tracker.next_sequence(topic),
            review_public_id=msg.review_public_id,
            user_public_id=msg.user_public_id,
            strategy_public_id=msg.strategy_public_id,
            wallet_public_id=msg.wallet_public_id,
            instrument_public_id=msg.instrument_public_id,
            cap_type=msg.cap_type,
            attempted=msg.attempted,
            limit=msg.limit,
            dispatch_version=msg.dispatch_version,
        )
        try:
            await self._msg_publisher.send(topic, external_frame)
        except Exception as exc:
            logger.exception(
                "Failed to broadcast ai_reviews caps_violation for review_public_id={}: {}",
                msg.review_public_id,
                exc,
            )
            return False
        return True

    async def handle_delegate_offline_bus_message(
        self, msg: DelegateOfflineData, *, repo: Repository
    ) -> int:
        """Plan D §3.5 ``bus.delegate_offline`` subscriber entry point.

        Wraps :meth:`_delegate_offline_tick` so the ZMQ listener loop
        (wired in a follow-up commit) can dispatch on the message
        envelope without knowing the ``_tick`` argument shape.

        Args:
            msg: Decoded ``bus.delegate_offline`` payload published by
                :class:`WebSocketAuthManager`.
            repo: Repository handle (passed by the listener's per-tick
                wiring).

        Returns:
            Number of pending reviews whose CAS won this fast-path
            invocation (forwarded from
            :meth:`_delegate_offline_tick`).
        """
        return await self._delegate_offline_tick(
            delegate_public_id=msg.delegate_public_id,
            repo=repo,
            now=msg.last_seen_at,
        )

    @staticmethod
    def _resolution_mode_for(
        *,
        previous_status: str,
        selected_delegate_public_id: str,
        responding_delegate_public_id: str,
    ) -> AiReviewResolutionModeEnum:
        """Plan A Q4 — pick the resolution_mode the row's transition implies.

        - ``pending`` + selected==responding -> PICK_ONE_PRIMARY (most common).
        - ``fanout_dispatched`` + selected==responding -> SECONDARY_AFTER_FANOUT
          (selected delegate came back online after fanout fired).
        - ``fanout_dispatched`` + selected!=responding -> FANOUT_FIRST_RESPONDER
          (different eligible delegate won the fanout race).
        """
        if previous_status == AiReviewStatusEnum.PENDING.value:
            return AiReviewResolutionModeEnum.PICK_ONE_PRIMARY
        if responding_delegate_public_id == selected_delegate_public_id:
            return AiReviewResolutionModeEnum.SECONDARY_AFTER_FANOUT
        return AiReviewResolutionModeEnum.FANOUT_FIRST_RESPONDER

    def set_repository_factory(self, repository_factory: Callable[[], Repository] | None) -> None:
        """Inject the repository factory used by the bus listener path.

        Mirrors :meth:`WebSocketAuthManager.set_wiring`'s
        ``repository_factory`` argument: the bus listener needs a fresh
        :class:`Repository` per dispatch (so the per-tick UnitOfWork
        is bounded + does not bleed connections across handler calls).
        Production wires this from the FastAPI lifespan; tests pass a
        callable that returns a fake repository.

        Args:
            repository_factory: Callable that returns a
                :class:`Repository`, or ``None`` to clear.
        """
        self._repository_factory = repository_factory

    async def start_bus_listener(self, zmq_broker_xpub: str) -> None:
        """Open the AI-review bus subscriber and start the dispatch task.

        Subscribes to ``bus.delegate_offline`` (Q17 layer-1 fast-path
        published by :class:`WebSocketAuthManager._publish_delegate_offline`
        — sole publisher) AND ``bus.caps_violation_after_ai_approve``
        (Plan D §3.6 fanout published by ``TradingCapsEnforcer`` —
        deferred publisher-side chunk). Both topics dispatch to the
        existing per-message handlers shipped in Phase 1 #2 + #8.

        Idempotent + restart-safe via :attr:`_bus_listener_lock`: a
        second call while a healthy listener is already running is a
        no-op; a second call after the previous task finished early
        (e.g. the loop unwound on an unexpected exception) reaps the
        dead task and re-allocates so the bus path stays live across
        single-listener failures. Mirrors
        :meth:`WebSocketAuthManager.start_admin_listener` semantics.

        Multi-instance deployment caveat: Plan D §14 anticipates each
        process running its own bus subscriber. For the
        ``bus.delegate_offline`` branch that is safe — the handler
        executes a DB CAS UPDATE per affected pending review, so only
        one process wins per row regardless of how many subscribers
        receive the same internal event. For
        ``bus.caps_violation_after_ai_approve`` the handler currently
        re-publishes a fresh ``ai_reviews.*.caps_violation`` external
        WS frame on every dispatch, which under multi-instance
        deployment would N-duplicate the WS fanout (each WS bridge
        subscribes to ``ai_reviews.*`` and would receive N copies of
        the same caps event from N processes' re-publishes). The
        single-instance Snapper deployment is the current target and
        is unaffected; multi-instance dedup is tracked as a Phase 2
        follow-up — likely via a per-bus-event idempotency claim
        column on the :class:`AiReview` row, or by partitioning the
        caps-violation re-publish to a single dedicated worker.

        Args:
            zmq_broker_xpub: Address of the broker's XPUB endpoint.
                Empty string skips the listener entirely (test mode +
                ``SERVER_API_ONLY`` boots).
        """
        async with self._bus_listener_lock:
            if self._bus_listen_task is not None and not self._bus_listen_task.done():
                return
            if self._bus_listen_task is not None:
                await self._reap_bus_listener_unlocked()
            if not zmq_broker_xpub:
                logger.info("AiReviewService: empty broker XPUB, skipping bus listener")
                return
            self._bus_zmq_context = zmq.asyncio.Context()
            raw_sub_socket = self._bus_zmq_context.socket(zmq.SUB)
            apply_hwm(raw_sub_socket, rcvhwm=HWM_AUDIT)
            raw_sub_socket.connect(zmq_broker_xpub)
            self._bus_subscriber = ValidatedSubscriber(raw_sub_socket)
            self._bus_subscriber.subscribe(_BUS_DELEGATE_OFFLINE_TOPIC)
            self._bus_subscriber.subscribe(_BUS_CAPS_VIOLATION_TOPIC)
            self._bus_running = True
            self._bus_listen_task = asyncio.create_task(self._bus_listen_loop())
            logger.info(
                "AiReviewService: bus listener subscribed to {} + {} on {}",
                _BUS_DELEGATE_OFFLINE_TOPIC,
                _BUS_CAPS_VIOLATION_TOPIC,
                zmq_broker_xpub,
            )

    async def stop_bus_listener(self) -> None:
        """Cancel the dispatch task, close the subscriber, terminate the context.

        Serialised against :meth:`start_bus_listener` via
        :attr:`_bus_listener_lock` so an overlapping start cannot
        allocate a new socket while we are tearing the old one down.
        Resource refs are captured into locals BEFORE attributes are
        nulled so a concurrent operation that races into the lock
        cannot observe stale references after the close. Idempotent.
        """
        async with self._bus_listener_lock:
            await self._reap_bus_listener_unlocked()

    async def _reap_bus_listener_unlocked(self) -> None:
        """Tear down listener resources. Caller MUST hold ``_bus_listener_lock``.

        Captures every resource reference into locals BEFORE clearing
        the attributes so a follow-up :meth:`start_bus_listener` (which
        runs after we release the lock) sees a fully-clean slate and
        cannot interfere with the close + term calls below. Mirrors
        :meth:`WebSocketAuthManager._reap_admin_listener_unlocked`.
        """
        self._bus_running = False
        task = self._bus_listen_task
        subscriber = self._bus_subscriber
        context = self._bus_zmq_context
        self._bus_listen_task = None
        self._bus_subscriber = None
        self._bus_zmq_context = None
        if task is not None:
            task.cancel()
            with contextlib.suppress(asyncio.CancelledError, Exception):
                await task
        if subscriber is not None:
            with contextlib.suppress(Exception):
                subscriber.close()
        if context is not None:
            with contextlib.suppress(Exception):
                context.term()

    async def _bus_listen_loop(self) -> None:
        """Receive AI-review bus events and dispatch to per-topic handlers.

        Per-message failures (parse errors, handler exceptions, recv
        errors) are caught + logged so a single bad frame can never
        silently stop the listener. Only :class:`asyncio.CancelledError`
        from :meth:`stop_bus_listener` unwinds the loop. The recv +
        dispatch halves are factored into helpers so the loop body
        stays under the project's cognitive-complexity ceiling.
        """
        subscriber = self._bus_subscriber
        if subscriber is None:
            return
        try:
            while self._bus_running:
                frame = await self._bus_recv_one_frame(subscriber)
                if frame is None:
                    continue
                await self._bus_dispatch_frame(*frame)
        except asyncio.CancelledError:
            logger.info("AiReviewService: bus listen loop cancelled")
            raise

    async def _bus_recv_one_frame(self, subscriber: ValidatedSubscriber) -> tuple[str, str] | None:
        """Receive and decode one AI-review bus frame.

        Returns ``None`` (after a small backoff) when recv raises a
        non-cancellation error OR when the decoded bytes are not
        valid UTF-8 — both cases let the caller simply ``continue``
        instead of letting a malformed frame unwind the listener
        loop. Decode is INSIDE the ``try`` so a
        :class:`UnicodeDecodeError` cannot escape the helper.
        """
        try:
            topic_bytes, payload_bytes = await subscriber.recv_multipart()
            topic = topic_bytes.decode() if isinstance(topic_bytes, bytes) else str(topic_bytes)
            payload = (
                payload_bytes.decode() if isinstance(payload_bytes, bytes) else str(payload_bytes)
            )
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.error("AiReviewService bus listener recv failed: {}", exc)
            await asyncio.sleep(_AI_REVIEW_LISTEN_RECV_BACKOFF_S)
            return None
        return topic, payload

    async def _bus_dispatch_frame(self, topic: str, payload: str) -> None:
        """Route one decoded AI-review bus frame to its typed handler.

        Handler exceptions other than :class:`asyncio.CancelledError`
        are logged + swallowed so one bad frame cannot stop the
        listener — the column-level audit trail
        (``ai_review_events``) remains the source of truth.

        ``bus.delegate_offline`` requires a fresh :class:`Repository`
        per dispatch so the per-tick UnitOfWork is bounded; if the
        lifespan never injected a factory we log a warning + skip
        (matches the ``ScopeGrantService`` best-effort contract).
        """
        try:
            if topic == _BUS_DELEGATE_OFFLINE_TOPIC:
                if self._repository_factory is None:
                    logger.warning(
                        "AiReviewService: {} received without repository_factory wiring; skipping",
                        _BUS_DELEGATE_OFFLINE_TOPIC,
                    )
                    return
                await self.handle_delegate_offline_bus_message(
                    DelegateOfflineData.from_json(payload),
                    repo=self._repository_factory(),
                )
            elif topic == _BUS_CAPS_VIOLATION_TOPIC:
                await self.handle_caps_violation_bus_message(
                    CapsViolationAfterAiApproveData.from_json(payload)
                )
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.error(
                "AiReviewService bus handler failed: topic={} err={}",
                topic,
                exc,
            )

    @classmethod
    def get_instance(cls) -> AiReviewService:
        """Return the singleton, creating it on first call.

        Returns:
            The process-wide ``AiReviewService`` singleton.
        """
        if cls._instance is None:
            cls._instance = AiReviewService()
        return cls._instance

    @classmethod
    def clear_instance(cls) -> None:
        """Reset the singleton — test-only seam."""
        cls._instance = None
        cls._initialized = False


def get_ai_review_service() -> AiReviewService:
    """Module-level accessor mirroring :func:`get_scope_grant_service`.

    Imported by FastAPI ``Depends`` wiring + by the MCP tool registration so
    the same singleton is observed across both transports.

    Returns:
        The process-wide ``AiReviewService`` singleton.
    """
    return AiReviewService.get_instance()
