"""Public-OSS prose audit for the bridge wire-contract working-tree file.

The bridge OSS repo cannot reference internal Snapper jargon — plan
letters, paragraph anchors, internal repo paths, internal handle
names. The autogenerator already emits header-only docs in v1, so
this scan is a defensive net that catches:

    1. Future regressions where someone reintroduces per-interface
       JSDoc that copies a backend Pydantic docstring containing
       internal jargon.
    2. Manual edits to the generated file that smuggle internal
       references through (the file is autogenerated; manual edits
       are forbidden, but the scan is the enforcement gate).

Exit codes:

    0 — no forbidden tokens found
    1 — at least one forbidden token found; the script prints every
        match with file path + line number for the developer to fix
    2 — target file missing or unreadable
"""

import argparse
import re
import sys
from pathlib import Path

from scripts.generate_types import _BRIDGE_OUTPUT_DEFAULT

_FORBIDDEN_PATTERNS: dict[str, re.Pattern[str]] = {
    "plan-letter": re.compile(r"Plan [A-Z]"),
    "paragraph-anchor": re.compile(r"§"),
    "q-reference": re.compile(r"\bQ[0-9]+\b"),
    "phase-reference": re.compile(r"Phase [0-9]"),
    "snapper-src-path": re.compile(r"src/snapper/"),
    "frontend-src-path": re.compile(r"frontend/src/"),
    "proprietary-path": re.compile(r"proprietary/"),
    "memory-path": re.compile(r"memory/"),
    "session-resume": re.compile(r"session_resume"),
    "memory-index": re.compile(r"MEMORY\.md"),
    "internal-handle": re.compile(r"holzera"),
}


def _project_root() -> Path:
    """Return the repository root (two levels above this script)."""
    return Path(__file__).resolve().parent.parent.parent


def scan_forbidden_tokens(target_path: Path) -> list[tuple[int, str, str]]:
    """Scan a TypeScript file for forbidden internal-jargon tokens.

    Args:
        target_path: Working-tree path to scan. Usually the generated
            ``wire-contract.ts`` file.

    Returns:
        A list of ``(line_number, pattern_name, line_content)``
        tuples for every match. Empty when the file is clean.

    Raises:
        FileNotFoundError: When ``target_path`` does not exist.
    """
    if not target_path.is_file():
        raise FileNotFoundError(
            f"Bridge wire-contract not found at {target_path}; "
            "run `make ts-bridge` to generate it before checking OSS prose."
        )

    findings: list[tuple[int, str, str]] = []
    for line_number, line in enumerate(
        target_path.read_text(encoding="utf-8").splitlines(),
        start=1,
    ):
        for name, pattern in _FORBIDDEN_PATTERNS.items():
            if pattern.search(line):
                findings.append((line_number, name, line))
    return findings


def main(argv: list[str] | None = None) -> int:
    """CLI entry point invoked by ``make bridge-check``.

    Args:
        argv: Optional CLI arguments (defaults to ``sys.argv[1:]``).

    Returns:
        Process exit code (0/1/2 — see module docstring).
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target",
        default=None,
        help=(
            "Override the working-tree wire-contract path "
            "(default: integrations/snapper-mcp/src/generated/wire-contract.ts)"
        ),
    )
    args = parser.parse_args(argv)

    if args.target is not None:
        target_path = Path(args.target)
        if not target_path.is_absolute():
            target_path = (_project_root() / target_path).resolve()
    else:
        target_path = (_project_root() / _BRIDGE_OUTPUT_DEFAULT).resolve()

    try:
        findings = scan_forbidden_tokens(target_path)
    except FileNotFoundError as exc:
        print(f"bridge-check oss-prose: {exc}", file=sys.stderr)
        return 2

    if not findings:
        print(f"bridge-check oss-prose: OK — {target_path} contains no forbidden tokens")
        return 0

    print(
        f"bridge-check oss-prose: FAIL — {len(findings)} forbidden token(s) found in {target_path}",
        file=sys.stderr,
    )
    for line_number, name, line in findings:
        print(f"  line {line_number} [{name}]: {line.rstrip()}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
