"""TypedDict definitions for Repository row contracts.

Write rows (upsert params) and read rows (query return values) are defined
here to keep repository.py focused on logic.  All types are runtime dicts
with compile-time type checking — no Pydantic overhead for trusted internal
data transfer.
"""

from datetime import datetime
from typing import TypedDict


class CandleUpsertRow(TypedDict, total=False):
    """Row dict for upsert_candles.

    Required keys are always present in caller-constructed dicts.
    Optional keys (public_id, known_to) are auto-generated by the repo
    if absent.
    """

    instrument_public_id: str
    open_at: datetime
    timestamp: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None
    trades: int | None
    session_id: str
    sequence_id: int
    public_id: str
    known_to: datetime


class TradeUpsertRow(TypedDict, total=False):
    """Row dict for upsert_trades."""

    instrument_public_id: str
    timestamp: datetime
    price: float
    size: float
    side: str
    trade_id: str
    executed_at: datetime | None
    session_id: str
    sequence_id: int
    public_id: str


class TickUpsertRow(TypedDict, total=False):
    """Row dict for upsert_ticks."""

    instrument_public_id: str
    timestamp: datetime
    bid: float | None
    ask: float | None
    last: float | None
    volume: float
    session_id: str
    sequence_id: int
    public_id: str


class TickRow(TypedDict):
    """Row dict returned by get_ticks."""

    timestamp: datetime
    bid: float | None
    ask: float | None
    last: float | None
    volume: float
    public_id: str
    session_id: str
    sequence_id: int


class MarketSnapshotUpsertRow(TypedDict, total=False):
    """Row dict for upsert_market_snapshots."""

    instrument_public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    bid: float | None
    bid_volume: float | None
    ask: float | None
    ask_volume: float | None
    last_price: float | None
    volume_24h: float | None
    vwap_24h: float | None
    low_24h: float | None
    high_24h: float | None
    change_24h: float | None
    spread: float | None
    spread_pct: float | None
    public_id: str
    known_to: datetime


class CandleRow(TypedDict):
    """Row dict returned by get_candles."""

    open_at: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None
    trades: int | None
    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int


class TradeRow(TypedDict):
    """Row dict returned by get_trades."""

    timestamp: datetime
    executed_at: datetime | None
    price: float
    size: float
    side: str
    trade_id: str


class MarketSnapshotRow(TypedDict):
    """Row dict returned by get_market_snapshots."""

    ts: datetime
    instrument_public_id: str
    bid: float | None
    bid_volume: float | None
    ask: float | None
    ask_volume: float | None
    last: float | None
    volume: float | None
    vwap: float | None
    low: float | None
    high: float | None


class SignalRow(TypedDict):
    """Row dict returned by get_signals."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    side: str
    strength: float
    reason: str
    strategy_name: str
    price: float
    fired_at: datetime


class OrderRow(TypedDict):
    """Row dict returned by get_orders."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    client_order_id: str
    exchange_order_id: str | None
    created_at: datetime
    updated_at: datetime | None
    side: str
    order_type: str
    price: float | None
    size: float
    filled_size: float
    average_price: float | None
    status: str
    time_in_force: str | None
    error: str | None


class ExecutionRow(TypedDict):
    """Row dict returned by get_executions."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    trade_id: str | None
    exchange_order_id: str | None
    client_order_id: str
    instrument: str
    exchange: str
    side: str
    size: float
    price: float
    fee: float
    fee_asset: str
    status: str
    executed_at: datetime


class PositionRow(TypedDict):
    """Row dict returned by get_positions."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    quantity: float
    average_price: float
    unrealized_pnl: float | None
    realized_pnl: float | None


class SettingRow(TypedDict):
    """Row dict returned by get_settings and get_setting_by_key."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    key: str
    value: str
    category: str
    description: str | None
    updated_by: str | None
