"""TypedDict definitions for Repository row contracts.

Write rows (upsert params) and read rows (query return values) are defined
here to keep repository.py focused on logic.  All types are runtime dicts
with compile-time type checking — no Pydantic overhead for trusted internal
data transfer.
"""

from datetime import datetime
from typing import Any
from typing import NotRequired
from typing import TypedDict

from snapper.core.json_types import JsonObject


class CandleUpsertRow(TypedDict, total=False):
    """Row dict for upsert_candles.

    Required keys are always present in caller-constructed dicts.
    Optional keys (public_id, known_to) are auto-generated by the repo
    if absent.
    """

    instrument_public_id: str
    open_at: datetime
    timestamp: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None
    trades: int | None
    session_id: str
    sequence_id: int
    public_id: str
    known_to: datetime


class TradeUpsertRow(TypedDict, total=False):
    """Row dict for upsert_trades."""

    instrument_public_id: str
    timestamp: datetime
    price: float
    size: float
    side: str
    trade_id: str | None
    executed_at: datetime | None
    session_id: str
    sequence_id: int
    public_id: str


class TickUpsertRow(TypedDict, total=False):
    """Row dict for upsert_ticks."""

    instrument_public_id: str
    timestamp: datetime
    bid: float | None
    ask: float | None
    last: float | None
    volume: float
    session_id: str
    sequence_id: int
    public_id: str


class TickRow(TypedDict):
    """Row dict returned by get_ticks."""

    timestamp: datetime
    bid: float | None
    ask: float | None
    last: float | None
    volume: float
    public_id: str
    session_id: str
    sequence_id: int


class MarketSnapshotUpsertRow(TypedDict, total=False):
    """Row dict for upsert_market_snapshots."""

    instrument_public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    bid: float | None
    bid_volume: float | None
    ask: float | None
    ask_volume: float | None
    last_price: float | None
    volume_24h: float | None
    vwap_24h: float | None
    low_24h: float | None
    high_24h: float | None
    change_24h: float | None
    spread: float | None
    spread_pct: float | None
    public_id: str
    known_to: datetime


class CandleRow(TypedDict):
    """Row dict returned by get_candles."""

    open_at: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None
    trades: int | None
    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int


class TradeRow(TypedDict):
    """Row dict returned by get_trades."""

    timestamp: datetime
    executed_at: datetime | None
    price: float
    size: float
    side: str
    trade_id: str | None


class MarketSnapshotRow(TypedDict):
    """Row dict returned by get_market_snapshots."""

    ts: datetime
    instrument_public_id: str
    bid: float | None
    bid_volume: float | None
    ask: float | None
    ask_volume: float | None
    last: float | None
    volume: float | None
    vwap: float | None
    low: float | None
    high: float | None


class SignalRow(TypedDict):
    """Row dict returned by get_signals."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    side: str
    strength: float
    reason: str
    strategy_name: str
    price: float
    fired_at: datetime
    wallet_public_id: str | None
    operator_public_id: str | None


class OrderInsertRow(TypedDict):
    """Row dict used by insert_order."""

    instrument_public_id: str
    client_order_id: str | None
    exchange_order_id: str | None
    created_at: datetime
    side: str
    order_type: str
    price: float | None
    size: float
    status: str
    session_id: str
    sequence_id: int
    timestamp: datetime
    wallet_public_id: str
    operator_public_id: NotRequired[str | None]
    time_in_force: NotRequired[str | None]
    mode: NotRequired[str]
    leverage: NotRequired[int | None]
    reduce_only: NotRequired[bool]


class ExecutionInsertRow(TypedDict):
    """Row dict used by insert_execution."""

    order_public_id: str
    timestamp: datetime
    side: str
    status: str
    price: float
    size: float
    fee: float
    fee_asset: str
    session_id: str
    sequence_id: int
    wallet_public_id: str
    exec_id: NotRequired[str | None]
    trade_id: NotRequired[str | None]
    operator_public_id: NotRequired[str | None]
    liquidity_role: NotRequired[str]


class OrderRow(TypedDict):
    """Row dict returned by get_orders."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    mode: str
    client_order_id: str
    exchange_order_id: str | None
    created_at: datetime
    updated_at: datetime | None
    side: str
    order_type: str
    price: float | None
    size: float
    filled_size: float
    average_price: float | None
    status: str
    time_in_force: str | None
    error: str | None
    leverage: int | None
    reduce_only: bool
    wallet_public_id: str | None
    operator_public_id: str | None


class ExecutionRow(TypedDict):
    """Row dict returned by get_executions."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    trade_id: str | None
    exchange_order_id: str | None
    client_order_id: str
    instrument: str
    exchange: str
    side: str
    size: float
    price: float
    fee: float
    fee_asset: str
    status: str
    executed_at: datetime
    wallet_public_id: str | None
    operator_public_id: str | None
    liquidity_role: NotRequired[str]


class PositionRow(TypedDict):
    """Row dict returned by get_positions."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument: str
    exchange: str
    mode: str
    quantity: float
    average_price: float
    unrealized_pnl: float | None
    realized_pnl: float | None
    position_cycle_public_id: str | None


class SettingRow(TypedDict):
    """Row dict returned by get_settings and get_setting_by_key."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    key: str
    value: str
    category: str
    description: str | None
    updated_by: str | None


class TradeCommandRow(TypedDict):
    """Row dict returned by trade command queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    command_type: str
    shard_key: str
    exchange: str
    instrument: str
    mode: str
    strategy_id: str
    client_order_id: str
    venue_client_id: str
    idempotency_key: str | None
    side: str
    order_type: str
    quantity: float
    price: float | None
    leverage: int | None
    reduce_only: bool
    status: str
    attempt_count: int
    last_error: str | None
    created_at: datetime
    dispatched_at: datetime | None
    acked_at: datetime | None
    terminal_at: datetime | None
    exchange_order_id: str | None
    supersedes_command_id: str | None
    correlation_id: str
    wallet_public_id: str | None
    operator_public_id: str | None
    user_public_id: str | None
    source_surface: str


class UserTradingCapsRow(TypedDict):
    """Active per-user trading-caps row projection (plan §3.5.3).

    Every cap field is nullable — a NULL cap means unbounded for
    that axis. Consumed by
    :class:`~snapper.application.trade.caps_enforcer.TradingCapsEnforcer`
    to evaluate submission admissibility.
    """

    public_id: str
    user_public_id: str
    max_order_quantity_per_instrument: JsonObject | None
    max_open_orders: int | None
    max_daily_notional_usd: float | None
    max_cancels_per_minute: int | None


class UserActiveTokenInsertRow(TypedDict):
    """Insert row for ``user_active_tokens`` (plan §3.6.2).

    Populated by :meth:`TokenManager.persist_tokens` on every
    successful ``create_tokens()`` so the inventory mirrors every
    outstanding access + refresh JWT. ``token_type`` is the literal
    string ``"access"`` or ``"refresh"``; ``token_hash`` is the
    SHA-256 hex of the full JWT (reversing to raw JWT is not
    supported — only byte-for-byte equality on the hash column is
    used by :meth:`Repository.get_active_token_by_hash`).

    Every field maps 1:1 to a NOT NULL column on
    :class:`~snapper.data.models.UserActiveToken` except
    ``revoked_at`` which starts NULL and is flipped by the kill
    switch / refresh-rotation paths.
    """

    public_id: str
    user_public_id: str
    jti: str
    token_hash: str
    token_type: str
    issued_at: datetime
    expires_at: datetime


class UserActiveTokenVerificationRow(TypedDict):
    """Read projection for DB-backed ``verify_token`` (plan §3.6.3).

    Returned by :meth:`Repository.get_active_token_by_hash` for the
    per-request validation path. The row combines the non-temporal
    ``user_active_tokens`` lifecycle columns with the
    ``users.is_active`` flag so the verifier can reject tokens owned
    by a deactivated user in a single round-trip instead of issuing
    a second SELECT.

    ``revoked_at IS NOT NULL`` or ``user_is_active is False`` →
    verify fails. Both states are cached in the 30-second LRU to
    keep the hot path O(1).
    """

    user_public_id: str
    revoked_at: datetime | None
    expires_at: datetime
    user_is_active: bool


class UserRecentSubmitRow(TypedDict):
    """Row returned by ``get_user_recent_submits`` for notional-cap math.

    Projects only the fields the enforcer needs to compute rolling
    24h USD notional accounting. ``TradeCommand`` stores
    ``instrument`` as the native symbol (e.g., ``"BTC-USD"``) plus
    ``exchange``; these are carried so the enforcer can optionally
    resolve to ``instrument_public_id`` for converter lookups on
    market orders where ``price`` is NULL.

    Phase A limitation: for market orders with ``price IS NULL``,
    the enforcer skips the row from the rolling sum and emits a
    WARN log. A follow-up plan can snapshot the submit-time USD
    notional into a dedicated column when non-USD-quoted
    instruments are onboarded.
    """

    instrument: str
    exchange: str
    quantity: float
    price: float | None


class VenueEventRow(TypedDict):
    """Row dict returned by venue event queries."""

    id: int
    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    event_type: str
    shard_key: str
    command_public_id: str | None
    exchange: str
    instrument: str
    mode: str
    exchange_order_id: str | None
    client_order_id: str | None
    venue_client_id: str | None
    side: str | None
    status: str | None
    fill_price: float | None
    fill_size: float | None
    cum_fill_size: float | None
    fee: float | None
    fee_asset: str | None
    exec_id: str | None
    trade_id: str | None
    error: str | None
    venue_timestamp: datetime | None
    received_at: datetime
    liquidity_role: NotRequired[str]


class TradeProjectionCheckpointRow(TypedDict):
    """Row dict returned by checkpoint queries."""

    public_id: str
    shard_key: str
    position_qty: float
    entry_price: float | None
    position_opened_at: datetime | None
    cash: float
    peak_equity: float
    realized_pnl: float
    turnover: float
    last_venue_event_id: int | None
    last_venue_event_at: datetime | None
    open_command_ids: str | None
    seen_exec_ids: str
    checkpoint_at: datetime
    session_id: str
    operator_public_id: str | None


class RecordVenueEventParams(TypedDict, total=False):
    """Caller-facing params for _record_venue_event.

    Required keys identify the event. Optional keys carry event-type-specific
    data (fills, errors, etc.). The executor fills envelope fields (shard_key,
    mode, timestamps, session tracking) before persisting.
    """

    event_type: str
    exchange_name: str
    instrument: str
    exchange_order_id: str | None
    client_order_id: str | None
    side: str | None
    status: str | None
    fill_price: float | None
    fill_size: float | None
    cum_fill_size: float | None
    fee: float | None
    fee_asset: str | None
    exec_id: str | None
    trade_id: str | None
    error: str | None
    venue_timestamp: datetime | None
    strategy_tag: str | None
    liquidity_role: str | None


class TradeCommandInsertRow(TypedDict, total=False):
    """Insert params for insert_trade_command.

    Required keys match the ORM model's NOT NULL columns.
    Optional keys have server-side defaults or are nullable.
    """

    command_type: str
    shard_key: str
    exchange: str
    instrument: str
    mode: str
    strategy_id: str
    client_order_id: str
    venue_client_id: str
    side: str
    order_type: str
    quantity: float
    price: float | None
    leverage: int | None
    reduce_only: bool
    status: str
    created_at: datetime
    correlation_id: str
    session_id: str
    sequence_id: int
    timestamp: datetime
    idempotency_key: str | None
    supersedes_command_id: str | None
    wallet_public_id: str
    operator_public_id: str | None
    user_public_id: str | None
    plan_public_id: str | None
    exchange_order_id: str | None
    source_surface: str


class VenueEventInsertRow(TypedDict, total=False):
    """Insert params for insert_venue_event.

    Required keys are the mandatory event envelope fields.
    Optional keys correspond to nullable columns or event-type-specific data.
    """

    event_type: str
    shard_key: str
    exchange: str
    instrument: str
    mode: str
    received_at: datetime
    session_id: str
    sequence_id: int
    timestamp: datetime
    command_public_id: str | None
    exchange_order_id: str | None
    client_order_id: str | None
    venue_client_id: str | None
    side: str | None
    status: str | None
    fill_price: float | None
    fill_size: float | None
    cum_fill_size: float | None
    fee: float | None
    fee_asset: str | None
    exec_id: str | None
    trade_id: str | None
    error: str | None
    venue_timestamp: datetime | None
    payload_json: str | None
    wallet_public_id: str
    liquidity_role: str


class InstrumentSpecRow(TypedDict):
    """Row dict returned by get_instrument_spec."""

    instrument_public_id: str
    tick_size: float | None
    lot_size: float | None
    min_order_size: float | None
    max_order_size: float | None
    cost_decimals: int | None
    qty_decimals: int | None
    margin_initial: float | None
    position_limit_long: int | None
    position_limit_short: int | None
    status: str | None
    expiry_at: datetime | None
    instrument_kind: str | None
    funding_type: str | None
    funding_frequency_hours: int | None
    rollover_rate_long: float | None
    rollover_rate_short: float | None
    max_funding_rate: float | None


class InstrumentFrontMonthRow(TypedDict):
    """Repository projection for front-month instrument.

    Joined across multiple temporal tables; API handler mints provenance.
    """

    instrument_public_id: str
    native_symbol: str
    exchange: str
    expiry_at: datetime
    relationship_type: str
    contract_family: str | None


class InstrumentContractRow(TypedDict):
    """Repository projection for futures contract listing.

    Same minted-provenance pattern as InstrumentFrontMonthRow.
    """

    instrument_public_id: str
    native_symbol: str
    exchange: str
    expiry_at: datetime | None
    instrument_kind: str | None
    relationship_type: str
    contract_family: str | None
    is_front_month: bool


class UnderlyingAssetRow(TypedDict):
    """Row dict returned by underlying asset queries."""

    public_id: str
    ticker: str
    name: str
    asset_class: str
    sector: str | None
    description: str | None
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument_count: int


class InstrumentUnderlyingRow(TypedDict):
    """Row dict returned by instrument-underlying mapping queries."""

    public_id: str
    instrument_public_id: str
    underlying_public_id: str
    relationship_type: str
    contract_family: str | None
    native_symbol: str
    exchange: str
    asset_type: str
    timestamp: datetime
    session_id: str
    sequence_id: int


class CheckpointUpsertRow(TypedDict):
    """Upsert params for upsert_checkpoint.

    All fields are required since checkpoints are full-state snapshots.
    """

    shard_key: str
    position_qty: float
    entry_price: float | None
    position_opened_at: datetime | None
    cash: float
    peak_equity: float
    realized_pnl: float
    turnover: float
    last_venue_event_id: int | None
    last_venue_event_at: datetime | None
    open_command_ids: str | None
    seen_exec_ids: str
    checkpoint_at: datetime
    session_id: str
    sequence_id: int
    bus_time: datetime
    wallet_public_id: str
    operator_public_id: NotRequired[str | None]


class ContinuousCandleRow(TypedDict):
    """Row dict for continuous contract candle series.

    Extends the candle concept with contract provenance and
    adjustment metadata for stitched futures series.
    """

    open_at: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None
    trades: int | None
    source_contract: str
    adjustment_factor: float | None


class FundingRateRow(TypedDict):
    """Row dict returned by funding rate queries."""

    public_id: str
    instrument_public_id: str
    exchange: str
    rate_type: str
    direction: str
    rate: float
    notional_asset: str
    effective_from: datetime
    source: str
    timestamp: datetime
    session_id: str
    sequence_id: int


class FundingRateInsertRow(TypedDict):
    """Insert params for insert_funding_rate.

    All fields are required since each row carries its own provenance
    envelope and exchange-side ``effective_from`` timestamp.
    """

    instrument_public_id: str
    exchange: str
    rate_type: str
    direction: str
    rate: float
    notional_asset: str
    effective_from: datetime
    source: str
    session_id: str
    sequence_id: int
    timestamp: datetime


class AccrualLedgerRow(TypedDict):
    """Row dict returned by accrual ledger queries."""

    public_id: str
    instrument_public_id: str
    mode: str
    accrual_type: str
    accrued_at: datetime
    amount: float
    amount_asset: str
    rate: float
    notional: float
    position_quantity_at_accrual: float
    exchange: str
    timestamp: datetime
    session_id: str
    sequence_id: int


class AccrualLedgerInsertRow(TypedDict):
    """Insert params for insert_accrual.

    All fields are required since accruals materialize the periodic
    charge applied to a position and need full provenance.
    ``wallet_public_id`` is mandatory (NOT NULL in the schema);
    ``operator_public_id`` stays optional because strategy-driven
    accruals are not necessarily initiated by a human operator.
    """

    instrument_public_id: str
    mode: str
    accrual_type: str
    accrued_at: datetime
    amount: float
    amount_asset: str
    rate: float
    notional: float
    position_quantity_at_accrual: float
    exchange: str
    session_id: str
    sequence_id: int
    timestamp: datetime
    wallet_public_id: str
    operator_public_id: NotRequired[str | None]


class ScopeGrantRow(TypedDict):
    """Row dict returned by scope grant queries.

    One row per ``wallet_operator_scope_grants`` SCD2 version. ``scope_kind``
    is exactly one of ``"underlying"`` / ``"instrument"``, and exactly one of
    ``underlying_public_id`` / ``instrument_public_id`` is non-NULL — enforced
    at the DB layer by the ``ck_scope_grants_scope_kind_xor`` CHECK constraint.
    """

    public_id: str
    operator_public_id: str
    wallet_public_id: str
    granted_by_user_public_id: str
    scope_kind: str
    underlying_public_id: str | None
    instrument_public_id: str | None
    note: str | None
    timestamp: datetime
    known_to: datetime
    session_id: str
    sequence_id: int


class WalletCredentialRow(TypedDict):
    """Row dict returned by wallet credential queries.

    One row per active ``wallet_credentials`` SCD2 version. The
    ``encrypted_payload`` is the Fernet-encrypted JSON envelope whose
    inner shape depends on ``credential_type`` (see ``WalletCredential``
    docstring). Decryption is the caller's responsibility — the
    repository never returns plaintext to keep accidental logging /
    serialization safe.
    """

    public_id: str
    wallet_public_id: str
    exchange: str
    credential_type: str
    encrypted_payload: str
    label: str | None
    timestamp: datetime
    session_id: str
    sequence_id: int


class OperatorRow(TypedDict):
    """Row dict returned by operator queries.

    One row per active ``operators`` SCD2 version. Used by login flows
    that need to compute the operator set ADMIN users automatically
    receive (every active operator), and by future API endpoints that
    list operators a user can act AS.
    """

    public_id: str
    label: str
    description: str | None
    timestamp: datetime
    session_id: str
    sequence_id: int


class WalletRow(TypedDict):
    """Row dict returned by wallet queries.

    One row per active ``wallets`` SCD2 version. Exposes the label,
    description, and paper flag so Phase 0d frontend pickers can
    render the accessible wallet catalogue without a second lookup.
    The encrypted credential payload lives on a separate table
    (``wallet_credentials``) and is never co-returned with WalletRow
    to keep the read surface free of sensitive data.
    """

    public_id: str
    label: str
    description: str | None
    is_paper: bool
    timestamp: datetime
    session_id: str
    sequence_id: int


class UserOperatorMembershipRow(TypedDict):
    """Row dict returned by user-operator membership queries.

    One row per active ``user_operator_memberships`` SCD2 version. Carries
    enough fields for the login flow to derive ``operator_public_ids`` /
    ``primary_operator_public_id`` for ``AuthPrincipal``.
    """

    public_id: str
    user_public_id: str
    operator_public_id: str
    is_primary: bool
    timestamp: datetime
    session_id: str
    sequence_id: int


class InstrumentOrderCapabilityRow(TypedDict):
    """Read projection for instrument_order_capabilities queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument_public_id: str
    exchange: str
    supported_order_types: list[str]
    supports_post_only: bool
    supports_reduce_only: bool
    supports_amend_in_place: bool
    supports_native_stop_loss: bool
    supports_native_take_profit: bool
    supports_trailing_stop_client_side: bool
    supports_market_making: bool
    supports_short_selling: bool
    supports_leverage: bool
    max_leverage_long: float
    max_leverage_short: float
    min_notional: float | None
    max_order_size: float | None
    top_of_book_quality: str


class VenueFeeScheduleRow(TypedDict):
    """Read projection for venue_fee_schedules queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    exchange: str
    instrument_public_id: str | None
    fee_tier: str
    maker_bps: float
    taker_bps: float
    min_volume_30d: float | None
    currency: str


class ExecutionPlanRow(TypedDict):
    """Read projection for execution_plans queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    plan_type: str
    created_by_user_id: str | None
    created_by_strategy: str | None
    created_via: str
    instrument_public_id: str
    exchange: str
    mode: str
    shard_key: str
    wallet_public_id: str
    operator_public_id: str | None
    total_quantity: float
    filled_quantity: float
    side: str
    parent_plan_public_id: str | None
    position_cycle_public_id: str | None
    params: JsonObject
    status: str
    created_at: datetime
    started_at: datetime | None
    completed_at: datetime | None
    expires_at: datetime | None
    cancel_requested_at: datetime | None
    last_evaluated_at: datetime | None
    last_error: str | None
    idempotency_key: str | None


class ExecutionPlanInsertRow(TypedDict, total=False):
    """Insert params for insert_execution_plan."""

    plan_type: str
    created_by_user_id: str | None
    created_by_strategy: str | None
    created_via: str
    instrument_public_id: str
    exchange: str
    mode: str
    shard_key: str
    wallet_public_id: str
    operator_public_id: str | None
    total_quantity: float
    side: str
    params: JsonObject
    status: str
    created_at: datetime
    parent_plan_public_id: str | None
    position_cycle_public_id: str | None
    expires_at: datetime | None
    idempotency_key: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class ExecutionPlanCheckpointRow(TypedDict):
    """Read projection for execution_plan_checkpoints queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    plan_public_id: str
    state: JsonObject
    last_venue_event_id: int
    last_tick_timestamp: datetime | None
    checkpoint_at: datetime


class CreateScopeGrantRequest(TypedDict):
    """Insert params for create_scope_grant.

    See ``WalletOperatorScopeGrant`` for the per-field semantics. Exactly one
    of ``underlying_public_id`` / ``instrument_public_id`` MUST be non-NULL,
    matching the chosen ``scope_kind``. ``note`` is free-form audit text.
    """

    operator_public_id: str
    wallet_public_id: str
    granted_by_user_public_id: str
    scope_kind: str
    underlying_public_id: str | None
    instrument_public_id: str | None
    note: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class ExecutionPlanDecisionInsertRow(TypedDict):
    """Insert params for insert_execution_plan_decision."""

    plan_public_id: str
    decision_type: str
    decided_at: datetime
    trigger_type: str
    evidence: JsonObject
    emitted_command_public_id: str | None
    new_status: str | None
    reason: str
    decision_importance: str


class ExecutionPlanDecisionRow(TypedDict):
    """Read projection for execution_plan_decisions queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    plan_public_id: str
    decision_type: str
    decided_at: datetime
    trigger_type: str
    evidence: JsonObject
    emitted_command_public_id: str | None
    new_status: str | None
    reason: str
    decision_importance: str


class PositionCycleRow(TypedDict):
    """Read projection for position_cycles queries.

    Represents one open->close lifetime of a position on a shard. Brackets
    (SL/TP) reference a cycle by its public_id.
    """

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    instrument_public_id: str
    exchange: str
    mode: str
    shard_key: str
    wallet_public_id: str
    operator_public_id: str | None
    direction: str
    max_qty: float
    status: str
    opened_at: datetime
    closed_at: datetime | None
    opening_command_public_id: str | None
    closing_command_public_id: str | None


class PositionCycleInsertRow(TypedDict, total=False):
    """Insert params for insert_position_cycle and flip_position_cycle new-row.

    All fields optional at the TypedDict level; callers decide which are
    required. Cycle rows are typically inserted with status='open' and
    closed_at/closing_command_public_id unset.
    """

    instrument_public_id: str
    exchange: str
    mode: str
    shard_key: str
    wallet_public_id: str
    operator_public_id: str | None
    direction: str
    max_qty: float
    status: str
    opened_at: datetime
    closed_at: datetime | None
    opening_command_public_id: str | None
    closing_command_public_id: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestRunInsertRow(TypedDict, total=False):
    """Insert payload for backtest_runs.

    Phase 2c Step 3 adds ``config_hash`` — the caller (API route,
    runner, or CLI) computes
    ``compute_fingerprint(config, for_pairing=True)`` and passes the
    resulting hex digest so the auto-pair comparison UI can group
    runs. Hashing happens in the caller, not the repo — ``data/``
    stays layer-pure and does not depend on ``application/``.
    """

    wallet_public_id: str
    operator_public_id: str | None
    strategy_name: str
    strategy_params: dict[str, Any]
    instrument_public_id: str
    exchange: str
    mode: str
    timeframe: str
    start_date: datetime
    end_date: datetime
    initial_cash: float
    status: str
    execution_mode: str
    fill_model: str
    slippage_bps: float
    commission_bps: float
    config_hash: str | None
    created_by_user_id: str | None
    process_name: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestRunRow(TypedDict):
    """Read projection for backtest_runs queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    wallet_public_id: str
    operator_public_id: str | None
    strategy_name: str
    strategy_params: dict[str, Any]
    instrument_public_id: str
    exchange: str
    mode: str
    timeframe: str
    start_date: datetime
    end_date: datetime
    initial_cash: float
    status: str
    execution_mode: str
    fill_model: str
    slippage_bps: float
    commission_bps: float
    config_hash: str | None
    created_by_user_id: str | None
    started_at: datetime | None
    completed_at: datetime | None
    error: str | None
    process_name: str | None


class BacktestComparisonInsertRow(TypedDict, total=False):
    """Insert payload for backtest_comparisons (Phase 2c Step 4).

    Pair is expected to be normalised to (min, max) lexically by the
    caller before insert, so (A,B) and (B,A) collapse to the same
    row under the partial unique index.
    """

    wallet_public_id: str
    operator_public_id: str | None
    created_by_user_id: str | None
    run_a_public_id: str
    run_b_public_id: str
    config_hash: str | None
    pairing_mode: str
    anchor_run_public_id: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestComparisonRow(TypedDict):
    """Read projection for backtest_comparisons queries."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    wallet_public_id: str
    operator_public_id: str | None
    created_by_user_id: str | None
    run_a_public_id: str
    run_b_public_id: str
    config_hash: str | None
    pairing_mode: str
    anchor_run_public_id: str | None


class BacktestEventInsertRow(TypedDict):
    """Insert payload for backtest_events."""

    run_public_id: str
    event_type: str
    detail: dict[str, Any]
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestEventRow(TypedDict):
    """Read projection for backtest_events."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    run_public_id: str
    event_type: str
    detail: dict[str, Any]


class BacktestResultInsertRow(TypedDict, total=False):
    """Insert payload for backtest_results.

    Phase 2c Step 1 promotes 5 metrics (``sortino_ratio``, ``cagr``,
    ``calmar_ratio``, ``expectancy``, ``avg_trade_pnl``) from the
    ``extra_metrics`` JSON blob to typed nullable-float columns, and
    adds 3 new metrics (``max_drawdown_duration_seconds``,
    ``exposure_ratio``, ``turnover_ratio``). All 8 fields are
    ``float | None`` — degenerate inputs emit ``None`` plus a
    ``metric_warning`` event (see metrics.py).
    """

    run_public_id: str
    total_trades: int
    winning_trades: int
    losing_trades: int
    total_pnl: float
    max_drawdown: float
    sharpe_ratio: float | None
    win_rate: float | None
    profit_factor: float | None
    final_equity: float
    max_equity: float
    sortino_ratio: float | None
    cagr: float | None
    calmar_ratio: float | None
    expectancy: float | None
    avg_trade_pnl: float | None
    max_drawdown_duration_seconds: float | None
    exposure_ratio: float | None
    turnover_ratio: float | None
    extra_metrics: dict[str, Any]
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestResultRow(TypedDict):
    """Read projection for backtest_results.

    Phase 2c Step 1 adds 8 advanced-metric fields. Pre-0005 rows leave
    the 5 promoted fields as ``None`` (with the value still reachable
    via ``extra_metrics``); post-0005 rows populate the typed columns
    and the 5 promoted keys are absent from ``extra_metrics``.
    """

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    run_public_id: str
    total_trades: int
    winning_trades: int
    losing_trades: int
    total_pnl: float
    max_drawdown: float
    sharpe_ratio: float | None
    win_rate: float | None
    profit_factor: float | None
    final_equity: float
    max_equity: float
    sortino_ratio: float | None
    cagr: float | None
    calmar_ratio: float | None
    expectancy: float | None
    avg_trade_pnl: float | None
    max_drawdown_duration_seconds: float | None
    exposure_ratio: float | None
    turnover_ratio: float | None
    extra_metrics: dict[str, Any]


class BacktestSignalInsertRow(TypedDict):
    """Insert payload for backtest_signals.

    ``public_id`` is required and supplied by the engine so the matching
    trade row can carry the same value in ``signal_public_id`` (FK-style
    linkage), enabling parity checks between Direct-DB and ZMQ replay
    engines.
    """

    run_public_id: str
    public_id: str
    signal_time: datetime
    signal_type: str
    instrument: str
    price: float
    indicators: dict[str, Any]
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestSignalRow(TypedDict):
    """Read projection for backtest_signals."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    run_public_id: str
    signal_time: datetime
    signal_type: str
    instrument: str
    price: float
    indicators: dict[str, Any]


class BacktestTradeInsertRow(TypedDict):
    """Insert payload for backtest_trades."""

    run_public_id: str
    executed_at: datetime
    instrument: str
    side: str
    quantity: float
    price: float
    fee: float
    pnl: float | None
    position_after: float
    signal_public_id: str | None
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestTradeRow(TypedDict):
    """Read projection for backtest_trades."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    run_public_id: str
    executed_at: datetime
    instrument: str
    side: str
    quantity: float
    price: float
    fee: float
    pnl: float | None
    position_after: float
    signal_public_id: str | None


class BacktestEquityPointInsertRow(TypedDict):
    """Insert payload for backtest_equity_points."""

    run_public_id: str
    point_time: datetime
    equity: float
    cash: float
    position_value: float
    drawdown: float
    session_id: str
    sequence_id: int
    timestamp: datetime


class BacktestEquityPointRow(TypedDict):
    """Read projection for backtest_equity_points."""

    public_id: str
    timestamp: datetime
    session_id: str
    sequence_id: int
    run_public_id: str
    point_time: datetime
    equity: float
    cash: float
    position_value: float
    drawdown: float
