"""Market data and trading event schemas for ZMQ messaging.

This module defines Pydantic models representing market data structures
(ticks, candles, trades) and trading events (signals, fills, order status).
These schemas are embedded in message envelopes for inter-process communication.

Classes:
    TickData: Real-time bid/ask/last price snapshot.
    CandleData: OHLCV bar data for a specific timeframe.
    TradeData: Individual trade execution data.
    SignalData: Trading signal with direction and strength.
    FillData: Order fill/execution details.
    OrderStatusData: Current order state and fill progress.
"""

from datetime import datetime

from pydantic import BaseModel
from pydantic import Field

from snapper.core.types import OrderEventType
from snapper.interface.websocket.schemas import FillStatus
from snapper.interface.websocket.schemas import OrderType
from snapper.interface.websocket.schemas import TradeSide


class TickData(BaseModel):
    """Real-time price tick snapshot from an exchange.

    Represents a point-in-time snapshot of bid/ask prices and last trade.
    Used for real-time price monitoring and spread calculations.

    Attributes:
        instrument: Trading pair symbol (e.g., 'BTC-USD').
        volume: Trading volume for the current period.
        bid: Best bid price (highest buy order).
        ask: Best ask price (lowest sell order).
        last: Last traded price.
    """

    instrument: str
    volume: float
    bid: float | None = None
    ask: float | None = None
    last: float | None = None


class CandleData(BaseModel):
    """OHLCV candlestick bar data for technical analysis.

    Represents aggregated price action over a specific timeframe.
    Used by strategies for pattern recognition and indicator calculation.

    Attributes:
        instrument: Trading pair symbol (e.g., 'BTC-USD').
        timeframe: Bar duration (e.g., '1m', '1h', '1d').
        open: Opening price of the bar.
        high: Highest price during the bar.
        low: Lowest price during the bar.
        close: Closing price of the bar.
        volume: Total traded volume during the bar.
        vwap: Volume-weighted average price (optional).
        trades: Number of trades in the bar (optional).
    """

    instrument: str
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None = None
    trades: int | None = None


class TradeData(BaseModel):
    """Individual trade execution from the market.

    Represents a single trade that occurred on the exchange.
    Used for trade tape analysis and market activity monitoring.

    Attributes:
        instrument: Trading pair symbol (e.g., 'BTC-USD').
        price: Execution price of the trade.
        volume: Size of the trade.
        side: Trade direction ('buy'/'sell') if available.
    """

    instrument: str
    price: float
    volume: float
    side: str | None = None


class SignalData(BaseModel):
    """Trading signal generated by a strategy.

    Represents a recommendation to enter or exit a position.
    Signals are published to the messaging bus for execution.

    Attributes:
        instrument: Target trading pair symbol.
        side: Recommended direction ('buy' or 'sell').
        strength: Signal confidence from 0.0 (weak) to 1.0 (strong).
        reason: Human-readable explanation for the signal.
        price: Suggested entry/exit price (optional).
        strategy_name: Name of the generating strategy (optional).
    """

    instrument: str
    side: TradeSide
    strength: float = Field(ge=0.0, le=1.0)
    reason: str
    price: float | None = None
    strategy_name: str | None = None


class FillData(BaseModel):
    """Order fill/execution details from an exchange.

    Represents a completed or partial fill of an order.
    Contains all information needed for trade tracking and P&L calculation.

    Attributes:
        trade_id: Unique fill/trade ID from exchange (e.g., Kraken exec_id).
            May be None for exchanges that don't provide it.
        exchange_order_id: Exchange-assigned order ID (e.g., Kraken txid).
            May be None if exchange hasn't assigned an ID yet.
        client_order_id: Our generated order ID (e.g., 'signal-a1b2c3d4').
        instrument: Trading pair symbol.
        exchange: Exchange where the fill occurred.
        side: Trade direction ('buy' or 'sell').
        size: Filled quantity.
        price: Execution price.
        fee: Transaction fee charged.
        fee_asset: Currency of the fee (e.g., 'USD', 'BTC').
        status: Fill status ('filled', 'partial', etc.).
        executed_at: Timestamp of the fill.
    """

    trade_id: str | None = None
    exchange_order_id: str | None = None
    client_order_id: str
    instrument: str
    exchange: str
    side: TradeSide
    size: float
    price: float
    fee: float
    fee_asset: str
    status: FillStatus
    executed_at: datetime


class OrderStatusData(BaseModel):
    """Current state of an order for ZMQ event publishing (non-fill events).

    Published on orders.events.{exchange}.{instrument}.{status} topics.
    Note: Fill events use FillEnvelope, NOT this class.

    INVARIANT: The 'status' field MUST match the topic suffix.
    For example, if published to orders.events.kraken.BTC-USD.submitted,
    then status MUST be 'submitted'. This ensures consistency between
    topic-based routing and payload-based processing.

    Payload separation:
        - orders.events.*.*.fill -> FillEnvelope (FillStatus)
        - orders.events.*.*.{other} -> OrderStatusEnvelope (OrderEventType)

    Attributes:
        exchange_order_id: Exchange-assigned order ID (e.g., Kraken txid).
            May be None before exchange ACK (e.g., for 'submitted' event).
        client_order_id: Our generated order ID (e.g., 'signal-a1b2c3d4').
        instrument: Trading pair symbol.
        exchange: Exchange where the order is placed.
        side: Order direction ('buy' or 'sell').
        status: Event type matching topic suffix (OrderEventType, excludes 'fill').
        order_type: Type of order ('market', 'limit', etc.).
        size: Total order size.
        filled_size: Amount filled so far.
        price: Limit price (for limit orders).
        average_price: Average fill price (for partial fills).
        reason: Optional rejection/failure reason (for 'rejected' status).
        created_at: Order creation timestamp.
        updated_at: Last status update timestamp.
    """

    exchange_order_id: str | None = None
    client_order_id: str
    instrument: str
    exchange: str
    side: TradeSide
    status: OrderEventType
    order_type: OrderType
    size: float
    filled_size: float
    price: float | None = None
    average_price: float | None = None
    reason: str | None = None
    created_at: datetime
    updated_at: datetime | None = None
