"""Signal storage and retrieval service.

Provides persistence and querying of trading signals generated by strategies.
"""

from datetime import UTC
from datetime import datetime
from datetime import timedelta
from typing import Any

from loguru import logger
from sqlalchemy import and_
from sqlalchemy import desc
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError

from snapper.config.settings import get_settings
from snapper.data.models import Instrument
from snapper.data.models import Signal
from snapper.data.repository import get_repository
from snapper.infrastructure.symbols.functions import resolve_symbol_public_id
from snapper.strategies.base import StrategySignal


class SignalReadService:
    """Service for storing and retrieving trading signals."""

    def __init__(self) -> None:
        """Initialize the instance."""
        self.settings = get_settings()
        self.repo = get_repository(self.settings.db_url)

    async def store_signal(
        self,
        signal: StrategySignal,
        exchange: str,
        strategy_name: str | None = None,
        price: float | None = None,
    ) -> str:
        """Store a trading signal in the database.

        Args:
            signal: Signal object with instrument, side, and strength.
            exchange: Exchange where the signal was generated.
            strategy_name: Name of the strategy that generated the signal.
            price: Current price at signal generation time.

        Returns:
            Signal event UUID or empty string on error.
        """
        try:
            async with self.repo.session() as session:
                inst_query = await session.execute(
                    select(Instrument).where(
                        and_(
                            Instrument.symbol == signal.instrument,
                            Instrument.exchange == exchange,
                        )
                    )
                )
                inst = inst_query.scalars().first()
                if not inst:
                    parts = (
                        signal.instrument.split("-")
                        if "-" in signal.instrument
                        else [signal.instrument]
                    )
                    base = parts[0]
                    quote = parts[1] if len(parts) > 1 else "USD"
                    symbol_pid = await resolve_symbol_public_id(self.repo, signal.instrument)
                    if symbol_pid is None:
                        logger.error(f"No active Symbol row for {signal.instrument}")
                        return ""
                    inst_id = await self.repo.upsert_instrument(
                        symbol_public_id=symbol_pid,
                        symbol=signal.instrument,
                        exchange=exchange,
                        base=base,
                        quote=quote,
                        tick_size=0.01,
                        lot_size=0.0001,
                    )
                else:
                    inst_id = inst.id
                signal_event = Signal(
                    instrument_id=inst_id,
                    timestamp=datetime.now(UTC),
                    fired_at=signal.timestamp or datetime.now(UTC),
                    side=signal.side,
                    strength=signal.strength,
                    reason=signal.reason,
                    strategy_name=strategy_name,
                    price=price,
                )
                session.add(signal_event)
                await session.commit()
                await session.refresh(signal_event)
                return signal_event.public_id
        except SQLAlchemyError as e:
            logger.error(f"Error storing signal: {e}")
            return ""

    async def get_recent_signals(
        self,
        instrument: str | None = None,
        strategy: str | None = None,
        exchange: str | None = None,
        hours: int = 24,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Retrieve recent trading signals from the database.

        Args:
            instrument: Filter by instrument symbol.
            strategy: Filter by strategy name.
            exchange: Filter by exchange name.
            hours: Look back period in hours.
            limit: Maximum number of signals to return.

        Returns:
            List of signal dicts with instrument, timestamp, side, etc.
        """
        try:
            async with self.repo.session() as session:
                now = datetime.now(UTC)
                since = now - timedelta(hours=hours)
                query = select(Signal, Instrument).join(Instrument)
                query = query.where(Signal.fired_at >= since)
                query = query.where(Signal.timestamp <= now, Signal.known_to > now)
                if instrument:
                    query = query.where(Instrument.symbol == instrument)
                if strategy:
                    query = query.where(Signal.strategy_name == strategy)
                if exchange:
                    query = query.where(Instrument.exchange == exchange)
                query = query.order_by(desc(Signal.fired_at)).limit(limit)
                result = await session.execute(query)
                signals_with_instruments = result.all()
                return [
                    {
                        "public_id": signal.public_id,
                        "instrument": inst.symbol,
                        "exchange": inst.exchange,
                        "timestamp": signal.timestamp,
                        "fired_at": signal.fired_at,
                        "side": signal.side,
                        "strength": signal.strength,
                        "reason": signal.reason,
                        "strategy_name": signal.strategy_name,
                        "price": signal.price,
                    }
                    for signal, inst in signals_with_instruments
                ]
        except SQLAlchemyError as e:
            logger.error(f"Error retrieving signals: {e}")
            return []


signal_service = SignalReadService()
