"""Signal storage and retrieval service.

Provides persistence and querying of trading signals generated by strategies.
"""

from datetime import UTC
from datetime import datetime
from datetime import timedelta
from typing import Any

from loguru import logger
from sqlalchemy import and_
from sqlalchemy import desc
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError

from snapper.config.settings import get_settings
from snapper.data.models import Instrument
from snapper.data.models import Signal
from snapper.data.models import Symbol
from snapper.data.repository import get_repository
from snapper.data.repository import where_active
from snapper.infrastructure.symbols.functions import resolve_symbol_public_id
from snapper.messaging.infrastructure.publisher import SequenceTracker
from snapper.strategies.models import StrategySignal


class SignalReadService:
    """Service for storing and retrieving trading signals."""

    def __init__(self) -> None:
        """Initialize the instance."""
        self.settings = get_settings()
        self.repo = get_repository(self.settings.db_url)

    async def _resolve_instrument(
        self,
        signal: StrategySignal,
        exchange: str,
        tracker: SequenceTracker,
    ) -> str | None:
        """Look up or lazily create the instrument row for a signal.

        Args:
            signal: Signal carrying the instrument symbol.
            exchange: Exchange name to look up / create for.
            tracker: SequenceTracker for provenance on upsert.

        Returns:
            The instrument_public_id string, or ``None`` when the symbol
            cannot be resolved.
        """
        async with self.repo.session() as session:
            s_ts, s_kt = where_active(Symbol)
            sym_query = await session.execute(
                select(Symbol).where(
                    Symbol.native_symbol == signal.instrument,
                    s_ts,
                    s_kt,
                )
            )
            sym = sym_query.scalars().first()
            if sym is None:
                logger.error(f"No active Symbol row for {signal.instrument}")
                return None
            i_ts, i_kt = where_active(Instrument)
            inst_query = await session.execute(
                select(Instrument).where(
                    Instrument.symbol_public_id == sym.public_id,
                    Instrument.exchange == exchange,
                    i_ts,
                    i_kt,
                )
            )
            inst = inst_query.scalars().first()
        if inst:
            return str(inst.public_id)
        symbol_pid = await resolve_symbol_public_id(self.repo, signal.instrument)
        if symbol_pid is None:
            logger.error(f"No active Symbol row for {signal.instrument}")
            return None
        _id, public_id = await self.repo.upsert_instrument(
            symbol_public_id=symbol_pid,
            exchange=exchange,
            session_id=tracker.session_id,
            sequence_id=tracker.next_sequence("instruments"),
        )
        return public_id

    async def store_signal(
        self,
        signal: StrategySignal,
        exchange: str,
        session_id: str,
        sequence_id: int,
        tracker: SequenceTracker,
        strategy_name: str | None = None,
        price: float | None = None,
        public_id: str | None = None,
        timestamp: datetime | None = None,
    ) -> str:
        """Store a trading signal in the database.

        Args:
            signal: Signal object with instrument, side, and strength.
            exchange: Exchange where the signal was generated.
            strategy_name: Name of the strategy that generated the signal.
            price: Current price at signal generation time.
            session_id: Producer session UUID for provenance tracking.
            sequence_id: Sequence number within the producer session.
            public_id: Stable public identity from the published envelope.
                When provided, the DB row carries the same public_id as the
                WS/ZMQ message so REST and WS represent the same event.
            timestamp: Known-at time from the published envelope.
            tracker: Strategy-owned SequenceTracker used when a lazy
                instrument upsert is needed. Keeps the instrument row in
                the same session as the owning strategy component.

        Returns:
            Signal event UUID or empty string on error.
        """
        try:
            inst_public_id = await self._resolve_instrument(signal, exchange, tracker)
            if inst_public_id is None:
                return ""
            async with self.repo.session() as session:
                init_kwargs: dict[str, Any] = {
                    "instrument_public_id": inst_public_id,
                    "timestamp": timestamp or datetime.now(UTC),
                    "fired_at": signal.timestamp or datetime.now(UTC),
                    "side": signal.side,
                    "strength": signal.strength,
                    "reason": signal.reason,
                    "strategy_name": strategy_name,
                    "price": price,
                    "session_id": session_id,
                    "sequence_id": sequence_id,
                }
                if public_id is not None:
                    init_kwargs["public_id"] = public_id
                signal_event = Signal(**init_kwargs)
                session.add(signal_event)
                await session.commit()
                await session.refresh(signal_event)
                return signal_event.public_id
        except SQLAlchemyError as e:
            logger.error(f"Error storing signal: {e}")
            return ""

    async def get_recent_signals(
        self,
        instrument: str | None = None,
        strategy: str | None = None,
        exchange: str | None = None,
        hours: int = 24,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Retrieve recent trading signals from the database.

        Args:
            instrument: Filter by instrument symbol.
            strategy: Filter by strategy name.
            exchange: Filter by exchange name.
            hours: Look back period in hours.
            limit: Maximum number of signals to return.

        Returns:
            List of signal dicts with instrument, timestamp, side, etc.
        """
        try:
            async with self.repo.session() as session:
                now = datetime.now(UTC)
                since = now - timedelta(hours=hours)
                query = (
                    select(Signal, Instrument, Symbol)
                    .join(
                        Instrument,
                        and_(
                            Signal.instrument_public_id == Instrument.public_id,
                            *where_active(Instrument),
                        ),
                    )
                    .join(
                        Symbol,
                        and_(
                            Instrument.symbol_public_id == Symbol.public_id,
                            *where_active(Symbol),
                        ),
                    )
                )
                query = query.where(Signal.fired_at >= since)
                query = query.where(Signal.timestamp <= now, Signal.known_to > now)
                if instrument:
                    s_ts, s_kt = where_active(Symbol)
                    symbol_subq = (
                        select(Symbol.public_id)
                        .where(Symbol.native_symbol == instrument, s_ts, s_kt)
                        .scalar_subquery()
                    )
                    query = query.where(Instrument.symbol_public_id == symbol_subq)
                if strategy:
                    query = query.where(Signal.strategy_name == strategy)
                if exchange:
                    query = query.where(Instrument.exchange == exchange)
                query = query.order_by(desc(Signal.fired_at)).limit(limit)
                result = await session.execute(query)
                signals_with_instruments = result.all()
                return [
                    {
                        "public_id": signal.public_id,
                        "instrument": symbol.native_symbol,
                        "exchange": inst.exchange,
                        "timestamp": signal.timestamp,
                        "fired_at": signal.fired_at,
                        "side": signal.side,
                        "strength": signal.strength,
                        "reason": signal.reason,
                        "strategy_name": signal.strategy_name,
                        "price": signal.price,
                    }
                    for signal, inst, symbol in signals_with_instruments
                ]
        except SQLAlchemyError as e:
            logger.error(f"Error retrieving signals: {e}")
            return []


signal_service = SignalReadService()
