/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/snapper/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and create session.
         *
         *     Sets access_token, refresh_token, and csrf_token cookies.
         *
         *     Args:
         *         request: FastAPI request.
         *         response: FastAPI response for setting cookies.
         *         login_data: Login credentials.
         *
         *     Returns:
         *         LoginResponse with user profile.
         *
         *     Raises:
         *         HTTPException: 401 if credentials invalid.
         */
        post: operations["login_snapper_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh session tokens.
         *
         *     Generates new access/refresh tokens and WebSocket token.
         *
         *     Args:
         *         request: FastAPI request with refresh_token cookie.
         *         response: FastAPI response for setting cookies.
         *
         *     Returns:
         *         RefreshResponse with new tokens and user profile.
         *
         *     Raises:
         *         HTTPException: 401 if refresh token invalid.
         */
        post: operations["refresh_token_snapper_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get profile information for the currently authenticated user.
         *
         *     Args:
         *         current_user: Authenticated user from dependency.
         *
         *     Returns:
         *         Current user's UserProfile.
         */
        get: operations["get_current_user_info_snapper_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout and invalidate session.
         *
         *     Clears all authentication cookies and invalidates tokens.
         *
         *     Args:
         *         request: FastAPI request.
         *         response: FastAPI response for clearing cookies.
         *
         *     Returns:
         *         MessageResponse confirming logout.
         */
        post: operations["logout_snapper_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description List all users in the system.
         *
         *     Args:
         *         current_user: Authenticated user with MANAGE_USERS permission.
         *         include_inactive: Whether to include deactivated users.
         *
         *     Returns:
         *         List of user profiles with total count.
         */
        get: operations["get_users_snapper_api_auth_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a new user account.
         *
         *     Args:
         *         user_data: User creation payload with username, password, etc.
         *         current_user: Authenticated user with MANAGE_USERS permission.
         *
         *     Returns:
         *         Created user profile.
         *
         *     Raises:
         *         HTTPException: If user creation fails.
         */
        post: operations["create_user_snapper_api_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User
         * @description Update an existing user's profile.
         *
         *     Args:
         *         user_id: Target user ID.
         *         user_data: Update payload with optional email, role, is_active.
         *         current_user: Authenticated user with MANAGE_USERS permission.
         *
         *     Returns:
         *         Updated user profile.
         *
         *     Raises:
         *         HTTPException: If user not found.
         */
        put: operations["update_user_snapper_api_auth_users__user_id__put"];
        post?: never;
        /**
         * Delete User
         * @description Deactivate a user account.
         *
         *     Args:
         *         user_id: Target user ID to deactivate.
         *         current_user: Authenticated user with MANAGE_USERS permission.
         *
         *     Returns:
         *         Success message.
         *
         *     Raises:
         *         HTTPException: If user not found or trying to delete self.
         */
        delete: operations["delete_user_snapper_api_auth_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/users/{user_id}/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change User Password
         * @description Change a user's password.
         *
         *     Users can change their own password. Admins can change any password.
         *
         *     Args:
         *         user_id: Target user ID.
         *         password_data: Current and new password.
         *         current_user: Authenticated user.
         *
         *     Returns:
         *         Success message.
         *
         *     Raises:
         *         HTTPException: If forbidden or invalid current password.
         */
        post: operations["change_user_password_snapper_api_auth_users__user_id__change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/auth/users/{user_id}/admin-reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Reset User Password
         * @description Admin endpoint to reset a user's password without current password.
         *
         *     Args:
         *         user_id: Target user ID.
         *         password_data: New password.
         *         current_user: Admin user with MANAGE_USERS permission.
         *
         *     Returns:
         *         Success message.
         *
         *     Raises:
         *         HTTPException: If forbidden or user not found.
         */
        post: operations["admin_reset_user_password_snapper_api_auth_users__user_id__admin_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Settings
         * @description Retrieve all application settings, optionally filtered by category.
         *
         *     Args:
         *         category: Optional category name to filter settings.
         *         user: Authenticated user with CONFIGURE_SYSTEM permission.
         *
         *     Returns:
         *         List of all settings matching the filter criteria.
         */
        get: operations["get_all_settings_snapper_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/settings/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setting Categories
         * @description Retrieve all distinct setting category names.
         *
         *     Args:
         *         user: Authenticated user with CONFIGURE_SYSTEM permission.
         *
         *     Returns:
         *         Response containing sorted list of category names.
         */
        get: operations["get_setting_categories_snapper_api_settings_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Setting
         * @description Update or create a setting by key.
         *
         *     Args:
         *         key: The setting key to update or create.
         *         request: Setting update payload with value and metadata.
         *         user: Authenticated user with CONFIGURE_SYSTEM permission.
         *
         *     Returns:
         *         The updated setting.
         *
         *     Raises:
         *         HTTPException: If setting not found after update.
         */
        put: operations["update_setting_snapper_api_settings__key__put"];
        post?: never;
        /**
         * Delete Setting
         * @description Delete a setting by key.
         *
         *     Args:
         *         key: The setting key to delete.
         *         user: Authenticated user with CONFIGURE_SYSTEM permission.
         *
         *     Returns:
         *         Success message confirming deletion.
         *
         *     Raises:
         *         HTTPException: If setting not found.
         */
        delete: operations["delete_setting_snapper_api_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Available Processes */
        get: operations["list_available_processes_snapper_api_processes_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/configured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configured Processes */
        get: operations["list_configured_processes_snapper_api_processes_configured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Process Configuration
         * @description Create a new process configuration from a template.
         *
         *     Args:
         *         request: Process creation request with template name and config.
         *         factory: Process launcher service.
         *         settings: Application settings.
         *         _user: Authenticated user with MANAGE_PROCESSES permission.
         *         _csrf: CSRF token validation.
         *
         *     Returns:
         *         Process creation response with status.
         *
         *     Raises:
         *         HTTPException: If template not found or name already exists.
         */
        post: operations["create_process_configuration_snapper_api_processes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/schema/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Process Schema
         * @description Get the configuration schema for a registered process.
         *
         *     Args:
         *         name: Process name from registry.
         *         settings: Application settings.
         *         _user: Authenticated user with MANAGE_PROCESSES permission.
         *
         *     Returns:
         *         Schema response with defaults and configuration options.
         *
         *     Raises:
         *         HTTPException: If process not found in registry.
         */
        get: operations["get_process_schema_snapper_api_processes_schema__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Process */
        post: operations["start_process_snapper_api_processes__name__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Process */
        post: operations["stop_process_snapper_api_processes__name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/processes/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Process Runs */
        get: operations["list_process_runs_snapper_api_processes_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_snapper_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candles */
        get: operations["get_candles_snapper_api_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders */
        get: operations["get_orders_snapper_api_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Signals */
        get: operations["get_signals_snapper_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Executions */
        get: operations["get_executions_snapper_api_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_snapper_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/ws/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Websocket Stats */
        get: operations["websocket_stats_snapper_api_ws_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/zmq/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zmq Health Check */
        get: operations["zmq_health_check_snapper_api_zmq_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapper/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Status */
        get: operations["get_system_status_snapper_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminResetPasswordRequest
         * @description Admin password reset request schema.
         *
         *     Used by admins to reset another user's password
         *     without knowing the current password.
         *
         *     Attributes:
         *         new_password: New password to set (min 8 chars).
         */
        AdminResetPasswordRequest: {
            /** New Password */
            new_password: string;
        };
        /**
         * AvailableProcess
         * @description Available process template response schema.
         *
         *     Describes a registered process that can be instantiated.
         *
         *     Attributes:
         *         name: Process identifier.
         *         class_path: Full Python class path.
         *         method: Entry point method name.
         *         description: Human-readable description.
         *         lifecycle: Process lifecycle type (long_running/one_shot).
         *         role: Process role category.
         *         tags: Categorization tags.
         *         parameters_schema: JSON Schema for parameters.
         */
        AvailableProcess: {
            /**
             * Name
             * @description Process identifier
             */
            name: string;
            /**
             * Class Path
             * @description Full Python class path
             */
            class_path: string;
            /**
             * Method
             * @description Entry point method name
             */
            method: string;
            /**
             * Description
             * @description Human-readable description
             */
            description: string;
            /**
             * Lifecycle
             * @description Process lifecycle type
             * @enum {string}
             */
            lifecycle: "long_running" | "one_shot";
            /**
             * Role
             * @description Process role category
             * @enum {string}
             */
            role: "core" | "task" | "strategy" | "backtest";
            /**
             * Tags
             * @description Categorization tags
             */
            tags?: string[];
            /**
             * Parameters Schema
             * @description JSON Schema for parameters
             */
            parameters_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AvailableProcessesResponse
         * @description Available processes list response schema.
         *
         *     Attributes:
         *         processes: List of available process templates.
         *         count: Total number of available processes.
         */
        AvailableProcessesResponse: {
            /** Processes */
            processes: components["schemas"]["AvailableProcess"][];
            /** Count */
            count: number;
        };
        /**
         * CandleSnapshot
         * @description OHLCV candle snapshot response schema.
         *
         *     Represents a single candlestick data point.
         *
         *     Attributes:
         *         instrument: Trading instrument symbol.
         *         timeframe: Candle timeframe (e.g., '1m', '1h', '1d').
         *         timestamp: Candle open timestamp.
         *         open: Opening price.
         *         high: Highest price in the period.
         *         low: Lowest price in the period.
         *         close: Closing price.
         *         volume: Trading volume.
         *         vwap: Volume-weighted average price (optional).
         *         trades: Number of trades in the period (optional).
         */
        CandleSnapshot: {
            /** Instrument */
            instrument: string;
            /** Timeframe */
            timeframe: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Vwap */
            vwap?: number | null;
            /** Trades */
            trades?: number | null;
        };
        /**
         * ChangePasswordRequest
         * @description Change password request schema.
         *
         *     Used by authenticated users to change their own password.
         *
         *     Attributes:
         *         current_password: Current password for verification.
         *         new_password: New password (min 8 chars).
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ConfiguredProcess
         * @description Configured process response schema.
         *
         *     Describes a process configuration with its current runtime state.
         *
         *     Attributes:
         *         name: Unique process name.
         *         enabled: Whether process autostarts on boot.
         *         running: Whether process is currently running.
         *         mode: Execution mode (thread/process).
         *         class_path: Full Python class path.
         *         method: Entry point method name.
         *         args: Constructor arguments.
         *         kwargs: Constructor keyword arguments.
         *         note: Optional note.
         *         lifecycle: Process lifecycle type.
         *         role: Process role category.
         *         tags: Categorization tags.
         *         parameters_schema: JSON Schema for parameters.
         *         is_one_shot: Whether process is one-shot task.
         *         active_run_id: Active run ID if running.
         */
        ConfiguredProcess: {
            /**
             * Name
             * @description Unique process name
             */
            name: string;
            /**
             * Enabled
             * @description Whether process autostarts on boot
             */
            enabled: boolean;
            /**
             * Running
             * @description Whether process is currently running
             */
            running: boolean;
            /**
             * Mode
             * @description Execution mode (thread/process)
             */
            mode: string;
            /**
             * Class Path
             * @description Full Python class path
             */
            class_path: string;
            /**
             * Method
             * @description Entry point method name
             */
            method: string;
            /**
             * Args
             * @description Constructor arguments
             */
            args?: unknown[];
            /**
             * Kwargs
             * @description Constructor kwargs
             */
            kwargs?: {
                [key: string]: unknown;
            };
            /**
             * Note
             * @description Optional note
             */
            note?: string | null;
            /**
             * Lifecycle
             * @description Process lifecycle type
             * @enum {string}
             */
            lifecycle: "long_running" | "one_shot";
            /**
             * Role
             * @description Process role category
             * @enum {string}
             */
            role: "core" | "task" | "strategy" | "backtest";
            /**
             * Tags
             * @description Categorization tags
             */
            tags?: string[];
            /**
             * Parameters Schema
             * @description JSON Schema for parameters
             */
            parameters_schema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Is One Shot
             * @description Whether process is one-shot task
             */
            is_one_shot: boolean;
            /**
             * Active Run Id
             * @description Active run ID if running
             */
            active_run_id?: string | null;
        };
        /**
         * ConfiguredProcessesResponse
         * @description Configured processes list response schema.
         *
         *     Attributes:
         *         processes: List of configured processes.
         *         count: Total number of configured processes.
         */
        ConfiguredProcessesResponse: {
            /** Processes */
            processes: components["schemas"]["ConfiguredProcess"][];
            /** Count */
            count: number;
        };
        /**
         * CreateUserRequest
         * @description Create user request schema.
         *
         *     Attributes:
         *         username: Unique username (3-64 chars).
         *         email: Optional email address.
         *         password: Password (min 8 chars).
         *         role: User role to assign.
         *         is_active: Whether account is active.
         */
        CreateUserRequest: {
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * ExecutionRecord
         * @description Trade execution record response schema.
         *
         *     Represents a single trade execution (fill) from an order.
         *
         *     Attributes:
         *         id: Unique execution identifier.
         *         order_id: Related order identifier.
         *         timestamp: Execution timestamp.
         *         price: Execution price.
         *         size: Executed quantity.
         *         fee: Transaction fee.
         *         fee_asset: Currency of the fee.
         *         instrument: Trading instrument symbol.
         *         side: Trade side (buy/sell).
         *         exchange: Exchange name (empty string if not specified).
         */
        ExecutionRecord: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Price */
            price: number;
            /** Size */
            size: number;
            /** Fee */
            fee: number;
            /** Fee Asset */
            fee_asset: string;
            /** Instrument */
            instrument: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Exchange
             * @default
             */
            exchange: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Main health check endpoint response.
         *
         *     Provides overall service health status including version,
         *     connection statistics, and topic availability.
         *
         *     Attributes:
         *         status: Overall service health status (healthy/unhealthy).
         *         timestamp: Timestamp of the health check.
         *         version: Application version string.
         *         connections: Connection statistics dictionary.
         *         topics: Topic availability information.
         */
        HealthCheckResponse: {
            /**
             * Status
             * @description Overall service health status
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the health check
             */
            timestamp: string;
            /**
             * Version
             * @description Application version
             */
            version: string;
            /**
             * Connections
             * @description Connection statistics
             */
            connections: {
                [key: string]: unknown;
            };
            /** @description Topics availability */
            topics: components["schemas"]["HealthTopics"];
        };
        /**
         * HealthTopics
         * @description Topic availability statistics.
         *
         *     Attributes:
         *         available: Total number of available topics.
         *         active: Number of currently active topics with subscribers.
         */
        HealthTopics: {
            /**
             * Available
             * @description Total number of available topics
             */
            available: number;
            /**
             * Active
             * @description Number of currently active topics
             */
            active: number;
        };
        /**
         * LoginRequest
         * @description Login request schema.
         *
         *     Attributes:
         *         username: User's login name.
         *         password: User's password.
         *         remember_me: If True, extends refresh token lifetime.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /**
         * LoginResponse
         * @description Login response schema.
         *
         *     Returned after successful authentication.
         *
         *     Attributes:
         *         message: Success message.
         *         expires_in: Access token TTL in seconds.
         *         user: Authenticated user profile.
         */
        LoginResponse: {
            /** Message */
            message: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserProfile"];
        };
        /**
         * MessageResponse
         * @description Generic API response containing a single message.
         *
         *     Used for simple acknowledgment responses.
         *
         *     Attributes:
         *         message: Human-readable response message.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * OrderStatus
         * @description Order status response schema.
         *
         *     Represents the current state of a trading order.
         *
         *     Attributes:
         *         id: Unique internal order identifier.
         *         instrument: Trading instrument symbol.
         *         exchange: Exchange name (empty string if not specified).
         *         client_order_id: Client-assigned order ID.
         *         exchange_order_id: Exchange-assigned order ID.
         *         created_at: Order creation timestamp.
         *         updated_at: Last update timestamp.
         *         side: Order side (buy/sell).
         *         type: Order type (market/limit).
         *         price: Limit price (None for market orders).
         *         size: Order quantity.
         *         status: Current order status.
         *         time_in_force: Order time-in-force setting.
         *         error: Error message if order failed.
         */
        OrderStatus: {
            /** Id */
            id: number;
            /** Instrument */
            instrument: string;
            /**
             * Exchange
             * @default
             */
            exchange: string;
            /** Client Order Id */
            client_order_id: string | null;
            /** Exchange Order Id */
            exchange_order_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Type
             * @enum {string}
             */
            type: "market" | "limit" | "stop" | "stop_limit";
            /** Price */
            price: number | null;
            /** Size */
            size: number;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "submitted" | "open" | "filled" | "partially_filled" | "cancelled" | "rejected";
            /** Time In Force */
            time_in_force?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * PositionSnapshot
         * @description Portfolio position snapshot response schema.
         *
         *     Represents a snapshot of a single position in the portfolio.
         *
         *     Attributes:
         *         id: Unique position identifier.
         *         instrument: Trading instrument symbol.
         *         exchange: Exchange name (empty string if not specified).
         *         quantity: Position size (positive for long, negative for short).
         *         average_price: Average entry price.
         *         unrealized_pnl: Unrealized profit/loss.
         *         realized_pnl: Realized profit/loss.
         *         updated_at: Last update timestamp.
         */
        PositionSnapshot: {
            /** Id */
            id: number;
            /** Instrument */
            instrument: string;
            /**
             * Exchange
             * @default
             */
            exchange: string;
            /** Quantity */
            quantity: number;
            /** Average Price */
            average_price: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Realized Pnl */
            realized_pnl: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProcessCreateRequest
         * @description Process creation request schema.
         *
         *     Used to create a new process configuration from a template.
         *
         *     Attributes:
         *         name: Unique process name (lowercase alphanumeric with underscores).
         *         template: Registered process identifier used as template.
         *         enabled: Whether process should autostart on boot.
         *         mode: Execution mode override (thread/process).
         *         args: Constructor positional arguments.
         *         kwargs: Constructor keyword arguments.
         *         note: Optional note stored alongside configuration.
         */
        ProcessCreateRequest: {
            /**
             * Name
             * @description Unique process name
             */
            name: string;
            /**
             * Template
             * @description Registered process identifier used as template
             */
            template: string;
            /**
             * Enabled
             * @description Whether process should autostart on boot
             */
            enabled?: boolean | null;
            /**
             * Mode
             * @description Execution mode override (thread/process)
             */
            mode?: string | null;
            /**
             * Args
             * @description Constructor positional arguments
             */
            args?: unknown[] | null;
            /**
             * Kwargs
             * @description Constructor keyword arguments
             */
            kwargs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Note
             * @description Optional note stored alongside configuration
             */
            note?: string | null;
        };
        /**
         * ProcessCreateResponse
         * @description Process creation response schema.
         *
         *     Attributes:
         *         status: Operation status ('created').
         *         process: Created process info.
         */
        ProcessCreateResponse: {
            /**
             * Status
             * @description Operation status
             * @constant
             */
            status: "created";
            /** @description Created process info */
            process: components["schemas"]["ProcessCreatedInfo"];
        };
        /**
         * ProcessCreatedInfo
         * @description Process creation info schema.
         *
         *     Attributes:
         *         name: Unique process name.
         *         template: Template used for creation.
         */
        ProcessCreatedInfo: {
            /**
             * Name
             * @description Unique process name
             */
            name: string;
            /**
             * Template
             * @description Template used for creation
             */
            template: string;
        };
        /**
         * ProcessRun
         * @description Process run record response schema.
         *
         *     Represents a single execution run of a process.
         *
         *     Attributes:
         *         run_id: Unique run identifier.
         *         process_name: Process name.
         *         status: Run status.
         *         role: Process role.
         *         lifecycle: Process lifecycle.
         *         parameters: Run parameters.
         *         result: Run result if completed.
         *         error: Error message if failed.
         *         tags: Process tags.
         *         started_at: Start time in ISO format.
         *         completed_at: Completion time if finished.
         */
        ProcessRun: {
            /**
             * Run Id
             * @description Unique run identifier
             */
            run_id: string;
            /**
             * Process Name
             * @description Process name
             */
            process_name: string;
            /**
             * Status
             * @description Run status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled";
            /**
             * Role
             * @description Process role
             * @enum {string}
             */
            role: "core" | "task" | "strategy" | "backtest";
            /**
             * Lifecycle
             * @description Process lifecycle
             * @enum {string}
             */
            lifecycle: "long_running" | "one_shot";
            /**
             * Parameters
             * @description Run parameters
             */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /**
             * Result
             * @description Run result if completed
             */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Error
             * @description Error message if failed
             */
            error?: string | null;
            /**
             * Tags
             * @description Process tags
             */
            tags?: string[];
            /**
             * Started At
             * @description Start time in ISO format
             */
            started_at: string;
            /**
             * Completed At
             * @description Completion time if finished
             */
            completed_at?: string | null;
        };
        /**
         * ProcessRunsResponse
         * @description Process runs list response schema.
         *
         *     Attributes:
         *         runs: List of process runs.
         *         count: Total number of runs.
         */
        ProcessRunsResponse: {
            /** Runs */
            runs: components["schemas"]["ProcessRun"][];
            /** Count */
            count: number;
        };
        /**
         * ProcessSchemaResponse
         * @description Process schema response.
         *
         *     Describes a process template schema with default values.
         *
         *     Attributes:
         *         name: Process identifier.
         *         description: Human-readable description.
         *         class_path: Full Python class path.
         *         method: Entry point method name.
         *         default_enabled: Default autostart setting.
         *         default_mode: Default execution mode.
         *         default_args: Default arguments.
         *         default_kwargs: Default keyword arguments.
         *         lifecycle: Process lifecycle type.
         */
        ProcessSchemaResponse: {
            /**
             * Name
             * @description Process identifier
             */
            name: string;
            /**
             * Description
             * @description Human-readable description
             */
            description: string;
            /**
             * Class Path
             * @description Full Python class path
             */
            class_path: string;
            /**
             * Method
             * @description Entry point method name
             */
            method: string;
            /**
             * Default Enabled
             * @description Default autostart setting
             */
            default_enabled: boolean;
            /**
             * Default Mode
             * @description Default execution mode
             */
            default_mode: string;
            /**
             * Default Args
             * @description Default arguments
             */
            default_args?: unknown[];
            /**
             * Default Kwargs
             * @description Default kwargs
             */
            default_kwargs?: {
                [key: string]: unknown;
            };
            /**
             * Lifecycle
             * @description Process lifecycle type
             * @enum {string}
             */
            lifecycle: "long_running" | "one_shot";
        };
        /**
         * ProcessStartRequest
         * @description Process start request schema.
         *
         *     Used to start a configured process with optional parameter overrides.
         *
         *     Attributes:
         *         mode: Execution mode (thread/process) override.
         *         args: Constructor positional arguments override.
         *         kwargs: Constructor keyword arguments override.
         *         autostart: Toggle autostart flag (None keeps stored value).
         */
        ProcessStartRequest: {
            /**
             * Mode
             * @description Execution mode (thread/process) - for ProcessLauncherService, not constructor
             * @example thread
             * @example process
             */
            mode?: string | null;
            /**
             * Args
             * @description Constructor positional arguments override
             * @example [
             *       "arg1",
             *       2,
             *       3
             *     ]
             */
            args?: unknown[] | null;
            /**
             * Kwargs
             * @description Constructor keyword arguments override
             * @example {
             *       "endpoint": "tcp://0.0.0.0:5555"
             *     }
             */
            kwargs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Autostart
             * @description Toggle autostart flag; None keeps stored value
             */
            autostart?: boolean | null;
        };
        /**
         * ProcessStartResponse
         * @description Process start response schema.
         *
         *     Attributes:
         *         status: Operation status (started, already_running, etc.).
         *         name: Process name.
         *         run_id: Run ID if started.
         *         message: Additional message.
         */
        ProcessStartResponse: {
            /**
             * Status
             * @description Operation status (started, already_running, etc.)
             */
            status: string;
            /**
             * Name
             * @description Process name
             */
            name: string;
            /**
             * Run Id
             * @description Run ID if started
             */
            run_id?: string | null;
            /**
             * Message
             * @description Additional message
             */
            message?: string | null;
        };
        /**
         * ProcessStatus
         * @description Process status response schema.
         *
         *     Represents the current status of a single process.
         *
         *     Attributes:
         *         status: Process status (not_running, running, stopped, completed, error).
         *         pid: Process ID if running.
         *         started_at: Start time in ISO format.
         *         command: Command that was executed.
         *         exit_code: Exit code if stopped.
         *         error: Error message if failed.
         */
        ProcessStatus: {
            /**
             * Status
             * @description Process status: not_running, running, stopped, completed, error
             */
            status: string;
            /**
             * Pid
             * @description Process ID if running
             */
            pid?: number | null;
            /**
             * Started At
             * @description Start time in ISO format
             */
            started_at?: string | null;
            /**
             * Command
             * @description Command that was executed
             */
            command?: string | null;
            /**
             * Exit Code
             * @description Exit code if stopped
             */
            exit_code?: number | null;
            /**
             * Error
             * @description Error message if failed
             */
            error?: string | null;
        };
        /**
         * ProcessStopResponse
         * @description Process stop response schema.
         *
         *     Attributes:
         *         status: Operation status (stopped, not_running, etc.).
         *         name: Process name.
         *         message: Additional message.
         */
        ProcessStopResponse: {
            /**
             * Status
             * @description Operation status (stopped, not_running, etc.)
             */
            status: string;
            /**
             * Name
             * @description Process name
             */
            name: string;
            /**
             * Message
             * @description Additional message
             */
            message?: string | null;
        };
        /**
         * RefreshResponse
         * @description Token refresh response schema.
         *
         *     Returned after successful token refresh.
         *
         *     Attributes:
         *         message: Success message.
         *         ws_token: New WebSocket authentication token.
         *         ws_token_exp: WebSocket token expiration time.
         *         csrf_token: New CSRF token.
         *         user: User profile.
         */
        RefreshResponse: {
            /** Message */
            message: string;
            /** Ws Token */
            ws_token: string;
            /**
             * Ws Token Exp
             * Format: date-time
             */
            ws_token_exp: string;
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["UserProfile"];
        };
        /**
         * SettingCategoriesResponse
         * @description Setting categories list response.
         *
         *     Attributes:
         *         categories: List of unique setting categories.
         */
        SettingCategoriesResponse: {
            /**
             * Categories
             * @description List of unique setting categories
             */
            categories: string[];
        };
        /**
         * SettingRead
         * @description Setting read response schema.
         *
         *     Returned when fetching a setting from the database.
         *
         *     Attributes:
         *         key: Unique setting key identifier.
         *         value: Setting value as string.
         *         category: Setting category for grouping.
         *         description: Optional human-readable description.
         *         updated_at: Last modification timestamp.
         *         updated_by: User who last modified the setting.
         */
        SettingRead: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Category */
            category: string;
            /** Description */
            description?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
        };
        /**
         * SettingUpdate
         * @description Setting update request schema.
         *
         *     Used when updating an existing setting.
         *
         *     Attributes:
         *         value: New setting value as string.
         *         category: Setting category (defaults to 'system').
         *         description: Optional description.
         */
        SettingUpdate: {
            /**
             * Value
             * @description Setting value as string
             */
            value: string;
            /**
             * Category
             * @description Setting category
             * @default system
             */
            category: string;
            /**
             * Description
             * @description Setting description
             */
            description?: string | null;
        };
        /**
         * SubscriptionsStats
         * @description Subscription statistics.
         *
         *     Attributes:
         *         per_topic: Subscriber count per topic.
         *         per_client: Topics subscribed per client.
         */
        SubscriptionsStats: {
            /**
             * Per Topic
             * @description Subscriber count per topic
             */
            per_topic: {
                [key: string]: number;
            };
            /**
             * Per Client
             * @description Topics subscribed per client
             */
            per_client: {
                [key: string]: string[];
            };
        };
        /**
         * SystemStatus
         * @description System-wide status response schema.
         *
         *     Provides status of the trader process, backtests, and active strategies.
         *
         *     Attributes:
         *         trader: Trader process status.
         *         backtests: Status of backtest processes by ID.
         *         strategies: List of active strategies from strategy_runner.
         */
        SystemStatus: {
            trader: components["schemas"]["ProcessStatus"];
            /** Backtests */
            backtests: {
                [key: string]: components["schemas"]["ProcessStatus"];
            };
            /**
             * Strategies
             * @description List of active strategies from strategy_runner
             */
            strategies?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TradingSignal
         * @description Trading signal response schema.
         *
         *     Represents a trading signal generated by a strategy.
         *
         *     Attributes:
         *         id: Unique signal identifier.
         *         instrument: Trading instrument symbol.
         *         exchange: Exchange name (empty string if not specified).
         *         timestamp: When the signal was generated.
         *         side: Trade direction (buy/sell).
         *         strength: Signal strength (0.0-1.0).
         *         reason: Human-readable reason for the signal.
         *         strategy_name: Name of the strategy that generated the signal.
         *         price: Target price for the trade (optional).
         */
        TradingSignal: {
            /** Id */
            id: number;
            /** Instrument */
            instrument: string;
            /**
             * Exchange
             * @default
             */
            exchange: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Strength */
            strength: number;
            /** Reason */
            reason: string;
            /** Strategy Name */
            strategy_name: string | null;
            /** Price */
            price: number | null;
        };
        /**
         * UpdateUserRequest
         * @description Update user request schema.
         *
         *     All fields are optional - only provided fields are updated.
         *
         *     Attributes:
         *         email: New email address.
         *         role: New role assignment.
         *         is_active: New active status.
         */
        UpdateUserRequest: {
            /** Email */
            email?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UserListResponse
         * @description User list response schema.
         *
         *     Returned by user listing endpoints.
         *
         *     Attributes:
         *         users: List of user profiles.
         *         total_count: Total number of users.
         */
        UserListResponse: {
            /** Users */
            users: components["schemas"]["UserProfile"][];
            /** Total Count */
            total_count: number;
        };
        /**
         * UserProfile
         * @description User profile schema.
         *
         *     Represents authenticated user information returned by API
         *     endpoints and stored in request state.
         *
         *     Attributes:
         *         id: Unique user identifier.
         *         username: User's login name.
         *         email: Optional email address.
         *         role: User's role (VIEWER, OPERATOR, ADMIN).
         *         is_active: Whether user account is active.
         *         created_at: Account creation timestamp.
         *         last_login: Last successful login timestamp.
         */
        UserProfile: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Last Login */
            last_login?: string | null;
        };
        /**
         * UserRole
         * @description User role enumeration.
         *
         *     Defines the available roles in the system with hierarchical
         *     access levels:
         *     - VIEWER: Read-only access to market data and positions
         *     - OPERATOR: Can execute trades and manage strategies
         *     - ADMIN: Full system access including user management
         * @enum {string}
         */
        UserRole: "viewer" | "operator" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebSocketStats
         * @description WebSocket connection statistics.
         *
         *     Attributes:
         *         active_connections: Number of active WebSocket connections.
         *         topic_subscribers: Subscriber count per topic.
         *         client_count: Total client count.
         */
        WebSocketStats: {
            /**
             * Active Connections
             * @description Number of active WebSocket connections
             */
            active_connections: number;
            /**
             * Topic Subscribers
             * @description Subscriber count per topic
             */
            topic_subscribers: {
                [key: string]: number;
            };
            /**
             * Client Count
             * @description Total client count
             */
            client_count: number;
        };
        /**
         * WsStatsConfig
         * @description WebSocket statistics configuration.
         *
         *     Attributes:
         *         broker_xpub: ZMQ broker XPUB endpoint address.
         *         heartbeat_interval_ms: Heartbeat interval in milliseconds.
         */
        WsStatsConfig: {
            /**
             * Broker Xpub
             * @description ZMQ broker XPUB endpoint
             */
            broker_xpub: string;
            /**
             * Heartbeat Interval Ms
             * @description Heartbeat interval in milliseconds
             */
            heartbeat_interval_ms: number;
        };
        /**
         * WsStatsResponse
         * @description WebSocket statistics endpoint response.
         *
         *     Comprehensive statistics about WebSocket connections, ZMQ bridge,
         *     and subscription state.
         *
         *     Attributes:
         *         websocket: WebSocket statistics.
         *         zmq_bridge: ZMQ bridge statistics.
         *         connections: Connection statistics.
         *         topics: Topic message statistics.
         *         subscriptions: Subscription details.
         *         config: Configuration details.
         */
        WsStatsResponse: {
            /** @description WebSocket statistics */
            websocket: components["schemas"]["WebSocketStats"];
            /** @description ZMQ bridge statistics */
            zmq_bridge: components["schemas"]["ZmqBridgeStats"];
            /**
             * Connections
             * @description Connection statistics
             */
            connections: {
                [key: string]: unknown;
            };
            /**
             * Topics
             * @description Topic message statistics
             */
            topics: {
                [key: string]: unknown;
            };
            /** @description Subscription details */
            subscriptions: components["schemas"]["SubscriptionsStats"];
            /** @description Configuration details */
            config: components["schemas"]["WsStatsConfig"];
        };
        /**
         * ZmqBridgeStats
         * @description ZMQ bridge statistics.
         *
         *     Attributes:
         *         active_topics: Number of active ZMQ topics.
         *         subscriber_tasks: Number of subscriber tasks.
         *         available_topics: List of available topics.
         */
        ZmqBridgeStats: {
            /**
             * Active Topics
             * @description Number of active ZMQ topics
             */
            active_topics: number;
            /**
             * Subscriber Tasks
             * @description Number of subscriber tasks
             */
            subscriber_tasks: number;
            /**
             * Available Topics
             * @description List of available topics
             */
            available_topics: string[];
        };
        /**
         * ZmqComponents
         * @description ZMQ infrastructure component status.
         *
         *     Attributes:
         *         zmq_context: ZMQ context status (active/inactive).
         *         websocket_manager: WebSocket manager status.
         *         active_connections: Number of active WebSocket connections.
         */
        ZmqComponents: {
            /**
             * Zmq Context
             * @description ZMQ context status
             */
            zmq_context: string;
            /**
             * Websocket Manager
             * @description WebSocket manager status
             */
            websocket_manager: string;
            /**
             * Active Connections
             * @description Number of active WebSocket connections
             */
            active_connections: number;
        };
        /**
         * ZmqConfig
         * @description ZMQ configuration information.
         *
         *     Attributes:
         *         available_topics: List of available ZMQ topics for subscription.
         */
        ZmqConfig: {
            /**
             * Available Topics
             * @description List of available ZMQ topics
             */
            available_topics: string[];
        };
        /**
         * ZmqHealthResponse
         * @description ZMQ bridge health check response.
         *
         *     Provides detailed status of the ZMQ-to-WebSocket bridge including
         *     component health, configuration, and message statistics.
         *
         *     Attributes:
         *         status: Overall ZMQ bridge health status.
         *         timestamp: Timestamp of the health check.
         *         components: Component status details.
         *         config: ZMQ configuration.
         *         connections: Connection statistics.
         *         message_stats: Message statistics per topic.
         *         errors: Error messages if unhealthy.
         */
        ZmqHealthResponse: {
            /**
             * Status
             * @description Overall ZMQ bridge health status
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the health check
             */
            timestamp: string;
            /** @description Component status details */
            components: components["schemas"]["ZmqComponents"];
            /** @description ZMQ configuration */
            config: components["schemas"]["ZmqConfig"];
            /**
             * Connections
             * @description Connection statistics
             */
            connections: {
                [key: string]: unknown;
            };
            /**
             * Message Stats
             * @description Message statistics per topic
             */
            message_stats: {
                [key: string]: unknown;
            };
            /**
             * Errors
             * @description Error messages if unhealthy
             */
            errors?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_snapper_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_snapper_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    get_current_user_info_snapper_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    logout_snapper_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_users_snapper_api_auth_users_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_snapper_api_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_snapper_api_auth_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_snapper_api_auth_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_password_snapper_api_auth_users__user_id__change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_reset_user_password_snapper_api_auth_users__user_id__admin_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_settings_snapper_api_settings_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setting_categories_snapper_api_settings_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingCategoriesResponse"];
                };
            };
        };
    };
    update_setting_snapper_api_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_setting_snapper_api_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_processes_snapper_api_processes_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableProcessesResponse"];
                };
            };
        };
    };
    list_configured_processes_snapper_api_processes_configured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguredProcessesResponse"];
                };
            };
        };
    };
    create_process_configuration_snapper_api_processes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_process_schema_snapper_api_processes_schema__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_process_snapper_api_processes__name__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_process_snapper_api_processes__name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_process_runs_snapper_api_processes_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_snapper_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    get_candles_snapper_api_candles_get: {
        parameters: {
            query: {
                /** @description Instrument symbol */
                instrument: string;
                /** @description Timeframe */
                timeframe: string;
                /** @description Number of candles to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_snapper_api_orders_get: {
        parameters: {
            query?: {
                /** @description Symbol to filter by */
                symbol?: string | null;
                /** @description Number of orders to return */
                limit?: number;
                /** @description Number of orders to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signals_snapper_api_signals_get: {
        parameters: {
            query?: {
                /** @description Filter by instrument */
                instrument?: string | null;
                /** @description Filter by strategy */
                strategy?: string | null;
                /** @description Hours of history to return */
                hours?: number;
                /** @description Number of signals to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingSignal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executions_snapper_api_executions_get: {
        parameters: {
            query?: {
                /** @description Number of executions to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_positions_snapper_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSnapshot"][];
                };
            };
        };
    };
    websocket_stats_snapper_api_ws_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsStatsResponse"];
                };
            };
        };
    };
    zmq_health_check_snapper_api_zmq_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZmqHealthResponse"];
                };
            };
        };
    };
    get_system_status_snapper_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
