export type { components, operations, paths } from './api.generated'
import type { components } from './api.generated'

export type CandleSnapshot = components['schemas']['CandleSnapshot']
export type OrderStatus = components['schemas']['OrderStatus']
export type ExecutionRecord = components['schemas']['ExecutionRecord']
export type PositionSnapshot = components['schemas']['PositionSnapshot']
export type TradingSignal = components['schemas']['TradingSignal']
export type SettingRead = components['schemas']['SettingRead']
export type SettingUpdate = components['schemas']['SettingUpdate']
export type UserProfile = components['schemas']['UserProfile']
export type UserListResponse = components['schemas']['UserListResponse']
export type UserRole = components['schemas']['UserRole']
export type LoginRequest = components['schemas']['LoginRequest']
export type CreateUserRequest = components['schemas']['CreateUserRequest']
export type UpdateUserRequest = components['schemas']['UpdateUserRequest']
export type ChangePasswordRequest = components['schemas']['ChangePasswordRequest']
export type AdminResetPasswordRequest = components['schemas']['AdminResetPasswordRequest']
export type ValidationError = components['schemas']['ValidationError']
export type HTTPValidationError = components['schemas']['HTTPValidationError']
export type ConfiguredProcess = components['schemas']['ConfiguredProcess']
export type ConfiguredProcessesResponse = components['schemas']['ConfiguredProcessesResponse']
export type AvailableProcess = components['schemas']['AvailableProcess']
export type AvailableProcessesResponse = components['schemas']['AvailableProcessesResponse']
export type ProcessRun = components['schemas']['ProcessRun']
export type ProcessRunsResponse = components['schemas']['ProcessRunsResponse']
export type ProcessSchemaResponse = components['schemas']['ProcessSchemaResponse']
export type ProcessCreatedInfo = components['schemas']['ProcessCreatedInfo']
export type ProcessCreateResponse = components['schemas']['ProcessCreateResponse']
export type ProcessCreateRequest = components['schemas']['ProcessCreateRequest']
export type ProcessStartRequest = components['schemas']['ProcessStartRequest']
export type ProcessStartResponse = components['schemas']['ProcessStartResponse']
export type ProcessStopResponse = components['schemas']['ProcessStopResponse']
export type ProcessStatus = components['schemas']['ProcessStatus']
export type SystemStatus = components['schemas']['SystemStatus']
export type HealthCheckResponse = components['schemas']['HealthCheckResponse']
export type MessageResponse = components['schemas']['MessageResponse']
