"""Tests for syncing Dockerfile tool pins from workspace state."""

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from scripts.update_tool_pins import COREPACK_ARG
from scripts.update_tool_pins import _default_root
from scripts.update_tool_pins import latest_npm_version
from scripts.update_tool_pins import main
from scripts.update_tool_pins import read_poetry_lock_version
from scripts.update_tool_pins import replace_arg_value
from scripts.update_tool_pins import sync_dockerfile_tool_pins


def test_default_root_returns_repository_root() -> None:
    """Default root resolves to the current repository root.

    Given: The update script is imported from the workspace scripts directory.
    When: The default root helper is called.
    Then: It returns the snapper repository root.
    """
    assert _default_root() == Path(__file__).resolve().parents[2]


def test_read_poetry_lock_version_returns_header_version(tmp_path: Path) -> None:
    """Poetry version is parsed from the canonical lockfile header.

    Given: A lockfile whose header contains a Poetry generator version.
    When: The lockfile version is read.
    Then: The exact header version is returned.
    """
    lock_path = tmp_path / "poetry.lock"
    lock_path.write_text(
        "# This file is automatically @generated by Poetry 2.4.1 and should not be changed by hand.\n",
        encoding="utf-8",
    )

    assert read_poetry_lock_version(lock_path) == "2.4.1"


def test_read_poetry_lock_version_raises_on_empty_file(tmp_path: Path) -> None:
    """Empty lockfiles fail loudly before header parsing.

    Given: An empty Poetry lockfile.
    When: The lockfile version is read.
    Then: A value error explains that the file is empty.
    """
    lock_path = tmp_path / "poetry.lock"
    lock_path.write_text("", encoding="utf-8")

    with pytest.raises(ValueError, match="is empty"):
        read_poetry_lock_version(lock_path)


def test_read_poetry_lock_version_raises_on_unknown_header(tmp_path: Path) -> None:
    """Unexpected lockfile headers fail loudly so the sync does not guess.

    Given: A lockfile without the canonical Poetry generated header.
    When: The lockfile version is read.
    Then: A value error explains that the version could not be parsed.
    """
    lock_path = tmp_path / "poetry.lock"
    lock_path.write_text("[metadata]\n", encoding="utf-8")

    with pytest.raises(ValueError, match="Could not parse Poetry version"):
        read_poetry_lock_version(lock_path)


def test_latest_npm_version_returns_trimmed_stdout() -> None:
    """Npm version lookup strips trailing whitespace from stdout.

    Given: The npm command returns a version with trailing whitespace.
    When: The latest package version is requested.
    Then: The returned version is stripped.
    """
    with patch("subprocess.run") as mock_run:
        mock_run.return_value = subprocess.CompletedProcess([], 0, stdout="0.35.1\n")

        assert latest_npm_version("corepack") == "0.35.1"


def test_latest_npm_version_raises_on_empty_stdout() -> None:
    """Empty npm responses are rejected instead of producing a blank pin.

    Given: The npm command succeeds but returns empty stdout.
    When: The latest package version is requested.
    Then: A value error prevents writing an empty Dockerfile pin.
    """
    with patch("subprocess.run") as mock_run:
        mock_run.return_value = subprocess.CompletedProcess([], 0, stdout="")

        with pytest.raises(ValueError, match="empty version"):
            latest_npm_version("corepack")


def test_replace_arg_value_updates_exact_assignment() -> None:
    """Docker ARG replacement rewrites only the matching assignment line.

    Given: Dockerfile text containing Corepack and Poetry ARG assignments.
    When: The Corepack ARG value is replaced.
    Then: Only the Corepack assignment changes.
    """
    original = "ARG COREPACK_VERSION=0.34.0\nARG POETRY_VERSION=2.3.4\n"

    updated = replace_arg_value(original, COREPACK_ARG, "0.35.0")

    assert updated == "ARG COREPACK_VERSION=0.35.0\nARG POETRY_VERSION=2.3.4\n"


def test_replace_arg_value_raises_when_arg_missing() -> None:
    """Missing ARG markers fail loudly so the Dockerfile contract stays explicit.

    Given: Dockerfile text without the requested ARG assignment.
    When: The ARG value replacement is attempted.
    Then: A value error explains that exactly one assignment was expected.
    """
    with pytest.raises(ValueError, match="Expected exactly one ARG COREPACK_VERSION"):
        replace_arg_value("FROM python:3.14-slim\n", COREPACK_ARG, "0.35.0")


def test_sync_dockerfile_tool_pins_writes_updated_versions(tmp_path: Path) -> None:
    """Dockerfile pin sync updates both tool ARGs and reports a change.

    Given: A Dockerfile whose Corepack and Poetry ARG pins are stale.
    When: Dockerfile tool pins are synchronized.
    Then: Both ARG values are rewritten and the function reports a change.
    """
    dockerfile_path = tmp_path / "Dockerfile"
    dockerfile_path.write_text(
        "FROM node:25-alpine\nARG COREPACK_VERSION=0.34.0\nFROM python:3.14-slim\nARG POETRY_VERSION=2.3.4\n",
        encoding="utf-8",
    )

    changed = sync_dockerfile_tool_pins(
        dockerfile_path,
        corepack_version="0.35.0",
        poetry_version="2.4.0",
    )

    assert changed is True
    assert "ARG COREPACK_VERSION=0.35.0" in dockerfile_path.read_text(encoding="utf-8")
    assert "ARG POETRY_VERSION=2.4.0" in dockerfile_path.read_text(encoding="utf-8")


def test_sync_dockerfile_tool_pins_is_noop_when_versions_match(tmp_path: Path) -> None:
    """Matching pins leave the Dockerfile untouched and report no change.

    Given: A Dockerfile whose tool ARG pins already match the requested versions.
    When: Dockerfile tool pins are synchronized.
    Then: The file contents remain unchanged and no change is reported.
    """
    dockerfile_path = tmp_path / "Dockerfile"
    content = "FROM node:25-alpine\nARG COREPACK_VERSION=0.35.0\nFROM python:3.14-slim\nARG POETRY_VERSION=2.4.0\n"
    dockerfile_path.write_text(content, encoding="utf-8")

    changed = sync_dockerfile_tool_pins(
        dockerfile_path,
        corepack_version="0.35.0",
        poetry_version="2.4.0",
    )

    assert changed is False
    assert dockerfile_path.read_text(encoding="utf-8") == content


def test_main_uses_overrides_and_prints_update(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """CLI overrides bypass auto-detection and update the Dockerfile in place.

    Given: CLI override versions and a temporary repository root.
    When: The pin sync CLI runs.
    Then: The Dockerfile is updated and the new pins are printed.
    """
    dockerfile_path = tmp_path / "Dockerfile"
    dockerfile_path.write_text(
        "FROM node:25-alpine\nARG COREPACK_VERSION=0.34.0\nFROM python:3.14-slim\nARG POETRY_VERSION=2.3.4\n",
        encoding="utf-8",
    )
    (tmp_path / "poetry.lock").write_text(
        "# This file is automatically @generated by Poetry 2.3.4 and should not be changed by hand.\n",
        encoding="utf-8",
    )

    result = main(
        [
            "--root",
            str(tmp_path),
            "--corepack-version",
            "0.35.0",
            "--poetry-version",
            "2.4.0",
        ]
    )

    assert result == 0
    captured = capsys.readouterr()
    assert "Updated Dockerfile" in captured.out
    assert "COREPACK_VERSION=0.35.0" in captured.out
    assert "POETRY_VERSION=2.4.0" in captured.out


def test_main_prints_noop_when_versions_already_match(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """CLI reports no-op when detected versions already match the Dockerfile.

    Given: Dockerfile pins already match the lockfile and npm lookup versions.
    When: The pin sync CLI runs without explicit version overrides.
    Then: The command reports that the Dockerfile already matches.
    """
    (tmp_path / "Dockerfile").write_text(
        "FROM node:25-alpine\nARG COREPACK_VERSION=0.35.0\nFROM python:3.14-slim\nARG POETRY_VERSION=2.4.0\n",
        encoding="utf-8",
    )
    (tmp_path / "poetry.lock").write_text(
        "# This file is automatically @generated by Poetry 2.4.0 and should not be changed by hand.\n",
        encoding="utf-8",
    )

    with patch("scripts.update_tool_pins.latest_npm_version", return_value="0.35.0"):
        result = main(["--root", str(tmp_path)])

    assert result == 0
    captured = capsys.readouterr()
    assert "Dockerfile already matches" in captured.out
    assert "COREPACK_VERSION=0.35.0" in captured.out
    assert "POETRY_VERSION=2.4.0" in captured.out
